Repository neoforged/NeoForge, pull requests merged in 2023-12, with the labels that each got.

#313 Remove the `RecipeSerializer` patch
  patches/net/minecraft/world/item/crafting/RecipeSerializer.java.patch
  src/main/java/net/neoforged/neoforge/common/crafting/ConditionalRecipe.java
Labels: bug, 1.20

#314 Deprecate mod id inference to prepare for the move of registration events to the Forge bus
  src/main/java/net/neoforged/neoforge/client/event/ModelEvent.java
  src/main/java/net/neoforged/neoforge/client/event/RegisterGuiOverlaysEvent.java
  src/main/java/net/neoforged/neoforge/client/event/RegisterNamedRenderTypesEvent.java
  src/main/java/net/neoforged/neoforge/registries/RegisterEvent.java
Labels: documentation, 1.20

#296 Event for finer-grained control over using items on blocks
  .gitignore
  patches/net/minecraft/world/item/ItemStack.java.patch
  patches/net/minecraft/world/level/block/state/BlockBehaviour.java.patch
  src/main/java/net/neoforged/neoforge/event/entity/player/PlayerInteractEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/player/UseItemOnBlockEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/player/UseItemOnBlockEventTest.java
  tests/src/main/resources/META-INF/mods.toml
Labels: enhancement, 1.20

#318 Bump FML and SJH
  gradle.properties
Labels: 1.20

#326 [1.20.3] Fix particles jittering when ticks are frozen
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
Labels: bug, 1.20, rendering

#319 addOptionalTag/s methods that allow passing the TagKey itself instead of passing the location
  src/main/java/net/neoforged/neoforge/common/extensions/ITagAppenderExtension.java
Labels: enhancement, 1.20

#327 [1.20.3] Fix render bounds of various BERs and add render bounds debug renderer
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/BannerRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/BrushableBlockRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/ChestRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/ConduitRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/DecoratedPotRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/ShulkerBoxRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/SkullBlockRenderer.java.patch
  patches/net/minecraft/world/level/block/entity/SignBlockEntity.java.patch
  src/main/java/net/neoforged/neoforge/client/BlockEntityRenderBoundsDebugRenderer.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockEntityExtension.java
Labels: bug, 1.20, rendering

#333 Fix GameTest server generating a full world
  patches/net/minecraft/server/Main.java.patch
Labels: bug, 1.20, regression

#340 Fix IAttachmentHolder#hasData(Supplier) not working with DeferredHolders
  src/main/java/net/neoforged/neoforge/attachment/IAttachmentHolder.java
Labels: bug, 1.20

#342 Merge strict and partial NBT ingredients
  patches/net/minecraft/world/item/ItemStack.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/crafting/CraftingHelper.java
  src/main/java/net/neoforged/neoforge/common/crafting/NBTIngredient.java
  src/main/java/net/neoforged/neoforge/common/crafting/PartialNBTIngredient.java
  src/main/java/net/neoforged/neoforge/common/crafting/StrictNBTIngredient.java
  testframework/src/main/java/net/neoforged/testframework/condition/TestEnabledIngredient.java
  testframework/src/main/java/net/neoforged/testframework/gametest/ExtendedGameTestHelper.java
  testframework/src/main/java/net/neoforged/testframework/impl/TestFrameworkMod.java
  tests/src/generated/resources/data/data_gen_test/advancements/recipes/tools/contains_nbt_ingredient_single_item.json
  tests/src/generated/resources/data/data_gen_test/recipes/compound_ingredient_custom_types.json
  tests/src/generated/resources/data/data_gen_test/recipes/contains_nbt_ingredient_item_set.json
  tests/src/generated/resources/data/data_gen_test/recipes/contains_nbt_ingredient_single_item.json
  tests/src/generated/resources/data/data_gen_test/recipes/difference_ingredient.json
  tests/src/generated/resources/data/data_gen_test/recipes/exact_nbt_ingredient.json
  tests/src/generated/resources/data/neotests_partial_nbtingredient/advancements/recipes/misc/partial_nbt.json
  tests/src/generated/resources/data/neotests_partial_nbtingredient/recipes/partial_nbt.json
  tests/src/generated/resources/data/neotests_strict_nbtingredient/advancements/recipes/misc/strict_nbt.json
  tests/src/generated/resources/data/neotests_strict_nbtingredient/recipes/strict_nbt.json
  tests/src/main/java/net/neoforged/neoforge/debug/crafting/IngredientTests.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/DataGeneratorTest.java
Labels: bug, 1.20, regression, breaking change

#358 [1.20.4] Split mod logo filepath on slashes for mod list menu
  src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java
Labels: bug, 1.20

#366 [1.20.4] Restore serversided onInteractEntityAt event firing
  patches/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
  tests/src/main/java/net/neoforged/neoforge/debug/entity/player/PlayerEventTests.java
Labels: bug, 1.20, regression

#315 New event: ClientPauseUpdateEvent
  patches/net/minecraft/client/Minecraft.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/ClientPauseUpdatedEvent.java
Labels: enhancement, 1.20

#352 [1.20.4] Made mod list search bar 2 pixels wider
  src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: bug, 1.20, rendering

#353 [1.20.4] Have Fishing Rods call onPlayerDestroyItem when they break
  patches/net/minecraft/world/item/FishingRodItem.java.patch
Labels: bug, 1.20

#343 Remove unsafe dispatch codec
  patches/net/minecraft/advancements/critereon/ItemPredicate.java.patch
  src/main/java/net/neoforged/neoforge/common/conditions/ConditionalOps.java
  src/main/java/net/neoforged/neoforge/common/conditions/FalseCondition.java
  src/main/java/net/neoforged/neoforge/common/conditions/ICondition.java
  src/main/java/net/neoforged/neoforge/common/conditions/TrueCondition.java
  src/main/java/net/neoforged/neoforge/common/crafting/CraftingHelper.java
  src/main/java/net/neoforged/neoforge/common/util/NeoForgeExtraCodecs.java
Labels: 1.20, cleanup, breaking change

#384 [1.20.4] Fix shulker box, end gateway, spawner, trial spawner and piston render bounds
  patches/net/minecraft/client/renderer/blockentity/PistonHeadRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/ShulkerBoxRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/SpawnerRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/TheEndGatewayRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/TrialSpawnerRenderer.java.patch
Labels: bug, 1.20, rendering

#365 [1.20.4] Fixed NeoForge pack version and description (Attempt 2)
  patches/net/minecraft/server/packs/metadata/pack/PackMetadataSection.java.patch
  patches/net/minecraft/server/packs/repository/Pack.java.patch
  src/generated/resources/pack.mcmeta
  src/main/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/DataGeneratorTest.java
Labels: bug, 1.20, breaking change

#367 [1.20.4] Change how resource pack grouping works and group mod data packs - take 2
  gradle.properties
  patches/net/minecraft/client/Options.java.patch
  patches/net/minecraft/client/gui/screens/packs/PackSelectionModel.java.patch
  patches/net/minecraft/client/gui/screens/packs/PackSelectionScreen.java.patch
  patches/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.java.patch
  patches/net/minecraft/server/MinecraftServer.java.patch
  patches/net/minecraft/server/commands/DataPackCommand.java.patch
  patches/net/minecraft/server/packs/repository/Pack.java.patch
  patches/net/minecraft/server/packs/repository/PackRepository.java.patch
  patches/net/minecraft/server/packs/resources/FallbackResourceManager.java.patch
  src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java
  src/main/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/data/ExistingFileHelper.java
  src/main/java/net/neoforged/neoforge/common/extensions/IPackResourcesExtension.java
  src/main/java/net/neoforged/neoforge/resource/DelegatingPackResources.java
  src/main/java/net/neoforged/neoforge/resource/EmptyPackResources.java
  src/main/java/net/neoforged/neoforge/resource/ResourcePackLoader.java
  src/main/java/net/neoforged/neoforge/server/ServerLifecycleHooks.java
  src/main/resources/assets/neoforge/lang/en_us.json
  tests/src/generated/resources/pack.mcmeta
  tests/src/main/java/net/neoforged/neoforge/debug/resources/OverlayTests.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/DataGeneratorTest.java
  tests/src/main/resources/data/pack_overlays_test/tags/blocks/must_be_overlayed.json
  tests/src/main/resources/pack_overlays_test/data/pack_overlays_test/tags/blocks/must_be_overlayed.json
Labels: enhancement, 1.20, breaking change

#344 [1.20.4 ] Fixed LootTableLoadEvent not being called
  patches/net/minecraft/world/level/storage/loot/LootDataType.java.patch
  patches/net/minecraft/world/level/storage/loot/LootTable.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/conditions/ConditionalOps.java
  src/main/java/net/neoforged/neoforge/common/util/NeoForgeExtraCodecs.java
  src/main/java/net/neoforged/neoforge/event/LootTableLoadEvent.java
Labels: bug, 1.20, regression

#389 Add StatAwardEvent
  patches/net/minecraft/stats/StatsCounter.java.patch
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/StatAwardEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/player/PlayerEventTests.java
Labels: enhancement, 1.20

#350 [1.20.4] Rework how effects determine what they can be cured by
  .teamcity/patches/buildTypes/MinecraftForge_MinecraftForge__Build.kts
  .teamcity/patches/buildTypes/MinecraftForge_MinecraftForge__BuildSecondaryBranches.kts
  .teamcity/patches/projects/_Self.kts
  patches/net/minecraft/world/effect/MobEffectInstance.java.patch
  patches/net/minecraft/world/entity/LivingEntity.java.patch
  patches/net/minecraft/world/item/HoneyBottleItem.java.patch
  patches/net/minecraft/world/item/MilkBucketItem.java.patch
  src/main/java/net/neoforged/neoforge/common/EffectCure.java
  src/main/java/net/neoforged/neoforge/common/EffectCures.java
  src/main/java/net/neoforged/neoforge/common/extensions/IMobEffectExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IMobEffectInstanceExtension.java
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/entity/living/MobEffectEvent.java
  testframework/src/main/java/net/neoforged/testframework/gametest/ExtendedGameTestHelper.java
  tests/src/main/java/net/neoforged/neoforge/debug/effect/MobEffectTests.java
Labels: 1.20, cleanup, breaking change

#357 [1.20.4] Render demo mode remaining time text properly
  patches/net/minecraft/client/gui/components/DebugScreenOverlay.java.patch
  src/main/java/net/neoforged/neoforge/client/gui/overlay/VanillaGuiOverlay.java
Labels: bug, 1.20, rendering

#392 Add copyOf and codecOf utility methods to NonNullList
  patches/net/minecraft/core/NonNullList.java.patch
Labels: enhancement, 1.20

#351 [1.20.4] Added trident throw and brushing tool actions
  patches/net/minecraft/world/item/BrushItem.java.patch
  patches/net/minecraft/world/item/TridentItem.java.patch
  src/main/java/net/neoforged/neoforge/common/ToolActions.java
Labels: enhancement, 1.20

#355 [1.20.4] Make keybind menu have scrolling descriptions
  patches/net/minecraft/client/gui/screens/controls/KeyBindsList.java.patch
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, 1.20, rendering

#379 [1.20.4] Make player feet and eyes both need to be in swimmable fluid to swim
  patches/net/minecraft/world/entity/Entity.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IEntityExtension.java
Labels: bug, 1.20

#386 Add an incompatible/discouraged clause to mod dependency
  gradle.properties
  src/main/java/net/neoforged/neoforge/common/I18nExtension.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, breaking change

#369 Implement fluid handler support for cauldrons
  patches/net/minecraft/world/level/block/AbstractCauldronBlock.java.patch
  src/main/java/net/neoforged/neoforge/capabilities/BlockCapability.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/fluids/CauldronFluidContent.java
  src/main/java/net/neoforged/neoforge/fluids/RegisterCauldronFluidContentEvent.java
  src/main/java/net/neoforged/neoforge/fluids/capability/wrappers/CauldronWrapper.java
  src/main/java/net/neoforged/neoforge/internal/RegistrationEvents.java
  tests/src/main/java/net/neoforged/neoforge/debug/capabilities/VanillaHandlersTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/capability/CapabilityTests.java
Labels: enhancement, 1.20

#394 1.20.1 actions
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue_report.md
  .github/stale.yml
  .github/workflows/build-prs.yml
  .github/workflows/release.yml
  .teamcity/pom.xml
  .teamcity/settings.kts
  build.gradle
Labels: 1.20, cleanup, CI

#364 [1.20.4] Improve NeoForge's chunk generator command
  src/main/java/net/neoforged/neoforge/server/command/ChunkGenWorker.java
  src/main/java/net/neoforged/neoforge/server/command/GenerateCommand.java
  src/main/java/net/neoforged/neoforge/server/command/generation/CoarseOnionIterator.java
  src/main/java/net/neoforged/neoforge/server/command/generation/GenerationBar.java
  src/main/java/net/neoforged/neoforge/server/command/generation/GenerationTask.java
  src/main/java/net/neoforged/neoforge/server/command/generation/OnionIterator.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, 1.20

#403 [1.20.4] Fix grouped mod datapacks being dropped when reloading data
  patches/net/minecraft/server/MinecraftServer.java.patch
  patches/net/minecraft/server/packs/repository/Pack.java.patch
  tests/src/generated/resources/data/neotests_mod_datapack/advancements/recipes/misc/test_advancement.json
  tests/src/main/java/net/neoforged/neoforge/debug/resources/ModDatapackTest.java
Labels: bug, 1.20, regression

#400 Allow mods to not provide pack information
  src/main/java/net/neoforged/neoforge/resource/ResourcePackLoader.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, 1.20

#401 Fix GameTestHelper#forEveryBlockInStructure including blocks that are not in the structure
  patches/net/minecraft/gametest/framework/GameTestHelper.java.patch
  tests/src/main/java/net/neoforged/neoforge/debug/structure/StructureTests.java
Labels: bug, 1.20

#405 Publish changelog in 1.20.1
  build.gradle
Labels: bug, 1.20, CI

#408 Fix world deletion cancel not working
  patches/net/minecraft/client/gui/screens/worldselection/WorldSelectionList.java.patch
Labels: bug, 1.20

#404 Replicate vanilla's loading progess bar better
  src/main/java/net/neoforged/neoforge/client/loading/NeoForgeLoadingOverlay.java
Labels: enhancement, 1.20

#397 Add reason field support to mandatory deps
  gradle.properties
  src/main/java/net/neoforged/neoforge/common/I18nExtension.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, 1.20

#415 Correctly filter out hidden packs from unselected packs in pack selection screen
  patches/net/minecraft/client/gui/screens/packs/PackSelectionModel.java.patch
Labels: bug, 1.20

#396 Release 20.2 with actions
  .github/workflows/build-prs.yml
  .github/workflows/release.yml
  .teamcity/patches/buildTypes/MinecraftForge_MinecraftForge__BuildSecondaryBranches.kts
  .teamcity/pom.xml
  .teamcity/settings.kts
  build.gradle
  projects/neoforge/build.gradle
Labels: 1.20, cleanup, ci/build

#416 Remove glazed terracotta as farmland for `DESERT` plant type
  patches/net/minecraft/world/level/block/Block.java.patch
  tests/src/main/java/net/neoforged/neoforge/debug/block/BlockTests.java
Labels: bug, 1.20

#414 [1.20.4] Fix inconsistency between custom registry ID getters and the vanilla one
  patches/net/minecraft/core/MappedRegistry.java.patch
  src/main/java/net/neoforged/neoforge/registries/IRegistryExtension.java
Labels: bug, 1.20

#421 [1.20.4] Remove ban screen creation patch
  patches/net/minecraft/client/Minecraft.java.patch
Labels: bug, 1.20

#420 [1.20.4] Reinstate early return on empty block pick result
  patches/net/minecraft/client/Minecraft.java.patch
Labels: bug, 1.20

#419 Apply getDropItem AT to correct class
  src/main/resources/META-INF/accesstransformer.cfg
Labels: bug, 1.20

#413 Add some more tests
  testframework/src/main/java/net/neoforged/testframework/gametest/ExtendedGameTestHelper.java
  testframework/src/main/java/net/neoforged/testframework/gametest/ParametrizedGameTestSequence.java
  testframework/src/main/java/net/neoforged/testframework/impl/reg/RegistrationHelperImpl.java
  testframework/src/main/java/net/neoforged/testframework/registration/DeferredAttachmentTypes.java
  testframework/src/main/java/net/neoforged/testframework/registration/RegistrationHelper.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/ClientEventTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/EntityEventTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/living/LivingEntityEventTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/player/PlayerEventTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/item/ItemEventTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/item/ItemTests.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/entity/AddEntityAttributeTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/entity/living/LivingConversionEventTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/entity/living/LivingGetProjectileEventTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/entity/living/LivingSetAttackTargetEventTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/entity/player/PermissionsChangedEventTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/entity/player/PlayerGameModeEventTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/item/CustomMobBucketTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/item/ItemAttributeModifierTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/item/ShieldBlockTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/item/SnowBootsTest.java
  tests/src/main/resources/META-INF/mods.toml
Labels: 1.20, cleanup

#423 Bump FML version and use FML SPI artifact.
  gradle.properties
  projects/neoforge/build.gradle
Labels: 1.20, cleanup

#425 [1.20.4] Reimplement ID offset on modded EntityDataSerializers
  patches/net/minecraft/network/syncher/EntityDataSerializers.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/EntityDataSerializerTest.java
Labels: bug, 1.20

#427 Remove conditional recipe serializer, use regular conditions instead
  patches/net/minecraft/world/item/crafting/RecipeManager.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/crafting/ConditionalRecipe.java
  src/main/java/net/neoforged/neoforge/common/crafting/CraftingHelper.java
Labels: cleanup, breaking change

#430 [1.20.2] Reimplement ID offset on modded EntityDataSerializers
  patches/net/minecraft/network/syncher/EntityDataSerializers.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
Labels: bug, 1.20

#429 Infrastructure for PR publishing
  .github/workflows/build-prs.yml
  .github/workflows/publish-prs.yml
  .github/workflows/release.yml
  build.gradle
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/forge/snapshots/ForgeSnapshotsModClient.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: 1.20, ci/build

#434 Fix EmptyModel.BAKED returning null quad list
  src/main/java/net/neoforged/neoforge/client/model/EmptyModel.java
Labels: bug, 1.20, rendering

#437 [1.20.4] Fix seams on generated item models (MC-73186)
  patches/net/minecraft/client/renderer/block/model/ItemModelGenerator.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/model/DynamicFluidContainerModel.java
  src/main/java/net/neoforged/neoforge/client/model/ItemLayerModel.java
  src/main/java/net/neoforged/neoforge/client/model/geometry/UnbakedGeometryHelper.java
  tests/src/main/resources/assets/custom_fluid_container_test/models/item/custom_fluid_container.json
Labels: bug, 1.20, rendering, breaking change, vanilla bug

#439 Add Crowdin configuration file
  crowdin.yml
Labels: enhancement, 1.20, l10n

#442 Update FML to prevent the Netty exceptions from being logged
  gradle.properties
Labels: enhancement, 1.20

#440 Fix signature of simpleCookingRecipe in AT
  src/main/resources/META-INF/accesstransformer.cfg
Labels: bug, 1.20, regression

#446 New Crowdin updates
  src/main/resources/assets/neoforge/lang/de_de.json
  src/main/resources/assets/neoforge/lang/en_gb.json
  src/main/resources/assets/neoforge/lang/es_es.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_hk.json
Labels: l10n

#435 Add back Level data attachments
  patches/net/minecraft/server/level/ServerLevel.java.patch
  patches/net/minecraft/world/level/Level.java.patch
  src/main/java/net/neoforged/neoforge/attachment/AttachmentType.java
  src/main/java/net/neoforged/neoforge/attachment/LevelAttachmentsSavedData.java
Labels: enhancement, 1.20, regression
