Repository neoforged/NeoForge, pull requests merged in 2023-08, with the labels that each got.

#72 [1.20.x] Actually post PlayerSpawnPhantomsEvent
  patches/minecraft/net/minecraft/world/level/levelgen/PhantomSpawner.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/test/java/net/minecraftforge/debug/entity/player/PlayerSpawnPhantomsEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: bug, 1.20

#68 Fix server installer
  build.gradle
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/TeamcityRequests.groovy
Labels: bug, 1.20

#79 Remove `equals` override in `ResourceKey`
  patches/minecraft/net/minecraft/resources/ResourceKey.java.patch
Labels: bug, 1.20, performance

#86 Update neo branding to final
  build.gradle
  docs/assets/installer.png
  docs/assets/neoforged.ico
  src/main/resources/neoforged_logo.png
Labels: documentation, enhancement, 1.20

#87 Use new logo in README
  build.gradle
  docs/README.md
  docs/assets/NeoForged_logo.svg
  docs/assets/installer.png
  docs/assets/neoforged_logo.png
  docs/assets/shitty_neoforged_installer_icon.ico
  docs/assets/shitty_neoforged_logo.png
Labels: documentation

#98 Fix `Level` leak in debug HUD
  src/main/java/net/minecraftforge/client/gui/overlay/ForgeGui.java
Labels: bug, 1.20

#95 Fix world creation screen being suppressed after world deletion
  patches/minecraft/net/minecraft/client/gui/screens/worldselection/WorldSelectionList.java.patch
Labels: bug, 1.20

#99 Fix chunk future chain not being bypassed for entity loads in 1.17+
  patches/minecraft/net/minecraft/server/level/ChunkMap.java.patch
Labels: bug, 1.20

#100 Don't warn about potentially malformed pack mcmeta files in datagen
  patches/minecraft/net/minecraft/server/packs/resources/MultiPackResourceManager.java.patch
Labels: enhancement, 1.20

#113 Keep order of sources in PackRepository
  patches/minecraft/net/minecraft/server/packs/repository/PackRepository.java.patch
Labels: bug, 1.20
