Repository neoforged/NeoForge, pull requests merged in 2023-11, with the labels that each got.

#227 Use updated translation keys in commands/command arguments
  src/main/java/net/neoforged/neoforge/server/command/EnumArgument.java
  src/main/java/net/neoforged/neoforge/server/command/ModListCommand.java
  src/main/java/net/neoforged/neoforge/server/command/TPSCommand.java
  src/main/java/net/neoforged/neoforge/server/command/TagsCommand.java
Labels: bug, 1.20

#203 [1.20.2] Fix ObjLoader leaking and using outdated ResourceManager
  src/main/java/net/neoforged/neoforge/client/model/obj/ObjLoader.java
  src/main/java/net/neoforged/neoforge/client/model/obj/ObjModel.java
Labels: bug, 1.20, rendering

#193 Partial gamerule support for FluidType#canConvertToSource of vanilla fluids
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
Labels: enhancement, 1.20

#231 Use Correct PoseStack in AFTER_LEVEL
  patches/net/minecraft/client/renderer/GameRenderer.java.patch
Labels: bug, 1.20, rendering, triage

#222 Fix signed chat state de-sync caused by `execute run say`
  patches/net/minecraft/network/chat/SignableCommand.java.patch
Labels: bug, 1.20

#234 Remove unneeded `ItemPredicate` extra methods
  patches/net/minecraft/advancements/critereon/ItemPredicate.java.patch
Labels: 1.20, cleanup

#237 [1.20.2] Fix player renderer getter in EntityRenderersEvent.AddLayers
  src/main/java/net/neoforged/neoforge/client/event/EntityRenderersEvent.java
Labels: bug, 1.20, regression, breaking change

#239 [1.20.2] Fix mouse scroll events and scroll axis handling
  patches/net/minecraft/client/MouseHandler.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/InputEvent.java
  src/main/java/net/neoforged/neoforge/client/event/ScreenEvent.java
Labels: bug, enhancement, 1.20, regression, breaking change

#244 [1.20.2] Fix waterlogged blocks being flammable
  patches/net/minecraft/world/level/block/FireBlock.java.patch
  patches/net/minecraft/world/level/material/LavaFluid.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/resources/forge.exc
Labels: bug, 1.20

#146 Allow datagen to use vanilla armor trim textures
  src/main/java/net/neoforged/neoforge/client/model/generators/ItemModelBuilder.java
  src/main/java/net/neoforged/neoforge/client/model/generators/ModelProvider.java
  tests/src/generated/resources/assets/data_gen_test/models/item/test_runtime_texture_model.json
  tests/src/main/java/net/neoforged/neoforge/debug/DataGeneratorTest.java
Labels: enhancement, 1.20

#145 Unbreak the MC-176559 fix
  patches/net/minecraft/client/multiplayer/MultiPlayerGameMode.java.patch
Labels: bug, 1.20, triage

#247 [1.20.2] Fix misplaced patch in FireBlock
  patches/net/minecraft/world/level/block/FireBlock.java.patch
Labels: bug, 1.20, regression

#240 Fix advancement existing file helper checks in datagen
  src/main/java/net/neoforged/neoforge/common/extensions/IAdvancementBuilderExtension.java
  tests/src/generated/resources/data/minecraft/advancements/obtain_diamond_block.json
  tests/src/main/java/net/neoforged/neoforge/debug/DataGeneratorTest.java
Labels: bug, 1.20

#175 Correct a grammatical mistake within SUPPORT.md
  docs/SUPPORT.md
Labels: documentation, 1.20

#253 Fix entity loot datagen not using getKnownEntityTypes()
  patches/net/minecraft/data/loot/EntityLootSubProvider.java.patch
Labels: bug, 1.20, regression

#250 Redo conditional recipe datagen
  patches/net/minecraft/data/recipes/FinishedRecipe.java.patch
  patches/net/minecraft/data/recipes/RecipeOutput.java.patch
  patches/net/minecraft/data/recipes/RecipeProvider.java.patch
  src/main/java/net/neoforged/neoforge/common/conditions/ICondition.java
  src/main/java/net/neoforged/neoforge/common/crafting/ConditionalRecipeBuilder.java
  src/main/java/net/neoforged/neoforge/common/crafting/ConditionalRecipeOutput.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeRecipeProvider.java
  src/main/java/net/neoforged/neoforge/common/extensions/IRecipeOutputExtension.java
  tests/src/generated/resources/data/data_gen_test/advancements/recipes/building_blocks/conditional.json
  tests/src/generated/resources/data/data_gen_test/advancements/recipes/building_blocks/conditional2.json
  tests/src/generated/resources/data/data_gen_test/advancements/recipes/building_blocks/conditional3.json
  tests/src/generated/resources/data/data_gen_test/advancements/recipes/building_blocks/conditional4.json
  tests/src/generated/resources/data/data_gen_test/recipes/conditional.json
  tests/src/generated/resources/data/data_gen_test/recipes/conditional2.json
  tests/src/generated/resources/data/data_gen_test/recipes/conditional3.json
  tests/src/generated/resources/data/data_gen_test/recipes/conditional4.json
  tests/src/main/java/net/neoforged/neoforge/debug/DataGeneratorTest.java
Labels: bug, enhancement, 1.20, breaking change

#163 Remove redundant zombie spawn chance config
  patches/net/minecraft/world/entity/monster/Zombie.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeConfig.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: 1.20, breaking change

#232 Fix some issues with the README
  docs/README.md
Labels: documentation, 1.20

#70 [1.20.x] Swapped codec of `EnvironmentScanPlacement` for `Direction` for less restrictions
  patches/net/minecraft/world/level/levelgen/placement/EnvironmentScanPlacement.java.patch
Labels: enhancement, 1.20

#173 Call IForgeBakedModel::getModelData when rendering block breaking texture
  patches/net/minecraft/client/renderer/block/BlockRenderDispatcher.java.patch
Labels: bug, 1.20, rendering

#170 Fix milk bucket curing effects before advancement trigger
  patches/net/minecraft/world/item/MilkBucketItem.java.patch
Labels: bug, 1.20, triage

#241 [1.20.2] Fix blending issues caused by item decorators
  patches/com/mojang/blaze3d/platform/GlStateManager.java.patch
  patches/com/mojang/blaze3d/systems/RenderSystem.java.patch
  src/main/java/net/neoforged/neoforge/client/GlStateBackup.java
  src/main/java/net/neoforged/neoforge/client/ItemDecoratorHandler.java
Labels: bug, 1.20, rendering

#267 Use the correct namespace in the MobEffectIdFix patch
  patches/net/minecraft/util/datafix/fixes/MobEffectIdFix.java.patch
Labels: bug, 1.20

#172 Fix worlds becoming unusable after custom dimension is removed
  src/main/java/net/neoforged/neoforge/common/LenientUnboundedMapCodec.java
Labels: bug, 1.20, regression

#266 [1.20.2] Use map backing the atlas instead of the atlas itself for liquid texture lookups
  patches/net/minecraft/client/renderer/block/LiquidBlockRenderer.java.patch
  patches/net/minecraft/client/renderer/texture/TextureAtlas.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/textures/FluidSpriteCache.java
Labels: bug, 1.20, rendering

#171 Fix KeyMapping modifiers not being respected in conflicting bindings
  src/main/java/net/neoforged/neoforge/client/settings/KeyMappingLookup.java
Labels: bug, 1.20, regression

#149 Remove redundant `getResource` call in DelegatingPackResources
  src/main/java/net/neoforged/neoforge/resource/DelegatingPackResources.java
Labels: 1.20, cleanup

#269 [1.20.2] Allow blocks complete control over breaking sounds
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
  src/main/java/net/neoforged/neoforge/client/extensions/common/IClientBlockExtensions.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/CustomBreakSoundTest.java
  tests/src/main/resources/META-INF/mods.toml
Labels: enhancement, 1.20

#272 Use `Entity#positionRider` to resync player with vehicle position
  patches/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
Labels: bug, 1.20

#246 Add Pointed Dripstone drip support to FluidTypes
  patches/net/minecraft/world/level/block/CauldronBlock.java.patch
  patches/net/minecraft/world/level/block/PointedDripstoneBlock.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/SoundActions.java
  src/main/java/net/neoforged/neoforge/fluids/FluidType.java
  src/main/resources/META-INF/accesstransformer.cfg
  tests/src/main/java/net/neoforged/neoforge/debug/fluid/FluidTypeTest.java
Labels: enhancement, 1.20

#276 [1.20.2] Move access change in AbstractButton to AT
  patches/net/minecraft/client/gui/components/AbstractButton.java.patch
  src/main/resources/META-INF/accesstransformer.cfg
Labels: cleanup

#251 Update condition key, rewrite `ConditionalCodec` implementation and add tests
  patches/net/minecraft/data/DataProvider.java.patch
  patches/net/minecraft/data/recipes/RecipeProvider.java.patch
  patches/net/minecraft/resources/RegistryDataLoader.java.patch
  patches/net/minecraft/world/item/crafting/RecipeManager.java.patch
  patches/net/minecraft/world/level/storage/loot/LootDataType.java.patch
  patches/net/minecraft/world/level/storage/loot/LootTable.java.patch
  src/main/java/net/neoforged/neoforge/common/conditions/ConditionalOps.java
  src/main/java/net/neoforged/neoforge/common/conditions/ICondition.java
  src/main/java/net/neoforged/neoforge/common/conditions/WithConditions.java
  src/main/java/net/neoforged/neoforge/common/data/JsonCodecProvider.java
  src/main/java/net/neoforged/neoforge/common/loot/IGlobalLootModifier.java
  src/main/java/net/neoforged/neoforge/common/util/NeoForgeExtraCodecs.java
  tests/src/generated/resources/data/data_gen_test/advancements/recipes/building_blocks/conditional.json
  tests/src/generated/resources/data/data_gen_test/advancements/recipes/building_blocks/conditional2.json
  tests/src/generated/resources/data/data_gen_test/advancements/recipes/building_blocks/conditional3.json
  tests/src/generated/resources/data/data_gen_test/advancements/recipes/building_blocks/conditional4.json
  tests/src/generated/resources/data/data_gen_test/recipes/conditional.json
  tests/src/generated/resources/data/data_gen_test/recipes/conditional2.json
  tests/src/generated/resources/data/data_gen_test/recipes/conditional3.json
  tests/src/generated/resources/data/data_gen_test/recipes/conditional4.json
  tests/src/main/java/net/neoforged/neoforge/debug/conditions/ConditionalCodecTest.java
  tests/src/main/resources/META-INF/mods.toml
  tests/src/main/resources/data/recipe_book_extension_test/advancements/recipes/recipe_book_extension_advancment.json
  tests/src/main/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_1.json
  tests/src/main/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_2.json
  tests/src/main/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_3.json
  tests/src/main/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_4.json
  tests/src/main/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_5.json
Labels: bug, 1.20, cleanup, breaking change

#283 [1.20.2] Band-aid fix connections between Neo and vanilla
  patches/net/minecraft/client/multiplayer/ClientConfigurationPacketListenerImpl.java.patch
  patches/net/minecraft/network/protocol/handshake/ClientIntentionPacket.java.patch
Labels: bug, 1.20, regression, blocks stable

#288 Rename certain DR subclass helpers as being 'simple'
  src/main/java/net/neoforged/neoforge/registries/DeferredRegister.java
  tests/src/main/java/net/neoforged/neoforge/debug/CustomSoundTypeTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/DeferredRegistryTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/BlockEntityOnLoadTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/CustomBreakSoundTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/CustomRespawnTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/FullPotsAccessorDemo.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/HideNeighborFaceTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/LevelSensitiveLightBlockTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/OnTreeGrowBlockTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/PistonEventTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/RedstoneSidedConnectivityTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/StickyBlockTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/ValidRailShapeTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/AmbientOcclusionElementsTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/CustomColorResolverTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/EmissiveElementsTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/model/MegaModelTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/model/MultiLayerModelTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/model/NewModelLoaderTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/item/TagBasedToolTypesTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/misc/GameTestTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/world/ForgeChunkManagerTest.java
Labels: 1.20, cleanup, breaking change

#284 Remove Neo's own PathPackResources
  patches/com/mojang/blaze3d/platform/GlStateManager.java.patch
  patches/com/mojang/blaze3d/systems/RenderSystem.java.patch
  src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java
  src/main/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/main/java/net/neoforged/neoforge/resource/PathPackResources.java
  src/main/java/net/neoforged/neoforge/resource/ResourcePackLoader.java
  src/main/java/net/neoforged/neoforge/server/ServerLifecycleHooks.java
Labels: 1.20, cleanup, breaking change

#279 Avoid O(n) complexity in MappedRegistry register methods
  patches/net/minecraft/core/MappedRegistry.java.patch
Labels: 1.20, performance

#294 Fix the `test runthis` command
  patches/net/minecraft/gametest/framework/GameTestInfo.java.patch
  patches/net/minecraft/gametest/framework/TestCommand.java.patch
Labels: bug, 1.20

#254 [20.2] Cleanup vanilla bugfixes
  patches/net/minecraft/client/multiplayer/ClientPacketListener.java.patch
  patches/net/minecraft/client/player/LocalPlayer.java.patch
  patches/net/minecraft/client/renderer/texture/TextureManager.java.patch
  patches/net/minecraft/world/entity/ExperienceOrb.java.patch
  patches/net/minecraft/world/entity/LivingEntity.java.patch
  patches/net/minecraft/world/entity/vehicle/Boat.java.patch
  patches/net/minecraft/world/level/block/PoweredRailBlock.java.patch
  patches/net/minecraft/world/level/block/RailBlock.java.patch
Labels: 1.20, cleanup

#77 [1.20.2] Add an event to register custom sprite source types
  patches/net/minecraft/client/renderer/texture/atlas/SpriteResourceLoader.java.patch
  patches/net/minecraft/client/renderer/texture/atlas/SpriteSources.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/RegisterSpriteSourceTypesEvent.java
  src/main/java/net/neoforged/neoforge/client/textures/SpriteContentsConstructor.java
  src/main/java/net/neoforged/neoforge/data/loading/DatagenModLoader.java
  src/main/resources/META-INF/accesstransformer.cfg
  tests/src/main/java/net/neoforged/neoforge/debug/client/CustomSpriteSourceTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/CustomTASTest.java
  tests/src/main/resources/META-INF/mods.toml
  tests/src/main/resources/assets/custom_sprite_source_test/models/item/test_item.json
  tests/src/main/resources/assets/custom_sprite_source_test/textures/test_item.png
  tests/src/main/resources/assets/custom_tas_test/textures/item/test_item.png.mcmeta
  tests/src/main/resources/assets/minecraft/atlases/blocks.json
Labels: enhancement, 1.20

#300 Restore smelting result count and nbt extensions
  patches/net/minecraft/world/item/crafting/SimpleCookingSerializer.java.patch
  src/main/java/net/neoforged/neoforge/common/crafting/CraftingHelper.java
  tests/src/main/resources/data/recipe_extensions/recipes/smelting_multi_output.json
Labels: enhancement, 1.20, regression

#310 Short-circuit the realms availability check in dev
  patches/com/mojang/realmsclient/RealmsAvailability.java.patch
Labels: enhancement, 1.20, loading

#286 Fix and change chunk ticket registration
  patches/net/minecraft/server/MinecraftServer.java.patch
  patches/net/minecraft/server/level/ServerLevel.java.patch
  patches/net/minecraft/world/level/ForcedChunksSavedData.java.patch
  src/main/java/net/neoforged/neoforge/common/world/ForcedChunkManager.java
  src/main/java/net/neoforged/neoforge/common/world/chunk/ForcedChunkManager.java
  src/main/java/net/neoforged/neoforge/common/world/chunk/LoadingValidationCallback.java
  src/main/java/net/neoforged/neoforge/common/world/chunk/RegisterTicketControllersEvent.java
  src/main/java/net/neoforged/neoforge/common/world/chunk/TicketController.java
  src/main/java/net/neoforged/neoforge/common/world/chunk/TicketHelper.java
  src/main/java/net/neoforged/neoforge/common/world/chunk/TicketSet.java
  src/main/java/net/neoforged/neoforge/internal/NeoForgeStatesProvider.java
  src/main/java/net/neoforged/neoforge/internal/RegistrationEvents.java
  tests/src/main/java/net/neoforged/neoforge/debug/world/ForgeChunkManagerTest.java
Labels: bug, enhancement, 1.20, breaking change

#285 [1.20.2] Reinstate chunk watch events
  patches/net/minecraft/server/level/ChunkMap.java.patch
  patches/net/minecraft/server/network/PlayerChunkSender.java.patch
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/level/ChunkWatchEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/world/ChunkWatchEventTest.java
Labels: bug, 1.20, regression

#180 [1.20.2] Fix BER render bounding boxes of various blocks
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/BeaconRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/BlockEntityRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/ChestRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/EnchantTableRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/LecternRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/SignRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/SkullBlockRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/StructureBlockRenderer.java.patch
  patches/net/minecraft/client/renderer/culling/Frustum.java.patch
  patches/net/minecraft/world/level/block/entity/SignBlockEntity.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/extensions/IBlockEntityRendererExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockEntityExtension.java
Labels: bug, 1.20, rendering
