Repository neoforged/NeoForge, pull requests merged in 2023-10, with the labels that each got.

#212 Suffix branch in version
  build.gradle
Labels: enhancement, 1.20

#207 [1.20.2] Fix duplicate sprite expansion in FaceBakery
  patches/net/minecraft/client/renderer/block/model/FaceBakery.java.patch
Labels: bug, 1.20, rendering

#206 [1.20.2] Fix FallingBlockRenderer not using RenderTypes given by the BakedModel
  patches/net/minecraft/client/renderer/entity/FallingBlockRenderer.java.patch
Labels: bug, 1.20, rendering

#217 Tweak actions for PRs
  .github/workflows/build-prs.yml
  build.gradle
Labels: 1.20, cleanup

#219 [1.20.x] Fix switched hud air graphics
  src/main/java/net/neoforged/neoforge/client/gui/overlay/ExtendedGui.java
Labels: bug, 1.20, rendering

#213 Fix shields being instantly broken
  patches/net/minecraft/world/entity/player/Player.java.patch
Labels: bug, 1.20, regression

#225 Fix switched armor points icons in HUD
  src/main/java/net/neoforged/neoforge/client/gui/overlay/ExtendedGui.java
Labels: bug, 1.20, rendering

#208 [1.20.2] Collapse TextureStitchEvent into a single post-stitch event
  patches/net/minecraft/client/renderer/texture/TextureAtlas.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/TextureAtlasStitchedEvent.java
  src/main/java/net/neoforged/neoforge/client/event/TextureStitchEvent.java
Labels: 1.20, rendering, cleanup
