Repository neoforged/NeoForge, pull requests merged in 2024-03, with the labels that each got.

#675 [1.20.4] Fix /neoforge tps command kicking player on dedicated server
  src/main/java/net/neoforged/neoforge/server/command/TPSCommand.java
Labels: bug, 1.20

#673 [1.20.1] Use LegacyInstaller v3
  build.gradle
Labels: bug, enhancement, 1.20

#676 Refactor `ContextAwareReloadListener`
  patches/net/minecraft/server/ReloadableServerResources.java.patch
  patches/net/minecraft/server/ServerAdvancementManager.java.patch
  patches/net/minecraft/world/item/crafting/RecipeManager.java.patch
  patches/net/minecraft/world/level/storage/loot/LootDataManager.java.patch
  src/main/java/net/neoforged/neoforge/common/conditions/ConditionContext.java
  src/main/java/net/neoforged/neoforge/common/conditions/ConditionalOps.java
  src/main/java/net/neoforged/neoforge/common/loot/LootModifierManager.java
  src/main/java/net/neoforged/neoforge/resource/ContextAwareReloadListener.java
Labels: 1.20, cleanup

#688 Fix bug with non Player Camera Entities causing crashes introduced by #627
  src/main/java/net/neoforged/neoforge/client/gui/overlay/ExtendedGui.java
  src/main/java/net/neoforged/neoforge/client/gui/overlay/VanillaGuiOverlay.java
Labels: regression, 1.20.4

#682 Update FML to switch to Fabric Mixin
  gradle.properties
  projects/neoforge/build.gradle
  tests/src/main/java/net/neoforged/neoforge/debug/MixinTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/mixin/InterfaceTestMixin.java
  tests/src/main/java/net/neoforged/neoforge/debug/mixin/TestMixin.java
  tests/src/main/resources/META-INF/mods.toml
  tests/src/main/resources/neotests.mixins.json
Labels: enhancement, 1.20.4

#690 Sync tags again after syncing registries
  src/main/java/net/neoforged/neoforge/network/configuration/SyncRegistries.java
Labels: bug, networking, 1.20.4

#687 add `CalculateDetachedCameraDistanceEvent`
  patches/net/minecraft/client/Camera.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/CalculateDetachedCameraDistanceEvent.java
Labels: enhancement, 1.20.4

#691 Synchronize the Fluid Registry with clients
  src/main/java/net/neoforged/neoforge/registries/NeoForgeRegistriesSetup.java
Labels: bug, 1.20.4

#694 Improve performance of entity fluid ticking
  patches/net/minecraft/world/entity/Entity.java.patch
Labels: performance, 1.20.4

#680 New Crowdin updates
  src/main/resources/assets/neoforge/lang/de_de.json
  src/main/resources/assets/neoforge/lang/ja_jp.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
Labels: l10n

#704 [24w10a] Redo FluidStack to align it with ItemStack
  src/main/java/net/neoforged/neoforge/fluids/FluidStack.java
  src/main/java/net/neoforged/neoforge/fluids/FluidUtil.java
  src/main/java/net/neoforged/neoforge/fluids/capability/templates/FluidHandlerItemStack.java
  src/main/java/net/neoforged/neoforge/fluids/capability/templates/FluidHandlerItemStackSimple.java
  src/main/java/net/neoforged/neoforge/fluids/capability/templates/FluidTank.java
  src/main/java/net/neoforged/neoforge/fluids/capability/wrappers/BucketPickupHandlerWrapper.java
  src/main/java/net/neoforged/neoforge/fluids/capability/wrappers/CauldronWrapper.java
  src/main/java/net/neoforged/neoforge/fluids/capability/wrappers/FluidBlockWrapper.java
  src/main/java/net/neoforged/neoforge/fluids/capability/wrappers/FluidBucketWrapper.java
  tests/src/main/java/net/neoforged/neoforge/debug/capabilities/VanillaHandlersTests.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/CodecsTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/fluid/MilkFluidTest.java
  tests/src/main/resources/META-INF/mods.toml
Labels: enhancement, breaking change, 1.20.5

#716 Update Testframework and setup publishing
  .github/workflows/publish-prs.yml
  testframework/build.gradle
  testframework/src/main/java/net/neoforged/testframework/DynamicTest.java
  testframework/src/main/java/net/neoforged/testframework/Test.java
  testframework/src/main/java/net/neoforged/testframework/client/AbstractTestScreen.java
  testframework/src/main/java/net/neoforged/testframework/conf/FrameworkConfiguration.java
  testframework/src/main/java/net/neoforged/testframework/impl/Commands.java
  testframework/src/main/java/net/neoforged/testframework/impl/DefaultMarkdownFileSummaryDumper.java
  testframework/src/main/java/net/neoforged/testframework/impl/GameTestRegistration.java
  testframework/src/main/java/net/neoforged/testframework/impl/SummaryDumper.java
  testframework/src/main/java/net/neoforged/testframework/impl/TestFrameworkImpl.java
  testframework/src/main/java/net/neoforged/testframework/impl/test/AbstractTest.java
  testframework/src/main/java/net/neoforged/testframework/summary/DefaultLogSummaryDumper.java
  testframework/src/main/java/net/neoforged/testframework/summary/FileSummaryDumper.java
  testframework/src/main/java/net/neoforged/testframework/summary/FormattingUtil.java
  testframework/src/main/java/net/neoforged/testframework/summary/GitHubActionsStepSummaryDumper.java
  testframework/src/main/java/net/neoforged/testframework/summary/JUnitSummaryDumper.java
  testframework/src/main/java/net/neoforged/testframework/summary/SummaryDumper.java
  testframework/src/main/java/net/neoforged/testframework/summary/TestSummary.java
  testframework/src/main/java/net/neoforged/testframework/summary/md/Alignment.java
  testframework/src/main/java/net/neoforged/testframework/summary/md/Table.java
  testframework/src/main/java/net/neoforged/testframework/summary/md/TableRow.java
  testframework/src/main/java/net/neoforged/testframework/summary/md/package-info.java
  testframework/src/main/java/net/neoforged/testframework/summary/package-info.java
  testframework/src/main/resources/META-INF/mods.toml
  testframework/src/main/resources/pack.mcmeta
  tests/src/main/java/net/neoforged/neoforge/debug/mixin/package-info.java
  tests/src/main/java/net/neoforged/neoforge/eventtest/internal/TestsMod.java
Labels: 1.20.4

#719 [1.20.4] Expand model-level AO hook to allow force-enabling AO irrespective of a block's light emission
  patches/net/minecraft/client/renderer/block/ModelBlockRenderer.java.patch
  patches/net/minecraft/client/renderer/block/model/BakedQuad.java.patch
  patches/net/minecraft/client/resources/model/MultiPartBakedModel.java.patch
  patches/net/minecraft/client/resources/model/WeightedBakedModel.java.patch
  src/main/java/net/neoforged/neoforge/client/extensions/IBakedModelExtension.java
  src/main/java/net/neoforged/neoforge/client/model/BakedModelWrapper.java
  src/main/java/net/neoforged/neoforge/common/util/TriState.java
Labels: enhancement, rendering, 1.20.4

#718 Fix non-synced data maps being nuked in singeplayer
  src/main/java/net/neoforged/neoforge/common/NeoForgeEventHandler.java
Labels: bug, data driven, 1.20.4

#722 [1.20.4] Restrict network error logging to config and play phase
  patches/net/minecraft/network/Connection.java.patch
Labels: networking, 1.20.4

#726 Update BoatDispenseItemBehavior.java.patch
  patches/net/minecraft/core/dispenser/BoatDispenseItemBehavior.java.patch
Labels: bug, 1.20.4

#717 Fix pack ordering for `PackType.SERVER_DATA`
  patches/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.java.patch
  patches/net/minecraft/server/MinecraftServer.java.patch
  patches/net/minecraft/server/packs/repository/PackRepository.java.patch
  patches/net/minecraft/server/packs/repository/ServerPacksSource.java.patch
  src/main/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/main/java/net/neoforged/neoforge/event/AddPackFindersEvent.java
  src/main/java/net/neoforged/neoforge/resource/ResourcePackLoader.java
Labels: bug, 1.20.4

#698 Fix inaccessible constructor in `AddTableLootModifier`
  src/main/java/net/neoforged/neoforge/common/loot/AddTableLootModifier.java
Labels: bug, 1.20.4

#724 Creative flight attribute
  patches/net/minecraft/client/player/LocalPlayer.java.patch
  patches/net/minecraft/server/level/ServerPlayer.java.patch
  patches/net/minecraft/server/level/ServerPlayerGameMode.java.patch
  patches/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
  patches/net/minecraft/world/entity/player/Abilities.java.patch
  patches/net/minecraft/world/entity/player/Player.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/extensions/IPlayerExtension.java
  src/main/resources/assets/neoforge/lang/en_us.json
  tests/src/main/java/net/neoforged/neoforge/oldtest/item/MayFlyAttributeTest.java
  tests/src/main/resources/META-INF/mods.toml
Labels: enhancement, 1.20

#727 Add a contribution workflow that spells out the gradle tasks needed
  docs/CONTRIBUTING.md
Labels: documentation

#732 Minimize allocations and avoid rebuilding weighted list when retrieving potential spawns
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/level/LevelEvent.java
Labels: performance, 1.20.4

#731 [1.20.1] Avoid lambda use in `RegistryObject#get`
  src/main/java/net/minecraftforge/registries/RegistryObject.java
Labels: 1.20, performance

#712 Make Data Attachment copy methods public API
  patches/net/minecraft/core/cauldron/CauldronInteraction.java.patch
  patches/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
  patches/net/minecraft/world/inventory/EnchantmentMenu.java.patch
  patches/net/minecraft/world/item/CompassItem.java.patch
  patches/net/minecraft/world/item/FoodOnAStickItem.java.patch
  patches/net/minecraft/world/item/ItemStack.java.patch
  patches/net/minecraft/world/item/crafting/BookCloningRecipe.java.patch
  patches/net/minecraft/world/item/crafting/ShulkerBoxColoring.java.patch
  patches/net/minecraft/world/item/crafting/SmithingTransformRecipe.java.patch
  patches/net/minecraft/world/level/chunk/LevelChunk.java.patch
  src/main/java/net/neoforged/neoforge/attachment/AttachmentInternals.java
  src/main/java/net/neoforged/neoforge/attachment/AttachmentUtils.java
Labels: enhancement, 1.20.4
