Repository neoforged/NeoForge, pull requests merged in 2024-02, with the labels that each got.

#600 Fix data map sync crash on dedicated servers
  projects/neoforge/build.gradle
Labels: bug, 1.20

#603 Prevent helmet overlay rendering when spyglass is being used
  src/main/java/net/neoforged/neoforge/client/gui/overlay/ExtendedGui.java
Labels: bug, 1.20, rendering

#577 Remove `alwaysSetupTerrainOffThread`
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeConfig.java
Labels: 1.20, cleanup

#607 fixed inventoryTick patch
  patches/net/minecraft/world/entity/player/Inventory.java.patch
Labels: bug, 1.20

#586 Add `toStack` helper methods to `DeferredItem` and `DeferredBlock`
  src/main/java/net/neoforged/neoforge/registries/DeferredBlock.java
  src/main/java/net/neoforged/neoforge/registries/DeferredItem.java
Labels: enhancement, 1.20

#594 Add a data map for vibration frequencies
  patches/net/minecraft/world/level/gameevent/vibrations/VibrationSystem.java.patch
  src/generated/resources/data/neoforge/data_maps/game_event/vibration_frequencies.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeDataMapsProvider.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/NeoForgeDataMaps.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/VibrationFrequency.java
Labels: enhancement, 1.20, data driven

#615 Fallback to magic damage on clientside when connecting to vanilla
  patches/net/minecraft/world/effect/PoisonMobEffect.java.patch
  src/main/resources/META-INF/accesstransformer.cfg
Labels: bug, 1.20

#617 [1.20.1] Fallback to magic damage on clientside when connecting to vanilla
  patches/minecraft/net/minecraft/world/effect/MobEffect.java.patch
  src/main/resources/META-INF/accesstransformer.cfg
Labels: bug, 1.20, backport

#599 send full dataslot value on neo<->neo connections
  patches/net/minecraft/server/level/ServerPlayer.java.patch
  src/main/java/net/neoforged/neoforge/network/NetworkInitialization.java
  src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java
  src/main/java/net/neoforged/neoforge/network/payload/AdvancedContainerSetDataPayload.java
Labels: enhancement, 1.20

#611 Add a data map for parrot imitations
  patches/net/minecraft/world/entity/animal/Parrot.java.patch
  src/generated/resources/data/neoforge/data_maps/entity_type/parrot_imitations.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeDataMapsProvider.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/NeoForgeDataMaps.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/ParrotImitation.java
Labels: enhancement, 1.20, data driven

#590 Furnace fuels data map
  patches/net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity.java.patch
  src/generated/resources/data/neoforge/data_maps/item/furnace_fuels.json
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeEventHandler.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeDataMapsProvider.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/event/furnace/FurnaceFuelBurnTimeEvent.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/FurnaceFuel.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/NeoForgeDataMaps.java
Labels: enhancement, 1.20, data driven

#622 Proto Chunk Attachments
  patches/net/minecraft/world/level/chunk/ChunkAccess.java.patch
  patches/net/minecraft/world/level/chunk/ImposterProtoChunk.java.patch
  patches/net/minecraft/world/level/chunk/LevelChunk.java.patch
  patches/net/minecraft/world/level/chunk/storage/ChunkSerializer.java.patch
  src/main/java/net/neoforged/neoforge/attachment/AttachmentInternals.java
  src/main/java/net/neoforged/neoforge/attachment/AttachmentType.java
Labels: enhancement, 1.20

#637 [1.20.1] Move firing of BuildCreativeModeTabContentsEvent to ForgeHooks
  patches/minecraft/net/minecraft/world/item/CreativeModeTab.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/BuildCreativeModeTabContentsEvent.java
Labels: enhancement, 1.20, breaking change, backport

#619 [Hot/Cold Fix] Fix the implementation of the "minecraft:register" and "minecraft:unregister" payloads
  patches/net/minecraft/client/multiplayer/ClientConfigurationPacketListenerImpl.java.patch
  patches/net/minecraft/client/multiplayer/ClientPacketListener.java.patch
  patches/net/minecraft/client/multiplayer/CommonListenerCookie.java.patch
  patches/net/minecraft/server/network/CommonListenerCookie.java.patch
  patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch
  patches/net/minecraft/server/network/ServerConfigurationPacketListenerImpl.java.patch
  patches/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeEventHandler.java
  src/main/java/net/neoforged/neoforge/common/TierSortingRegistry.java
  src/main/java/net/neoforged/neoforge/common/extensions/IClientCommonPacketListenerExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IServerCommonPacketListenerExtension.java
  src/main/java/net/neoforged/neoforge/network/ConfigurationInitialization.java
  src/main/java/net/neoforged/neoforge/network/NetworkInitialization.java
  src/main/java/net/neoforged/neoforge/network/connection/ConnectionPhase.java
  src/main/java/net/neoforged/neoforge/network/connection/ConnectionType.java
  src/main/java/net/neoforged/neoforge/network/filters/GenericPacketSplitter.java
  src/main/java/net/neoforged/neoforge/network/filters/NetworkFilters.java
  src/main/java/net/neoforged/neoforge/network/filters/VanillaConnectionNetworkFilter.java
  src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java
  src/main/java/net/neoforged/neoforge/network/handling/IReplyHandler.java
  src/main/java/net/neoforged/neoforge/network/payload/DinnerboneProtocolUtils.java
  src/main/java/net/neoforged/neoforge/network/payload/MinecraftRegisterPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/MinecraftUnregisterPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/ModdedNetworkPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/ModdedNetworkQueryPayload.java
  src/main/java/net/neoforged/neoforge/network/registration/NetworkPayloadSetup.java
  src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java
  src/main/java/net/neoforged/neoforge/server/command/TextComponentHelper.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: bug, 1.20, blocks stable

#644 Fix regressions in difference and intersection ingredients
  src/main/java/net/neoforged/neoforge/common/crafting/ChildBasedIngredient.java
  src/main/java/net/neoforged/neoforge/common/crafting/CompoundIngredient.java
  src/main/java/net/neoforged/neoforge/common/crafting/DifferenceIngredient.java
  src/main/java/net/neoforged/neoforge/common/crafting/IntersectionIngredient.java
Labels: 1.20, regression

#652 Fix writing fluid stack to nbt not copying the stack's nbt and instead passing a direct reference
  src/main/java/net/neoforged/neoforge/fluids/FluidStack.java
Labels: bug, 1.20

#638 Add support to NBTIngredient for handling attachments
  src/main/java/net/neoforged/neoforge/common/crafting/NBTIngredient.java
  tests/src/generated/resources/data/neotests_partial_attachment_ingredient/advancements/recipes/misc/partial_attachments.json
  tests/src/generated/resources/data/neotests_partial_attachment_ingredient/recipes/partial_attachments.json
  tests/src/generated/resources/data/neotests_partial_nbt_attachment_ingredient/advancements/recipes/misc/partial_nbt_and_attachments.json
  tests/src/generated/resources/data/neotests_partial_nbt_attachment_ingredient/recipes/partial_nbt_and_attachments.json
  tests/src/generated/resources/data/neotests_strict_attachment_ingredient/advancements/recipes/misc/strict_attachments.json
  tests/src/generated/resources/data/neotests_strict_attachment_ingredient/recipes/strict_attachments.json
  tests/src/generated/resources/data/neotests_strict_nbt_attachment_ingredient/advancements/recipes/misc/strict_attachments.json
  tests/src/generated/resources/data/neotests_strict_nbt_attachment_ingredient/recipes/strict_attachments.json
  tests/src/main/java/net/neoforged/neoforge/debug/crafting/IngredientTests.java
Labels: enhancement, 1.20

#620 Fix `ContainerScreenEvent$Render$Background` running after renderables being drawn.
  patches/net/minecraft/client/gui/screens/Screen.java.patch
  patches/net/minecraft/client/gui/screens/inventory/AbstractContainerScreen.java.patch
Labels: bug, 1.20

#653 Use Collections.emptyMap() for empty ModelData instances
  src/main/java/net/neoforged/neoforge/client/model/data/ModelData.java
Labels: enhancement, 1.20, rendering, performance

#642 Create `AddSectionGeometryEvent`
  patches/net/minecraft/client/renderer/chunk/RenderRegionCache.java.patch
  patches/net/minecraft/client/renderer/chunk/SectionRenderDispatcher.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/AddSectionGeometryEvent.java
  src/main/java/net/neoforged/neoforge/client/model/lighting/LightPipelineAwareModelBlockRenderer.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/ClientEventTests.java
Labels: enhancement, 1.20, rendering

#654 Add support for custom entity predicates and make some advancements support modded types
  patches/net/minecraft/advancements/critereon/EntityPredicate.java.patch
  patches/net/minecraft/advancements/critereon/ItemPredicate.java.patch
  src/generated/resources/data/minecraft/advancements/husbandry/wax_off.json
  src/generated/resources/data/minecraft/advancements/nether/distract_piglin.json
  src/generated/resources/reports/registry_order.json
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/advancements/critereon/ICustomEntityPredicate.java
  src/main/java/net/neoforged/neoforge/common/advancements/critereon/PiglinCurrencyItemPredicate.java
  src/main/java/net/neoforged/neoforge/common/advancements/critereon/PiglinNeutralArmorEntityPredicate.java
  src/main/java/net/neoforged/neoforge/common/advancements/critereon/ToolActionItemPredicate.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeAdvancementProvider.java
  src/main/java/net/neoforged/neoforge/registries/NeoForgeRegistries.java
  src/main/java/net/neoforged/neoforge/registries/NeoForgeRegistriesSetup.java
Labels: enhancement, 1.20

#591 [1.20.4] Add `onDestroyedByPushReaction` hook
  patches/net/minecraft/world/level/block/piston/PistonBaseBlock.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockStateExtension.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/OnDestroyedByPushReactionTests.java
Labels: enhancement, 1.20

#643 New Crowdin updates
  src/main/resources/assets/neoforge/lang/en_gb.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/zh_hk.json
Labels: l10n

#613 Prevent registering synced data maps for non-synced datapack registries
  src/main/java/net/neoforged/neoforge/common/NeoForgeEventHandler.java
  src/main/java/net/neoforged/neoforge/registries/DataPackRegistriesHooks.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/RegisterDataMapTypesEvent.java
Labels: bug, 1.20

#658 Load en_us languages on dedicated server
  src/main/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/main/java/net/neoforged/neoforge/server/LanguageHook.java
  src/main/java/net/neoforged/neoforge/server/ServerLifecycleHooks.java
  src/main/java/net/neoforged/neoforge/server/loading/ServerModLoader.java
Labels: bug, 1.20

#627 Remove the "`gui.shouldDrawSurvivalElements()`" condition in `MOUNT_HEALTH`
  src/main/java/net/neoforged/neoforge/client/gui/overlay/VanillaGuiOverlay.java
Labels: bug, 1.20, rendering

#618 Optional data attachment method
  patches/net/minecraft/world/level/chunk/ChunkAccess.java.patch
  src/main/java/net/neoforged/neoforge/attachment/AttachmentHolder.java
  src/main/java/net/neoforged/neoforge/attachment/IAttachmentHolder.java
  tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java
Labels: enhancement, 1.20

#662 New Crowdin updates
  src/main/resources/assets/neoforge/lang/ru_ru.json
Labels: l10n
