Repository neoforged/NeoForge, pull requests merged in 2024-06, with the labels that each got.

#1047 Rename EffectCures#getActions to EffectCures#getAllCures
  src/main/java/net/neoforged/neoforge/common/EffectCure.java
Labels: bug, breaking change, 1.20.6

#999 Make heart types an extensible enum and add an event to modify them
  patches/net/minecraft/client/gui/Gui.java.patch
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/entity/player/PlayerHeartTypeEvent.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, 1.20.6

#1046 Add new constructor to SwordItem to allow setting Tool data component
  patches/net/minecraft/world/item/SwordItem.java.patch
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, 1.20.6

#1054 Update FML to get Java Core Mods and early-loading config support
  gradle.properties
  src/main/java/net/neoforged/neoforge/junit/JUnitMain.java
Labels: enhancement, 1.20.6

#1043 [1.20.6] Use stack hash strategy for mutable map in creative tab event
  src/main/java/net/neoforged/neoforge/common/util/MutableHashedLinkedMap.java
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/CreativeTabOrderTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/CreativeModeTabTest.java
  tests/src/main/resources/META-INF/neoforge.mods.toml
Labels: bug, 1.20.6

#1017 Add ExplosionEvent.Knockback event
  patches/net/minecraft/world/level/Explosion.java.patch
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/level/ExplosionKnockbackEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/EntityEventTests.java
Labels: enhancement, 1.20.6

#1037 [No CI] Add a gametest for startup configs
  tests/build.gradle
  tests/src/junit/java/net/neoforged/neoforge/unittest/StartupConfigTest.java
  tests/src/junit/resources/META-INF/neoforge.mods.toml
  tests/src/main/resources/META-INF/neoforge.mods.toml
Labels: enhancement, 1.20.6

#1024 Remove IFluidBlock and FluidBlockWrapper
  src/main/java/net/neoforged/neoforge/fluids/FluidUtil.java
  src/main/java/net/neoforged/neoforge/fluids/IFluidBlock.java
  src/main/java/net/neoforged/neoforge/fluids/capability/wrappers/BlockWrapper.java
  src/main/java/net/neoforged/neoforge/fluids/capability/wrappers/FluidBlockWrapper.java
Labels: cleanup, breaking change, last call, 1.20.6

#1034 Propagate Block#playerWillDestroy result to Block#playerDestroy
  patches/net/minecraft/client/multiplayer/MultiPlayerGameMode.java.patch
  patches/net/minecraft/server/level/ServerPlayerGameMode.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/BlockTests.java
Labels: bug, breaking change, 1.20.6

#996 Update IShearable to support Bogged and perform some fixes and cleanup
  patches/net/minecraft/world/entity/Shearable.java.patch
  patches/net/minecraft/world/entity/animal/MushroomCow.java.patch
  patches/net/minecraft/world/entity/animal/Sheep.java.patch
  patches/net/minecraft/world/entity/animal/SnowGolem.java.patch
  patches/net/minecraft/world/entity/monster/Bogged.java.patch
  patches/net/minecraft/world/item/ShearsItem.java.patch
  src/main/java/net/neoforged/neoforge/common/IShearable.java
Labels: bug, cleanup, breaking change, 1.20.6

#1036 [1.20.4] Improved ModMismatchDisconnectedScreen and clientside handling of channel mismatches in general
  src/main/java/net/neoforged/neoforge/client/gui/ModMismatchDisconnectedScreen.java
  src/main/java/net/neoforged/neoforge/network/negotiation/NetworkComponentNegotiator.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, backport, 1.20.4

#989 [1.20.4] BlockTagIngredient Backport
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/crafting/BlockTagIngredient.java
  tests/src/generated/resources/data/neotests_block_tag_ingredient/advancements/recipes/misc/block_tag.json
  tests/src/generated/resources/data/neotests_block_tag_ingredient/recipes/block_tag.json
  tests/src/main/java/net/neoforged/neoforge/debug/crafting/IngredientTests.java
Labels: enhancement, backport, 1.20.4

#1061 [1.20.6] Add `BlockDropsEvent`
  patches/net/minecraft/server/level/ServerPlayerGameMode.java.patch
  patches/net/minecraft/world/level/block/Block.java.patch
  patches/net/minecraft/world/level/block/state/BlockBehaviour.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockStateExtension.java
  src/main/java/net/neoforged/neoforge/event/level/BlockDropsEvent.java
  src/main/java/net/neoforged/neoforge/event/level/BlockEvent.java
  testframework/src/main/java/net/neoforged/testframework/gametest/ExtendedGameTestHelper.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/BlockEventTests.java
Labels: enhancement, breaking change, 1.20.6

#1041 Fix `EffectCure` syncing by introducing connection aware `StreamCodec`
  patches/net/minecraft/client/multiplayer/ClientConfigurationPacketListenerImpl.java.patch
  patches/net/minecraft/network/RegistryFriendlyByteBuf.java.patch
  patches/net/minecraft/server/network/ServerConfigurationPacketListenerImpl.java.patch
  patches/net/minecraft/server/players/PlayerList.java.patch
  patches/net/minecraft/world/effect/MobEffectInstance.java.patch
  src/main/java/net/neoforged/neoforge/common/util/FriendlyByteBufUtil.java
  src/main/java/net/neoforged/neoforge/network/codec/NeoForgeStreamCodecs.java
  src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/EntityDataSerializerTest.java
Labels: bug, last call, 1.20.6

#1090 Fix crash when setting zero experience in BlockDropsEvent
  src/main/java/net/neoforged/neoforge/event/level/BlockDropsEvent.java
Labels: bug, 1.20.6

#1089 [port/1.21] Fix issues relating to gameplay-enchantment support
  patches/net/minecraft/advancements/critereon/ItemEnchantmentsPredicate.java.patch
  patches/net/minecraft/core/Holder.java.patch
  patches/net/minecraft/world/item/ArrowItem.java.patch
  patches/net/minecraft/world/item/ItemStack.java.patch
  patches/net/minecraft/world/item/ProjectileWeaponItem.java.patch
  patches/net/minecraft/world/item/enchantment/Enchantment.java.patch
  patches/net/minecraft/world/item/enchantment/EnchantmentHelper.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/extensions/IHolderExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/enchanting/GetEnchantmentLevelEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/enchantment/EnchantmentLevelTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/loot/GlobalLootModifiersTest.java
Labels: bug, 1.21

#1096 [1.21] Add back Neo early config task registration
  patches/net/minecraft/server/network/ServerConfigurationPacketListenerImpl.java.patch
Labels: bug, regression, blocks stable, 1.21, networking

#1097 [1.21] Fix per-face ExtraFaceData not getting saved in datagen
  src/main/java/net/neoforged/neoforge/client/model/generators/ModelBuilder.java
Labels: bug, rendering, regression, blocks stable, 1.21, data driven

#1069 [1.21] Remove Legacy `BiomeManager`
  patches/net/minecraft/data/worldgen/biome/OverworldBiomes.java.patch
  src/main/java/net/neoforged/neoforge/common/BiomeManager.java
Labels: cleanup, breaking change, 1.21

#1095 Add Mangrove Swamp and Bamboo Jungle to Dense Overworld Vegetation tag
  src/generated/resources/data/c/tags/worldgen/biome/is_dense_vegetation/overworld.json
  src/generated/resources/pack.mcmeta
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBiomeTagsProvider.java
Labels: bug, 1.21

#1018 New Crowdin updates
  src/main/resources/assets/neoforge/lang/da_dk.json
  src/main/resources/assets/neoforge/lang/de_de.json
  src/main/resources/assets/neoforge/lang/en_gb.json
  src/main/resources/assets/neoforge/lang/es_es.json
  src/main/resources/assets/neoforge/lang/et_ee.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/hu_hu.json
  src/main/resources/assets/neoforge/lang/it_it.json
  src/main/resources/assets/neoforge/lang/ja_jp.json
  src/main/resources/assets/neoforge/lang/ko_kr.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/ro_ro.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/sk_sk.json
  src/main/resources/assets/neoforge/lang/tr_tr.json
  src/main/resources/assets/neoforge/lang/tt_ru.json
  src/main/resources/assets/neoforge/lang/uk_ua.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_hk.json
Labels: l10n

#1102 Restore 2 SwordItem constructor patch (#1046 and #1010)
  patches/net/minecraft/world/item/SwordItem.java.patch
Labels: regression, 1.21

#1104 Fix tags command error messages
  src/main/java/net/neoforged/neoforge/server/command/TagsCommand.java
Labels: bug, 1.21

#1103 Fix withSearchBar not setting the background texture for the creative menu
  patches/net/minecraft/world/item/CreativeModeTab.java.patch
Labels: bug, regression, 1.21

#1066 Add Mangrove Swamp and Bamboo Jungle to Dense Overworld Vegetation tag
  src/generated/resources/data/c/tags/worldgen/biome/is_dense_vegetation/overworld.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBiomeTagsProvider.java
Labels: bug, backport, 1.20.6

#1108 Allow querying and baking top-level models from ModelBaker
  patches/net/minecraft/client/resources/model/ModelBakery.java.patch
  src/main/java/net/neoforged/neoforge/client/extensions/IModelBakerExtension.java
Labels: enhancement, rendering, 1.21

#1016 [1.21] Move extensible enums to data-driven enum extension
  gradle.properties
  patches/com/mojang/blaze3d/vertex/VertexFormatElement.java.patch
  patches/net/minecraft/client/RecipeBookCategories.java.patch
  patches/net/minecraft/client/gui/Gui.java.patch
  patches/net/minecraft/client/model/HumanoidModel.java.patch
  patches/net/minecraft/world/damagesource/DamageEffects.java.patch
  patches/net/minecraft/world/damagesource/DamageScaling.java.patch
  patches/net/minecraft/world/damagesource/DeathMessageType.java.patch
  patches/net/minecraft/world/entity/MobCategory.java.patch
  patches/net/minecraft/world/entity/raid/Raid.java.patch
  patches/net/minecraft/world/inventory/RecipeBookType.java.patch
  patches/net/minecraft/world/item/ItemDisplayContext.java.patch
  patches/net/minecraft/world/item/Rarity.java.patch
  patches/net/minecraft/world/item/component/FireworkExplosion.java.patch
  patches/net/minecraft/world/level/biome/BiomeSpecialEffects.java.patch
  projects/neoforge/build.gradle
  src/main/java/net/neoforged/neoforge/common/IExtensibleEnum.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/registries/NeoForgeRegistries.java
  src/main/java/net/neoforged/neoforge/registries/NeoForgeRegistriesSetup.java
  src/main/resources/META-INF/accesstransformer.cfg
  tests/src/generated/resources/data/neotests_dmg_type_tests/damage_type/test.json
  tests/src/main/java/net/neoforged/neoforge/debug/client/RenderTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/damagesource/DamageTypeTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/item/ItemTests.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/client/model/CustomItemDisplayContextTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/entity/CreateEntityClassificationTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/entity/player/ItemUseAnimationTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/recipebook/RecipeBookExtensionClientHelper.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/recipebook/RecipeBookExtensionTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/world/RaidEnumTest.java
  tests/src/main/resources/META-INF/enumextensions.json
  tests/src/main/resources/META-INF/neoforge.mods.toml
Labels: enhancement, breaking change, 1.21

#1030 Tag cleanup and additions for 1.21
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/block/concretes.json
  src/generated/resources/data/c/tags/block/glass_blocks/cheap.json
  src/generated/resources/data/c/tags/block/glazed_terracottas.json
  src/generated/resources/data/c/tags/item/concrete_powders.json
  src/generated/resources/data/c/tags/item/concretes.json
  src/generated/resources/data/c/tags/item/glass_blocks/cheap.json
  src/generated/resources/data/c/tags/item/glazed_terracottas.json
  src/generated/resources/data/c/tags/item/music_discs.json
  src/generated/resources/data/c/tags/item/raw_blocks.json
  src/generated/resources/data/c/tags/item/raw_blocks/copper.json
  src/generated/resources/data/c/tags/item/raw_blocks/gold.json
  src/generated/resources/data/c/tags/item/raw_blocks/iron.json
  src/generated/resources/data/c/tags/item/shulker_boxes.json
  src/generated/resources/data/c/tags/item/tools.json
  src/generated/resources/data/c/tags/item/tools/bow.json
  src/generated/resources/data/c/tags/item/tools/bows.json
  src/generated/resources/data/c/tags/item/tools/brush.json
  src/generated/resources/data/c/tags/item/tools/brushes.json
  src/generated/resources/data/c/tags/item/tools/crossbow.json
  src/generated/resources/data/c/tags/item/tools/fishing_rod.json
  src/generated/resources/data/c/tags/item/tools/shear.json
  src/generated/resources/data/c/tags/item/tools/shears.json
  src/generated/resources/data/c/tags/item/tools/shield.json
  src/generated/resources/data/c/tags/item/tools/spear.json
  src/generated/resources/data/c/tags/item/tools/spears.json
  src/generated/resources/data/c/tags/worldgen/biome/is_sparse_vegetation/overworld.json
  src/main/java/net/neoforged/neoforge/common/TagConventionLogWarning.java
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBiomeTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: enhancement, cleanup, breaking change, 1.21

#1121 Fix enchantment attribute modifiers not being applied
  patches/net/minecraft/world/item/ItemStack.java.patch
Labels: bug, 1.21

#1116 Adds an extension method to items (adjustAttributeModifiers) to allow modifying the exposed attributes
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/item/MayFlyAttributeTest.java
Labels: enhancement, breaking change, 1.21

#1126 [1.21] Add back missed patch for RegistryFriendlyByteBuf connection type awareness
  patches/net/minecraft/server/network/ServerConfigurationPacketListenerImpl.java.patch
Labels: bug, regression, blocks stable, 1.21, networking

#842 [21.0] RenderType changes
  src/main/java/net/neoforged/neoforge/client/NeoForgeRenderTypes.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: 1.21

#1132 [1.21] Fix armor rendering using the wrong model
  patches/net/minecraft/client/renderer/entity/layers/HumanoidArmorLayer.java.patch
Labels: bug, rendering, regression, 1.21

#1124 [1.21] Fixed ProjectileWeaponItem#customArrow patch
  patches/net/minecraft/world/entity/monster/AbstractSkeleton.java.patch
  patches/net/minecraft/world/entity/monster/Illusioner.java.patch
  patches/net/minecraft/world/item/ProjectileWeaponItem.java.patch
Labels: enhancement, breaking change, 1.21

#1114 [1.21] Fix PlayerRespawnPositionEvent position copying logic
  patches/net/minecraft/server/players/PlayerList.java.patch
  src/main/java/net/neoforged/neoforge/event/entity/player/PlayerRespawnPositionEvent.java
Labels: bug, breaking change, 1.21

#1140 Fix regression with keyboard modifiers
  patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch
Labels: bug, regression, 1.21

#1139 [1.21] Fix angles set in ViewportEvent.ComputeCameraAngles not taking effect
  patches/net/minecraft/client/Camera.java.patch
  patches/net/minecraft/client/renderer/GameRenderer.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/ViewportEvent.java
Labels: bug, rendering, regression, breaking change, 1.21

#1118 [1.21] Fixes MC-273464 by providing the correct partial tick
  patches/net/minecraft/client/renderer/GameRenderer.java.patch
Labels: rendering, 1.21, vanilla bug

#969 Add hook for projectile weapon to define default ammo
  patches/net/minecraft/world/entity/player/Player.java.patch
  patches/net/minecraft/world/item/ProjectileWeaponItem.java.patch
Labels: bug, enhancement, 1.21

#1149 Make RecipeWrapper implement RecipeInput
  src/main/java/net/neoforged/neoforge/items/wrapper/RecipeWrapper.java
Labels: cleanup, breaking change, 1.21

#1125 [1.21] Update `ItemAttributeModifierEvent` to be based on `ItemAttributeModifiers` and update new vanilla attribute uses against the event
  patches/net/minecraft/advancements/critereon/ItemAttributeModifiersPredicate.java.patch
  patches/net/minecraft/world/entity/Mob.java.patch
  patches/net/minecraft/world/item/Item.java.patch
  patches/net/minecraft/world/item/ItemStack.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
  src/main/java/net/neoforged/neoforge/event/ItemAttributeModifierEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/item/ItemEventTests.java
Labels: bug, enhancement, breaking change, 1.21

#1137 [1.21] Cleanup access transformers
  patches/net/minecraft/client/gui/Gui.java.patch
  patches/net/minecraft/client/renderer/blockentity/PistonHeadRenderer.java.patch
  patches/net/minecraft/core/Holder.java.patch
  patches/net/minecraft/core/HolderSet.java.patch
  patches/net/minecraft/world/level/block/BushBlock.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeEventHandler.java
  src/main/java/net/neoforged/neoforge/server/command/ConfigCommand.java
  src/main/resources/META-INF/accesstransformer.cfg
  testframework/src/main/java/net/neoforged/testframework/gametest/GameTestPlayer.java
Labels: bug, cleanup, regression, breaking change, 1.21

#1130 [1.21] Add missing alias resolve in MappedRegistry#getHolder() and properly handle null name in MappedRegistry#get()
  patches/net/minecraft/core/MappedRegistry.java.patch
Labels: bug, regression, blocks stable, 1.21

#1157 [1.21] Add missing tool, block entity, and breaker context to getExpDrop
  patches/net/minecraft/world/level/block/DropExperienceBlock.java.patch
  patches/net/minecraft/world/level/block/RedStoneOreBlock.java.patch
  patches/net/minecraft/world/level/block/SculkCatalystBlock.java.patch
  patches/net/minecraft/world/level/block/SculkSensorBlock.java.patch
  patches/net/minecraft/world/level/block/SculkShriekerBlock.java.patch
  patches/net/minecraft/world/level/block/SpawnerBlock.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockStateExtension.java
  src/main/java/net/neoforged/neoforge/event/level/BlockDropsEvent.java
Labels: enhancement, breaking change, 1.21

#1151 [1.21] Fix duplicate registration error for empty loot table
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
Labels: bug, 1.21, data driven

#792 Damage Pipeline Update
  patches/net/minecraft/client/player/LocalPlayer.java.patch
  patches/net/minecraft/client/player/RemotePlayer.java.patch
  patches/net/minecraft/world/entity/Entity.java.patch
  patches/net/minecraft/world/entity/LivingEntity.java.patch
  patches/net/minecraft/world/entity/player/Player.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/damagesource/DamageContainer.java
  src/main/java/net/neoforged/neoforge/common/damagesource/IReductionFunction.java
  src/main/java/net/neoforged/neoforge/common/extensions/ILivingEntityExtension.java
  src/main/java/net/neoforged/neoforge/event/entity/EntityInvulnerabilityCheckEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/living/ArmorHurtEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/living/LivingAttackEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/living/LivingDamageEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/living/LivingHurtEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/living/LivingIncomingDamageEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/living/LivingShieldBlockEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/living/ShieldBlockEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/data/DataMapTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/EntityEventTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/living/LivingEntityEventTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/player/PlayerEventTests.java
Labels: enhancement, breaking change, 1.21, last call

#1164 [1.21] Fix transforms for modded ItemDisplayContexts being ignored
  patches/net/minecraft/client/renderer/block/model/ItemTransforms.java.patch
  tests/src/main/java/net/neoforged/neoforge/oldtest/client/model/CustomItemDisplayContextTest.java
Labels: bug, rendering, regression, 1.21

#1175 Remove two LivingEntity stat patches that did nothing
  patches/net/minecraft/world/entity/LivingEntity.java.patch
Labels: cleanup, 1.21

#1171 Remove separate eye height field from EntityEvent.Size
  patches/net/minecraft/world/entity/Entity.java.patch
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/entity/EntityEvent.java
Labels: bug, regression, 1.21

#1136 Add a `can_villager_compost` field to the compostables datamap
  patches/net/minecraft/world/entity/ai/behavior/WorkAtComposter.java.patch
  src/generated/resources/data/neoforge/data_maps/item/compostables.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeDataMapsProvider.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/Compostable.java
Labels: enhancement, 1.21, data driven

#1178 Bump NeoGradle to fix the patch baking issue
  settings.gradle
Labels: bug, 1.21, ci/build

#1142 Fix not being able to set keybindings when using keyboard navigation
  patches/net/minecraft/client/KeyboardHandler.java.patch
Labels: bug, 1.21

#1194 Remove remaining invalid ATs
  .github/workflows/build-prs.yml
  .github/workflows/check-local-changes.yml
  gradle.properties
  projects/neoforge/build.gradle
  src/main/resources/META-INF/accesstransformer.cfg
Labels: bug, 1.21

#1198 [1.21] Add holder helpers to LevelReader and HolderLookupProvider
  patches/net/minecraft/core/HolderLookup.java.patch
  patches/net/minecraft/world/level/LevelReader.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IHolderLookupProviderExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/ILevelReaderExtension.java
Labels: enhancement, 1.21
