Repository neoforged/NeoForge, pull requests merged in 2024-04, with the labels that each got.

#746 Fix ContextAwareReloadListener for listeners added through the event
  src/main/java/net/neoforged/neoforge/event/AddReloadListenerEvent.java
Labels: bug

#760 Add capabilities methods to `ExtendedGameTestHelper`
  testframework/src/main/java/net/neoforged/testframework/gametest/ExtendedGameTestHelper.java
Labels: enhancement, 1.20.4

#771 [24w13a] Fix FluidTank not serializing fluids correctly
  src/main/java/net/neoforged/neoforge/fluids/capability/templates/FluidTank.java
Labels: bug, 1.20.5

#699 Remove `CommonHooks#getBurnTime` and move contents to `ItemStack#getBurnTime`
  patches/net/minecraft/world/inventory/AbstractFurnaceMenu.java.patch
  patches/net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
Labels: cleanup, 1.20.4

#778 Fix potential breaking change with fuel values of -1
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
Labels: bug, 1.20.4

#776 Add Leaves method to ModelProvider.java
  src/main/java/net/minecraftforge/client/model/generators/ModelProvider.java
Labels: enhancement, 1.20

#779 Add Leaves method to ModelProvider.java
  src/main/java/net/neoforged/neoforge/client/model/generators/ModelProvider.java
Labels: enhancement, 1.20.4

#784 Fixes ModMismatchEvent crash
  src/main/java/net/neoforged/neoforge/event/ModMismatchEvent.java
Labels: bug, 1.20.4

#765 [1.20.4] Improve detection of dynamic block light sources during light updates in chunk generation and loading
  patches/net/minecraft/world/level/chunk/ChunkAccess.java.patch
  patches/net/minecraft/world/level/chunk/ImposterProtoChunk.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockStateExtension.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/BlockPropertyTests.java
Labels: 1.20.4

#772 Optimize ModelData when used with very few properties
  src/main/java/net/neoforged/neoforge/client/model/data/ModelData.java
Labels: enhancement, performance, 1.20.4

#786 Adds a dump registry command
  src/main/java/net/neoforged/neoforge/server/command/CommandUtils.java
  src/main/java/net/neoforged/neoforge/server/command/DumpCommand.java
  src/main/java/net/neoforged/neoforge/server/command/NeoForgeCommand.java
  src/main/java/net/neoforged/neoforge/server/command/TagsCommand.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, 1.20.4

#754 Add the custom payload id to exceptions thrown by custom payload serializers/deserializers
  patches/net/minecraft/network/protocol/common/ClientboundCustomPayloadPacket.java.patch
  patches/net/minecraft/network/protocol/common/ServerboundCustomPayloadPacket.java.patch
Labels: enhancement, networking, 1.20.4

#728 Allow control over the rendering of slot highlights
  patches/net/minecraft/client/gui/screens/inventory/AbstractContainerScreen.java.patch
Labels: enhancement, rendering, 1.20.4

#729 Fix param naming of AbstractContainerScreen#renderSlotContents
  patches/net/minecraft/client/gui/screens/inventory/AbstractContainerScreen.java.patch
Labels: enhancement, rendering, 1.20.4

#762 Add the for modders to use their own extension of `GameTestHelper`
  testframework/src/main/java/net/neoforged/testframework/DynamicTest.java
  testframework/src/main/java/net/neoforged/testframework/impl/FrameworkCollectors.java
  testframework/src/main/java/net/neoforged/testframework/impl/GameTestHelperFactory.java
  testframework/src/main/java/net/neoforged/testframework/impl/test/AbstractTest.java
  testframework/src/main/java/net/neoforged/testframework/impl/test/MethodBasedGameTestTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/CustomHelperTests.java
Labels: enhancement, 1.20.4

#817 [1.20.5] Patch in `MutableDataComponentHolder` interface
  patches/net/minecraft/core/component/DataComponentHolder.java.patch
  patches/net/minecraft/world/item/ItemStack.java.patch
  src/main/java/net/neoforged/neoforge/common/MutableDataComponentHolder.java
  src/main/java/net/neoforged/neoforge/common/extensions/IDataComponentHolderExtension.java
  src/main/java/net/neoforged/neoforge/fluids/FluidStack.java
  src/main/java/net/neoforged/neoforge/fluids/capability/templates/FluidHandlerItemStack.java
  src/main/java/net/neoforged/neoforge/fluids/capability/templates/FluidHandlerItemStackSimple.java
  tests/src/main/java/net/neoforged/neoforge/debug/capabilities/FluidTemplatesTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/item/ItemComponentTests.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/item/CustomFluidContainerTest.java
Labels: enhancement, 1.20.5

#774 Update to simpler mod loading from latest FML
  gradle.properties
  patches/net/minecraft/client/Minecraft.java.patch
  patches/net/minecraft/client/gui/screens/MenuScreens.java.patch
  patches/net/minecraft/client/renderer/GameRenderer.java.patch
  patches/net/minecraft/client/renderer/RenderBuffers.java.patch
  patches/net/minecraft/client/renderer/Sheets.java.patch
  patches/net/minecraft/client/renderer/blockentity/SkullBlockRenderer.java.patch
  patches/net/minecraft/client/renderer/entity/EntityRenderDispatcher.java.patch
  patches/net/minecraft/client/sounds/SoundEngine.java.patch
  patches/net/minecraft/data/DataGenerator.java.patch
  patches/net/minecraft/server/network/ServerConfigurationPacketListenerImpl.java.patch
  patches/net/minecraft/world/entity/SpawnPlacements.java.patch
  src/main/java/net/neoforged/neoforge/capabilities/CapabilityHooks.java
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/ColorResolverManager.java
  src/main/java/net/neoforged/neoforge/client/DimensionSpecialEffectsManager.java
  src/main/java/net/neoforged/neoforge/client/EntitySpectatorShaderManager.java
  src/main/java/net/neoforged/neoforge/client/ItemDecoratorHandler.java
  src/main/java/net/neoforged/neoforge/client/NamedRenderTypeManager.java
  src/main/java/net/neoforged/neoforge/client/PresetEditorManager.java
  src/main/java/net/neoforged/neoforge/client/RecipeBookManager.java
  src/main/java/net/neoforged/neoforge/client/gui/ClientTooltipComponentManager.java
  src/main/java/net/neoforged/neoforge/client/gui/GuiLayerManager.java
  src/main/java/net/neoforged/neoforge/client/gui/LoadingErrorScreen.java
  src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java
  src/main/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/main/java/net/neoforged/neoforge/client/loading/NeoForgeLoadingOverlay.java
  src/main/java/net/neoforged/neoforge/client/model/geometry/GeometryLoaderManager.java
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/world/chunk/ForcedChunkManager.java
  src/main/java/net/neoforged/neoforge/data/loading/DatagenModLoader.java
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/fluids/CauldronFluidContent.java
  src/main/java/net/neoforged/neoforge/gametest/GameTestHooks.java
  src/main/java/net/neoforged/neoforge/internal/CommonModLoader.java
  src/main/java/net/neoforged/neoforge/internal/NeoForgeStatesProvider.java
  src/main/java/net/neoforged/neoforge/internal/package-info.java
  src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java
  src/main/java/net/neoforged/neoforge/registries/GameData.java
  src/main/java/net/neoforged/neoforge/registries/RegistryManager.java
  src/main/java/net/neoforged/neoforge/resource/ResourcePackLoader.java
  src/main/java/net/neoforged/neoforge/server/loading/ServerModLoader.java
  src/main/resources/META-INF/services/net.neoforged.fml.IModStateProvider
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, 1.20.5

#802 [1.20.5] ModelDataManager cleanup
  patches/net/minecraft/client/multiplayer/ClientLevel.java.patch
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
  patches/net/minecraft/client/renderer/block/BlockModelShaper.java.patch
  patches/net/minecraft/client/renderer/chunk/RenderChunkRegion.java.patch
  patches/net/minecraft/client/renderer/chunk/SectionRenderDispatcher.java.patch
  patches/net/minecraft/server/level/ChunkMap.java.patch
  patches/net/minecraft/world/level/Level.java.patch
  patches/net/minecraft/world/level/chunk/ChunkAccess.java.patch
  patches/net/minecraft/world/level/chunk/LevelChunk.java.patch
  src/main/java/net/neoforged/neoforge/client/model/data/ModelDataManager.java
  src/main/java/net/neoforged/neoforge/common/FarmlandWaterManager.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockGetterExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/ILevelExtension.java
  src/main/java/net/neoforged/neoforge/event/level/ChunkEvent.java
Labels: cleanup, breaking change, 1.20.5

#812 Remove x,y parameters from renderSlotContents since they are available as slot.x/slot.y
  patches/net/minecraft/client/gui/screens/inventory/AbstractContainerScreen.java.patch
Labels: 1.20.5

#823 [1.20.5] Remove the unneeded MultipartModelData class wrapper
  src/main/java/net/neoforged/neoforge/client/model/data/MultipartModelData.java
Labels: cleanup, breaking change, 1.20.5

#824 [1.20.5] Remove deprecated IBakedModelExtension#useAmbientOcclusion overloads
  patches/net/minecraft/client/resources/model/MultiPartBakedModel.java.patch
  patches/net/minecraft/client/resources/model/WeightedBakedModel.java.patch
  src/main/java/net/neoforged/neoforge/client/extensions/IBakedModelExtension.java
  src/main/java/net/neoforged/neoforge/client/model/BakedModelWrapper.java
Labels: cleanup, breaking change, 1.20.5

#803 [1.20.5] Make neo attributes use getAttributeValue instead of getAttribute to read, and add fixer for attributes removed/changed in 1.20.5 port
  patches/net/minecraft/util/datafix/DataFixers.java.patch
  patches/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/common/data/fixes/NeoForgeEntityLegacyAttributesFix.java
  src/main/java/net/neoforged/neoforge/common/data/fixes/package-info.java
Labels: bug, enhancement, 1.20.5

#825 [1.20.5] Refactor PacketDistributor to static helper methods
  src/main/java/net/neoforged/neoforge/common/NeoForgeEventHandler.java
  src/main/java/net/neoforged/neoforge/network/PacketDistributor.java
  testframework/src/main/java/net/neoforged/testframework/impl/TestFrameworkImpl.java
Labels: cleanup, breaking change, networking, 1.20.5

#830 Add buckets tag and fixed missing entry from meats tag
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/items/buckets.json
  src/generated/resources/data/c/tags/items/buckets/empty.json
  src/generated/resources/data/c/tags/items/buckets/entity_water.json
  src/generated/resources/data/c/tags/items/buckets/lava.json
  src/generated/resources/data/c/tags/items/buckets/milk.json
  src/generated/resources/data/c/tags/items/buckets/powder_snow.json
  src/generated/resources/data/c/tags/items/buckets/water.json
  src/generated/resources/data/c/tags/items/foods/cooked_meats.json
  src/generated/resources/data/c/tags/items/foods/raw_meats.json
  src/main/java/net/neoforged/neoforge/common/TagConventionLogWarning.java
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: 1.20.5

#851 Remove ability to translate mod names
  src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java
  src/main/java/net/neoforged/neoforge/client/gui/widget/ModListWidget.java
  src/main/java/net/neoforged/neoforge/common/I18nExtension.java
  tests/src/main/resources/META-INF/neoforge.mods.toml
  tests/src/main/resources/assets/neotests/lang/fr_fr.json
Labels: cleanup, breaking change, 1.20.5

#852 Continue processing server brand after configuration listener
  patches/net/minecraft/client/multiplayer/ClientConfigurationPacketListenerImpl.java.patch
Labels: bug, 1.20.5

#686 [FIX] Don't attempt to format modinfo localizations
  src/main/java/net/neoforged/neoforge/common/I18nExtension.java
Labels: bug, 1.20.4

#845 Make custom ingredients never return `true` from `Ingredient#isEmpty`
  patches/net/minecraft/world/item/crafting/Ingredient.java.patch
  tests/src/main/java/net/neoforged/neoforge/debug/crafting/IngredientTests.java
Labels: bug, 1.20.5

#860 [1.20.5] Fix custom spawn eggs using DeferredSpawnEggItem being invisible
  src/main/java/net/neoforged/neoforge/common/DeferredSpawnEggItem.java
Labels: bug, rendering, regression, 1.20.5

#864 Fix crash when rendering corrupted level summaries
  patches/net/minecraft/client/gui/screens/worldselection/WorldSelectionList.java.patch
  patches/net/minecraft/world/level/storage/LevelSummary.java.patch
Labels: bug, 1.20.5

#685 Include modid in "failedtoloadmodclass" error
  src/main/resources/assets/neoforge/lang/da_dk.json
  src/main/resources/assets/neoforge/lang/de_de.json
  src/main/resources/assets/neoforge/lang/en_gb.json
  src/main/resources/assets/neoforge/lang/en_us.json
  src/main/resources/assets/neoforge/lang/es_es.json
  src/main/resources/assets/neoforge/lang/et_ee.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/hu_hu.json
  src/main/resources/assets/neoforge/lang/it_it.json
  src/main/resources/assets/neoforge/lang/ko_kr.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/ro_ro.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/sk_sk.json
  src/main/resources/assets/neoforge/lang/tr_tr.json
  src/main/resources/assets/neoforge/lang/tt_ru.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_hk.json
Labels: enhancement, 1.20.4

#865 Hide demo timer when debug overlay is open
  patches/net/minecraft/client/gui/Gui.java.patch
Labels: bug, rendering, regression, 1.20.5

#866 Fix lava always placing fire blocks in the default state
  patches/net/minecraft/world/level/material/LavaFluid.java.patch
Labels: bug, 1.20.5

#844 Avoid calling getDimensions in Entity constructor
  patches/net/minecraft/world/entity/Entity.java.patch
Labels: bug, regression, 1.20.5

#744 Attempt implementing better safe component type detection
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
Labels: 1.20.5

#847 Remove unnecessary registry supplier redirects
  patches/net/minecraft/world/item/BucketItem.java.patch
  patches/net/minecraft/world/item/MobBucketItem.java.patch
  patches/net/minecraft/world/level/block/LiquidBlock.java.patch
  patches/net/minecraft/world/level/block/StairBlock.java.patch
  patches/net/minecraft/world/level/block/WeatheringCopperStairBlock.java.patch
  src/main/resources/coremods/field_to_method.js
  tests/src/main/java/net/neoforged/neoforge/debug/item/ItemTests.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/fluid/FluidTypeTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/fluid/NewFluidTest.java
Labels: cleanup, breaking change, 1.20.5

#542 [1.20.5] Refactor tick events into distinct subclasses
  patches/net/minecraft/client/Minecraft.java.patch
  patches/net/minecraft/client/multiplayer/ClientLevel.java.patch
  patches/net/minecraft/server/MinecraftServer.java.patch
  patches/net/minecraft/server/level/ServerLevel.java.patch
  patches/net/minecraft/world/entity/Entity.java.patch
  patches/net/minecraft/world/entity/LivingEntity.java.patch
  patches/net/minecraft/world/entity/player/Player.java.patch
  src/main/java/net/neoforged/neoforge/capabilities/CapabilityHooks.java
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/ClientTickEvent.java
  src/main/java/net/neoforged/neoforge/client/event/RenderFrameEvent.java
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeEventHandler.java
  src/main/java/net/neoforged/neoforge/common/extensions/IEntityExtension.java
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/TickEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/living/LivingEvent.java
  src/main/java/net/neoforged/neoforge/event/tick/EntityTickEvent.java
  src/main/java/net/neoforged/neoforge/event/tick/LevelTickEvent.java
  src/main/java/net/neoforged/neoforge/event/tick/PlayerTickEvent.java
  src/main/java/net/neoforged/neoforge/event/tick/ServerTickEvent.java
  src/main/java/net/neoforged/neoforge/event/tick/package-info.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/ClientTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/level/LevelTests.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/client/rendering/CustomParticleTypeTest.java
Labels: cleanup, breaking change, 1.20.5

#871 Add `@Deprecated` annotation to `GiveGiftToHero#GIFTS`
  patches/net/minecraft/world/entity/ai/behavior/GiveGiftToHero.java.patch
Labels: cleanup, 1.20.5

#836 [1.20.5] Misc improvements to QuadLighter
  src/main/java/net/neoforged/neoforge/client/model/lighting/QuadLighter.java
Labels: enhancement, breaking change, 1.20.5

#873 Add quit option to `LoadingErrorScreen`
  src/main/java/net/neoforged/neoforge/client/gui/LoadingErrorScreen.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, 1.20.5

#879 Mark fluid type registry as synced
  src/main/java/net/neoforged/neoforge/registries/NeoForgeRegistries.java
Labels: enhancement, 1.20.5

#876 [1.20.5] Fix getting kicked from vanilla servers when interacting with fireworks
  src/main/java/net/neoforged/neoforge/common/IExtensibleEnum.java
Labels: bug, networking, 1.20.5

#869 Fix `ServerLifecycleHooks.getCurrentServer` being incorrectly marked non-null.
  src/main/java/net/neoforged/neoforge/server/ServerLifecycleHooks.java
Labels: cleanup, 1.20.5

#878 Mark ResourceKeys as being valid component classes
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
Labels: enhancement, 1.20.5

#835 Make hasChannel callable from payload context
  patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IClientCommonPacketListenerExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/ICommonPacketListener.java
  src/main/java/net/neoforged/neoforge/common/extensions/IServerCommonPacketListenerExtension.java
  src/main/java/net/neoforged/neoforge/network/filters/GenericPacketSplitter.java
  src/main/java/net/neoforged/neoforge/network/handling/ClientPayloadContext.java
  src/main/java/net/neoforged/neoforge/network/handling/IPayloadContext.java
  src/main/java/net/neoforged/neoforge/network/handling/ServerPayloadContext.java
Labels: breaking change, networking, 1.20.5

#858 [1.20.x] Render local player when the renderViewEntity is not the local player
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
Labels: bug, rendering, regression, 1.20.5

#859 [1.20.4] Render local player when the renderViewEntity is not the local player
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
Labels: bug, rendering, regression, 1.20.4

#870 Remove AT for `MenuScreens.register`
  patches/net/minecraft/client/gui/screens/MenuScreens.java.patch
  src/main/resources/META-INF/accesstransformer.cfg
Labels: cleanup, 1.20.5

#891 AT BucketItem#content and LiquidBlock#fluid to be public
  patches/net/minecraft/world/item/BucketItem.java.patch
  src/main/java/net/neoforged/neoforge/fluids/capability/wrappers/BucketPickupHandlerWrapper.java
  src/main/java/net/neoforged/neoforge/fluids/capability/wrappers/FluidBucketWrapper.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: cleanup, breaking change, 1.20.5

#810 [TestFramework] Add a config option to force all tests to have a description
  testframework/src/main/java/net/neoforged/testframework/conf/FrameworkConfiguration.java
  testframework/src/main/java/net/neoforged/testframework/conf/MissingDescriptionAction.java
  testframework/src/main/java/net/neoforged/testframework/impl/TestFrameworkImpl.java
  tests/src/main/java/net/neoforged/neoforge/debug/level/LevelEventTests.java
  tests/src/main/java/net/neoforged/neoforge/eventtest/internal/TestsMod.java
Labels: enhancement, 1.20.5

#890 Fix position of "continue" button on loading warn screen.
  src/main/java/net/neoforged/neoforge/client/gui/LoadingErrorScreen.java
Labels: bug, 1.20.6

#735 [1.20.6] Various fixes to mod resource pack quirks
  patches/net/minecraft/server/MinecraftServer.java.patch
  patches/net/minecraft/server/commands/ReloadCommand.java.patch
  patches/net/minecraft/server/packs/repository/Pack.java.patch
  patches/net/minecraft/server/packs/repository/PackRepository.java.patch
  src/main/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/event/AddPackFindersEvent.java
  src/main/java/net/neoforged/neoforge/resource/ResourcePackLoader.java
  src/main/resources/META-INF/accesstransformer.cfg
  testframework/src/main/java/net/neoforged/testframework/impl/reg/RegistrationHelperImpl.java
Labels: enhancement, breaking change, 1.20.5
