Repository neoforged/NeoForge, pull requests merged in 2024-01, with the labels that each got.

#453 Add public getters for shaped recipe width and height fields
  patches/net/minecraft/world/item/crafting/ShapedRecipePattern.java.patch
  patches/net/minecraft/world/item/crafting/ShapelessRecipe.java.patch
Labels: bug, 1.20

#455 Fix NoClassDefFoundError on dedicated server
  src/main/java/net/neoforged/neoforge/common/extensions/IServerGamePacketListenerExtension.java
  src/main/java/net/neoforged/neoforge/network/negotiation/NetworkComponentNegotiator.java
  src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java
Labels: bug, 1.20, regression

#451 Patch cleanup
  build.gradle
  patches/com/mojang/realmsclient/gui/screens/RealmsGenericErrorScreen.java.patch
  patches/net/minecraft/client/gui/components/DebugScreenOverlay.java.patch
  patches/net/minecraft/client/gui/screens/worldselection/WorldCreationUiState.java.patch
  patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch
  patches/net/minecraft/client/multiplayer/ClientConfigurationPacketListenerImpl.java.patch
  patches/net/minecraft/client/renderer/block/LiquidBlockRenderer.java.patch
  patches/net/minecraft/network/ConnectionProtocol.java.patch
  patches/net/minecraft/network/protocol/BundlerInfo.java.patch
  patches/net/minecraft/resources/RegistryOps.java.patch
  patches/net/minecraft/resources/ResourceLocation.java.patch
  patches/net/minecraft/server/level/ServerLevel.java.patch
  patches/net/minecraft/server/network/ConfigurationTask.java.patch
  patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch
  patches/net/minecraft/server/network/ServerConfigurationPacketListenerImpl.java.patch
  patches/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
  patches/net/minecraft/server/packs/repository/BuiltInPackSource.java.patch
  patches/net/minecraft/server/rcon/thread/RconClient.java.patch
  patches/net/minecraft/tags/TagFile.java.patch
  patches/net/minecraft/world/entity/Mob.java.patch
  patches/net/minecraft/world/entity/raid/Raid.java.patch
  patches/net/minecraft/world/item/crafting/Ingredient.java.patch
  patches/net/minecraft/world/item/crafting/RecipeManager.java.patch
Labels: bug, enhancement, 1.20

#452 NeoForge chunk generate command improvements
  src/main/java/net/neoforged/neoforge/server/command/generation/CoarseOnionIterator.java
  src/main/java/net/neoforged/neoforge/server/command/generation/GenerationTask.java
Labels: enhancement, 1.20

#460 Fix finalize spawn playing ambient sounds for cancelled mob spawns
  patches/net/minecraft/world/entity/EntityType.java.patch
  tests/src/main/java/net/neoforged/neoforge/oldtest/FinalizeSpawnTest.java
  tests/src/main/resources/META-INF/mods.toml
Labels: bug, 1.20

#458 Expand particle bounding boxes by 1 unit in all directions when culling
  patches/net/minecraft/client/particle/ParticleEngine.java.patch
Labels: bug, 1.20, rendering

#468 Update NG and use newer installer versions
  .github/workflows/release.yml
  projects/neoforge/build.gradle
  settings.gradle
  src/main/resources/neoforged_logo.png
Labels: enhancement

#469 Create AttachmentHolder map lazily
  src/main/java/net/neoforged/neoforge/attachment/AttachmentHolder.java
  src/main/java/net/neoforged/neoforge/attachment/AttachmentInternals.java
Labels: 1.20, performance

#462 Allow attachments to capture a reference to their holder on construction
  patches/net/minecraft/world/level/chunk/LevelChunk.java.patch
  src/main/java/net/neoforged/neoforge/attachment/AttachmentHolder.java
  src/main/java/net/neoforged/neoforge/attachment/AttachmentInternals.java
  src/main/java/net/neoforged/neoforge/attachment/AttachmentType.java
  src/main/java/net/neoforged/neoforge/attachment/IAttachmentSerializer.java
  testframework/src/main/java/net/neoforged/testframework/gametest/ExtendedGameTestHelper.java
  tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/chat/CommandTests.java
Labels: enhancement, 1.20, breaking change

#448 EntityType Settings Issues
  patches/net/minecraft/world/entity/EntityType.java.patch
Labels: bug, 1.20, regression

#433 [1.20.4] Snapshot ModelDataManager in RenderChunkRegion instead of exposing original ModelDataManager owned by ClientLevel
  patches/net/minecraft/client/multiplayer/ClientLevel.java.patch
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
  patches/net/minecraft/client/renderer/block/BlockModelShaper.java.patch
  patches/net/minecraft/client/renderer/chunk/RenderChunkRegion.java.patch
  patches/net/minecraft/client/renderer/chunk/RenderRegionCache.java.patch
  patches/net/minecraft/client/renderer/chunk/SectionRenderDispatcher.java.patch
  patches/net/minecraft/world/level/Level.java.patch
  src/main/java/net/neoforged/neoforge/client/model/data/ModelDataManager.java
Labels: enhancement, 1.20, rendering, breaking change

#482 [1.20.1] Backport progress bar improvements from #404
  src/main/java/net/minecraftforge/client/loading/ForgeLoadingOverlay.java
Labels: enhancement, 1.20, backport

#484 Check registry aliases in registry.get(ResourceLocation)
  patches/net/minecraft/core/MappedRegistry.java.patch
Labels: bug, 1.20

#477 Make sure empty model data is not inserted into manager
  src/main/java/net/neoforged/neoforge/client/model/data/ModelDataManager.java
Labels: bug, 1.20

#487 Bump NG to fix the installer not working on Java 8
  .github/workflows/release.yml
  settings.gradle
Labels: bug, 1.20

#478 Improve withAlternative support for MapCodecCodecs
  patches/net/minecraft/advancements/Advancement.java.patch
  patches/net/minecraft/data/recipes/RecipeProvider.java.patch
  patches/net/minecraft/server/ServerAdvancementManager.java.patch
  patches/net/minecraft/world/item/crafting/Recipe.java.patch
  patches/net/minecraft/world/item/crafting/RecipeManager.java.patch
  src/main/java/net/neoforged/neoforge/common/util/NeoForgeExtraCodecs.java
Labels: enhancement, 1.20

#483 Add system for conditional pack overlays
  patches/net/minecraft/server/packs/OverlayMetadataSection.java.patch
  src/main/java/net/neoforged/neoforge/common/data/GeneratingOverlayMetadataSection.java
  src/main/resources/META-INF/accesstransformer.cfg
  tests/src/generated/resources/pack.mcmeta
  tests/src/main/java/net/neoforged/neoforge/debug/resources/OverlayTests.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/DataGeneratorTest.java
  tests/src/main/resources/conditional_overlays_disabled/data/conditional_overlays_test/tags/blocks/overlay_disabled.json
  tests/src/main/resources/conditional_overlays_enabled/data/conditional_overlays_test/tags/blocks/overlay_enabled.json
  tests/src/main/resources/data/conditional_overlays_test/tags/blocks/overlay_disabled.json
  tests/src/main/resources/data/conditional_overlays_test/tags/blocks/overlay_enabled.json
Labels: enhancement, 1.20

#464 [1.20.4] Add thread-safe side-band system for lighting driven by BlockEntity data
  patches/net/minecraft/client/renderer/chunk/RenderChunkRegion.java.patch
  patches/net/minecraft/server/network/PlayerChunkSender.java.patch
  patches/net/minecraft/world/level/chunk/LevelChunk.java.patch
  patches/net/minecraft/world/level/chunk/storage/ChunkSerializer.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockGetterExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IFriendlyByteBufExtension.java
  src/main/java/net/neoforged/neoforge/common/world/AuxiliaryLightManager.java
  src/main/java/net/neoforged/neoforge/common/world/LevelChunkAuxiliaryLightManager.java
  src/main/java/net/neoforged/neoforge/network/NetworkInitialization.java
  src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java
  src/main/java/net/neoforged/neoforge/network/payload/AuxiliaryLightDataPayload.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/assets/neoforge/lang/en_us.json
  tests/src/main/java/net/neoforged/neoforge/debug/block/BlockPropertyTests.java
Labels: enhancement, 1.20, breaking change

#496 Fix custom baked quad generators producing tinted quads by default
  src/main/java/net/neoforged/neoforge/client/model/obj/ObjMaterialLibrary.java
  src/main/java/net/neoforged/neoforge/client/model/pipeline/QuadBakingVertexConsumer.java
Labels: bug, 1.20

#500 Fix the `/neoforge tps` command not taking into account the actual tick rate of the world
  src/main/java/net/neoforged/neoforge/server/command/TPSCommand.java
Labels: bug, 1.20, blocks stable

#501 Add a simple hook to allow custom fluid rendering
  patches/net/minecraft/client/renderer/block/BlockRenderDispatcher.java.patch
  src/main/java/net/neoforged/neoforge/client/extensions/common/IClientFluidTypeExtensions.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/fluid/FluidTypeTest.java
Labels: enhancement, 1.20, rendering

#76 [1.20.x] Broaden generic restrictions on `RangedCrossbowAttackGoal`
  patches/net/minecraft/world/entity/ai/goal/RangedCrossbowAttackGoal.java.patch
Labels: enhancement, 1.20

#509 [1.20.4] Extensible Damage Types
  patches/net/minecraft/client/renderer/GameRenderer.java.patch
  patches/net/minecraft/world/damagesource/CombatTracker.java.patch
  patches/net/minecraft/world/damagesource/DamageEffects.java.patch
  patches/net/minecraft/world/damagesource/DamageScaling.java.patch
  patches/net/minecraft/world/damagesource/DamageSource.java.patch
  patches/net/minecraft/world/damagesource/DeathMessageType.java.patch
  patches/net/minecraft/world/effect/PoisonMobEffect.java.patch
  patches/net/minecraft/world/entity/player/Player.java.patch
  src/generated/resources/data/forge/tags/damage_type/is_environment.json
  src/generated/resources/data/forge/tags/damage_type/is_magic.json
  src/generated/resources/data/forge/tags/damage_type/is_physical.json
  src/generated/resources/data/forge/tags/damage_type/is_poison.json
  src/generated/resources/data/forge/tags/damage_type/is_technical.json
  src/generated/resources/data/forge/tags/damage_type/is_wither.json
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/damagesource/IDeathMessageProvider.java
  src/main/java/net/neoforged/neoforge/common/damagesource/IScalingFunction.java
  src/main/java/net/neoforged/neoforge/common/data/NeoForgeDamageTypeTagsProvider.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/data/neoforge/damage_type/poison.json
  tests/src/generated/resources/data/test/damage_type/test.json
  tests/src/main/java/net/neoforged/neoforge/debug/damagesource/DamageTypeTests.java
Labels: enhancement, 1.20

#80 Update license branding
  LICENSE.txt
Labels: documentation

#503 [1.20.4] Add GetEnchantmentLevelEvent
  patches/net/minecraft/world/item/enchantment/EnchantmentHelper.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/enchanting/GetEnchantmentLevelEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/enchantment/EnchantmentLevelTests.java
Labels: enhancement, 1.20

#471 Make chunk sections only be considered all air if filled with Blocks.AIR only
  patches/net/minecraft/world/level/chunk/LevelChunkSection.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockStateExtension.java
Labels: bug, 1.20

#512 Have Watchdog print the full stacktraces when doing a thread dump
  patches/net/minecraft/server/dedicated/ServerWatchdog.java.patch
  src/main/java/net/neoforged/neoforge/logging/ThreadInfoUtil.java
Labels: enhancement, 1.20

#59 [1.20.1] Extensible Damage Types
  patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch
  patches/minecraft/net/minecraft/world/damagesource/CombatTracker.java.patch
  patches/minecraft/net/minecraft/world/damagesource/DamageEffects.java.patch
  patches/minecraft/net/minecraft/world/damagesource/DamageScaling.java.patch
  patches/minecraft/net/minecraft/world/damagesource/DamageSource.java.patch
  patches/minecraft/net/minecraft/world/damagesource/DeathMessageType.java.patch
  patches/minecraft/net/minecraft/world/effect/MobEffect.java.patch
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
  src/generated/resources/data/forge/tags/damage_type/is_environment.json
  src/generated/resources/data/forge/tags/damage_type/is_magic.json
  src/generated/resources/data/forge/tags/damage_type/is_physical.json
  src/generated/resources/data/forge/tags/damage_type/is_poison.json
  src/generated/resources/data/forge/tags/damage_type/is_technical.json
  src/generated/resources/data/forge/tags/damage_type/is_wither.json
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/Tags.java
  src/main/java/net/minecraftforge/common/damagesource/IDeathMessageProvider.java
  src/main/java/net/minecraftforge/common/damagesource/IScalingFunction.java
  src/main/java/net/minecraftforge/common/data/ForgeDamageTypeTagsProvider.java
  src/main/java/net/minecraftforge/common/extensions/IForgeTagAppender.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/data/forge/damage_type/poison.json
  src/test/java/net/minecraftforge/debug/CustomDamageTypeTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/data/test/damage_type/test.json
Labels: enhancement, 1.20, backport

#129 [1.20.1] Add GetEnchantmentLevelEvent
  patches/minecraft/net/minecraft/world/item/enchantment/EnchantmentHelper.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/main/java/net/minecraftforge/common/extensions/IForgeItemStack.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/GetEnchantmentLevelEvent.java
  src/test/java/net/minecraftforge/debug/misc/GetEnchantmentLevelEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: enhancement, 1.20, backport

#507 [1.20.4] Fix GUI far plane calculation to match vanilla
  patches/net/minecraft/client/renderer/GameRenderer.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/GuiTests.java
Labels: bug, 1.20, rendering, last call

#514 Fire LivingConversionEvent Pre and Post properly for Husk, Tadpole, Mushroom, and Skeleton conversions
  patches/net/minecraft/world/entity/animal/MushroomCow.java.patch
  patches/net/minecraft/world/entity/animal/frog/Tadpole.java.patch
  patches/net/minecraft/world/entity/monster/Husk.java.patch
  patches/net/minecraft/world/entity/monster/Skeleton.java.patch
  patches/net/minecraft/world/entity/monster/Zombie.java.patch
  src/main/resources/META-INF/accesstransformer.cfg
Labels: 1.20, last call

#534 add `CalculateTurnPlayerValuesEvent`
  patches/net/minecraft/client/MouseHandler.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/CalculatePlayerTurnEvent.java
Labels: enhancement, 1.20, triage

#532 Bump MixinExtras to 0.3.5
  gradle.properties
Labels: 1.20, last call

#525 [1.20.4] Properly log exceptions in the vanilla network stack
  patches/net/minecraft/network/Connection.java.patch
  patches/net/minecraft/network/PacketEncoder.java.patch
Labels: enhancement, 1.20, networking

#541 [1.20.4] Move `BuildCreativeModeTabContentsEvent` out of client-only code
  patches/net/minecraft/world/item/CreativeModeTab.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/event/BuildCreativeModeTabContentsEvent.java
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
Labels: bug, 1.20, breaking change

#508 Add `RegisterMenuScreensEvent` to replace `MenuScreens#register(MenuType, ScreenConstructor)`
  patches/net/minecraft/client/gui/screens/MenuScreens.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/RegisterMenuScreensEvent.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/misc/ContainerTypeTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/recipebook/RecipeBookExtensionTest.java
Labels: enhancement, 1.20, breaking change

#546 Add RegisterRenderBuffersEvent to register fixed BufferBuilder's for RenderType's
  patches/net/minecraft/client/renderer/RenderBuffers.java.patch
  src/main/java/net/neoforged/neoforge/client/event/RegisterRenderBuffersEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/ClientEventTests.java
Labels: enhancement, 1.20

#475 Add attachment support to ItemStack and recipe output codecs, and recipe builders
  patches/net/minecraft/data/recipes/ShapedRecipeBuilder.java.patch
  patches/net/minecraft/data/recipes/ShapelessRecipeBuilder.java.patch
  patches/net/minecraft/data/recipes/SimpleCookingRecipeBuilder.java.patch
  patches/net/minecraft/world/item/ItemStack.java.patch
  src/main/java/net/neoforged/neoforge/common/crafting/CraftingHelper.java
  tests/src/generated/resources/data/neotests_item_attachment_recipe_output/advancements/recipes/misc/test_blasting.json
  tests/src/generated/resources/data/neotests_item_attachment_recipe_output/advancements/recipes/misc/test_shaped.json
  tests/src/generated/resources/data/neotests_item_attachment_recipe_output/advancements/recipes/misc/test_shapeless.json
  tests/src/generated/resources/data/neotests_item_attachment_recipe_output/recipes/test_blasting.json
  tests/src/generated/resources/data/neotests_item_attachment_recipe_output/recipes/test_shaped.json
  tests/src/generated/resources/data/neotests_item_attachment_recipe_output/recipes/test_shapeless.json
  tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java
Labels: enhancement, 1.20

#524 [1.20.4] Add Mob Split Event
  patches/net/minecraft/world/entity/monster/Slime.java.patch
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/entity/living/MobSplitEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/living/LivingEntityEventTests.java
Labels: enhancement, 1.20

#551 Fix onHorseArmorTick call site
  patches/net/minecraft/world/entity/animal/horse/AbstractHorse.java.patch
  patches/net/minecraft/world/entity/animal/horse/Horse.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
Labels: 1.20, cleanup

#555 [1.20.1] Fix CME in ModelDataManager
  src/main/java/net/minecraftforge/client/model/data/ModelDataManager.java
Labels: bug, 1.20, rendering

#556 [1.20.1] Avoid crash in AddLayers event for renderers of the wrong type
  src/main/java/net/minecraftforge/client/event/EntityRenderersEvent.java
Labels: bug, 1.20, rendering

#557 [1.20.1] Fix being unable to cancel deleting a world
  patches/minecraft/net/minecraft/client/gui/screens/worldselection/WorldSelectionList.java.patch
Labels: bug, 1.20

#558 [1.20.4] Adjust registration order of modded registry entries to follow BuiltInRegistries.LOADERS
  patches/net/minecraft/core/MappedRegistry.java.patch
  patches/net/minecraft/core/registries/BuiltInRegistries.java.patch
  src/generated/resources/reports/registry_order.json
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeRegistryOrderReportProvider.java
  src/main/java/net/neoforged/neoforge/registries/GameData.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/world/LoginPacketSplitTest.java
Labels: bug, 1.20, breaking change

#564 [1.20.1] Short-circuit Realms check in dev
  patches/minecraft/com/mojang/realmsclient/gui/screens/RealmsNotificationsScreen.java.patch
Labels: enhancement, 1.20, backport

#563 [1.20.1] Remove redundant getResource call in DelegatingPackResources
  src/main/java/net/minecraftforge/resource/DelegatingPackResources.java
Labels: enhancement, 1.20, backport

#565 [1.20.1] Fix `BakedModel#getModelData` not being called for breaking texture
  patches/minecraft/net/minecraft/client/renderer/block/BlockRenderDispatcher.java.patch
Labels: bug, 1.20, backport

#567 [1.20.1] Suppress update checking
  src/main/resources/META-INF/mods.toml
Labels: 1.20, backport

#562 Expose what entity types have renderers to the AddLayer event
  src/main/java/net/neoforged/neoforge/client/event/EntityRenderersEvent.java
Labels: enhancement, 1.20

#568 Simplify LevelRenderer visible block entity patch
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
  src/main/java/net/neoforged/neoforge/client/BlockEntityRenderBoundsDebugRenderer.java
Labels: enhancement, 1.20, cleanup

#545 [1.20.4] Fix ModListScreen link detection
  src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java
Labels: bug, 1.20

#578 [1.20.4] Add back vanilla RecipeProvider constructor
  patches/net/minecraft/data/Main.java.patch
  patches/net/minecraft/data/recipes/RecipeProvider.java.patch
  patches/net/minecraft/data/recipes/packs/BundleRecipeProvider.java.patch
  patches/net/minecraft/data/recipes/packs/UpdateOneTwentyOneRecipeProvider.java.patch
  patches/net/minecraft/data/recipes/packs/VanillaRecipeProvider.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeRecipeProvider.java
  tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/crafting/IngredientTests.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/DataGeneratorTest.java
Labels: 1.20, cleanup

#575 [1.20.4] Provide preliminary atlas stitch results in ModelEvent.ModifyBakingResult
  patches/net/minecraft/client/resources/model/ModelManager.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/ModelEvent.java
Labels: enhancement, 1.20, rendering

#576 Synchronize when iterating over `globalBlockEntities`
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
Labels: bug, 1.20

#519 [1.20.4] Data maps
  patches/net/minecraft/core/Holder.java.patch
  patches/net/minecraft/core/HolderLookup.java.patch
  patches/net/minecraft/core/MappedRegistry.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeEventHandler.java
  src/main/java/net/neoforged/neoforge/common/data/DataMapProvider.java
  src/main/java/net/neoforged/neoforge/common/extensions/IFriendlyByteBufExtension.java
  src/main/java/net/neoforged/neoforge/internal/RegistrationEvents.java
  src/main/java/net/neoforged/neoforge/network/ConfigurationInitialization.java
  src/main/java/net/neoforged/neoforge/network/NetworkInitialization.java
  src/main/java/net/neoforged/neoforge/network/configuration/RegistryDataMapNegotiation.java
  src/main/java/net/neoforged/neoforge/network/payload/KnownRegistryDataMapsPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/KnownRegistryDataMapsReplyPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/RegistryDataMapSyncPayload.java
  src/main/java/net/neoforged/neoforge/registries/BaseMappedRegistry.java
  src/main/java/net/neoforged/neoforge/registries/ClientRegistryManager.java
  src/main/java/net/neoforged/neoforge/registries/DataMapLoader.java
  src/main/java/net/neoforged/neoforge/registries/IRegistryExtension.java
  src/main/java/net/neoforged/neoforge/registries/RegistryManager.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/AdvancedDataMapType.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/DataMapEntry.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/DataMapFile.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/DataMapType.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/DataMapValueMerger.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/DataMapValueRemover.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/IWithData.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/RegisterDataMapTypesEvent.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/package-info.java
  src/main/resources/assets/neoforge/lang/en_us.json
  testframework/src/main/java/net/neoforged/testframework/TestFramework.java
  testframework/src/main/java/net/neoforged/testframework/impl/TestFrameworkImpl.java
  testframework/src/main/java/net/neoforged/testframework/impl/reg/RegistrationHelperImpl.java
  testframework/src/main/java/net/neoforged/testframework/impl/test/AbstractTest.java
  testframework/src/main/java/net/neoforged/testframework/registration/RegistrationHelper.java
  tests/src/generated/resources/data/neotests_data_map_merger/data_maps/item/some_list.json
  tests/src/generated/resources/data/neotests_data_map_remover/data_maps/item/some_map.json
  tests/src/generated/resources/data/neotests_data_map_test/data_maps/item/some_data.json
  tests/src/generated/resources/data/neotests_dynamic_reg_data_maps/data_maps/damage_type/xp_grant.json
  tests/src/generated/resources/neotests_data_map_merger_second_layer/data/neotests_data_map_merger/data_maps/item/some_list.json
  tests/src/generated/resources/neotests_data_map_remover_second_layer/data/neotests_data_map_remover/data_maps/item/some_map.json
  tests/src/main/java/net/neoforged/neoforge/debug/data/DataMapTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/data/package-info.java
Labels: enhancement, 1.20

#559 Fix misaligned ShieldBlockEvent patch
  patches/net/minecraft/world/entity/LivingEntity.java.patch
Labels: bug, 1.20

#579 [1.20.4] Reinstate screen drag event patch
  patches/net/minecraft/client/MouseHandler.java.patch
Labels: bug, 1.20, regression

#587 [Eclipse Compiler] Fix generic inference issue in DataMapEntry
  src/main/java/net/neoforged/neoforge/registries/datamaps/DataMapEntry.java
Labels: bug, 1.20

#582 Removed shrink of U and V by 16 in UnitTextureAtlasSprite
  src/main/java/net/neoforged/neoforge/client/textures/UnitTextureAtlasSprite.java
Labels: bug, 1.20, rendering

#583 Compostables as data maps
  patches/net/minecraft/world/level/block/ComposterBlock.java.patch
  src/generated/resources/data/neoforge/data_maps/item/compostables.json
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeDataMapsProvider.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/Compostable.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/NeoForgeDataMaps.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/package-info.java
  tests/src/generated/resources/data/neoforge/data_maps/item/compostables.json
  tests/src/main/java/net/neoforged/neoforge/debug/data/DataMapTests.java
Labels: enhancement, 1.20, last call

#522 Bump FML to account for recent changes
  gradle.properties
  projects/neoforge/build.gradle
  settings.gradle
Labels: enhancement, 1.20

#549 [1.20.4] Fix inventoryTick and deprecate onArmorTick
  patches/net/minecraft/world/entity/player/Inventory.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
Labels: bug, 1.20, cleanup

#498 New Crowdin updates
  src/main/resources/assets/neoforge/lang/da_dk.json
  src/main/resources/assets/neoforge/lang/de_de.json
  src/main/resources/assets/neoforge/lang/en_gb.json
  src/main/resources/assets/neoforge/lang/es_es.json
  src/main/resources/assets/neoforge/lang/et_ee.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/hu_hu.json
  src/main/resources/assets/neoforge/lang/it_it.json
  src/main/resources/assets/neoforge/lang/ko_kr.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/ro_ro.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/sk_sk.json
  src/main/resources/assets/neoforge/lang/tr_tr.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_hk.json
Labels: l10n

#581 Simplify shear patches and fix some differences compared to vanilla
  patches/net/minecraft/world/entity/Entity.java.patch
  patches/net/minecraft/world/entity/Shearable.java.patch
  patches/net/minecraft/world/entity/animal/MushroomCow.java.patch
  patches/net/minecraft/world/entity/animal/Sheep.java.patch
  patches/net/minecraft/world/entity/animal/SnowGolem.java.patch
  patches/net/minecraft/world/item/ShearsItem.java.patch
  src/main/java/net/neoforged/neoforge/common/IShearable.java
Labels: bug, enhancement, 1.20, cleanup

#585 Add various helpers to FluidStack similar to those in ItemStack and BlockState
  src/main/java/net/neoforged/neoforge/fluids/FluidStack.java
  src/main/java/net/neoforged/neoforge/fluids/FluidUtil.java
  src/main/java/net/neoforged/neoforge/fluids/capability/templates/FluidHandlerItemStack.java
  src/main/java/net/neoforged/neoforge/fluids/capability/templates/FluidHandlerItemStackSimple.java
  src/main/java/net/neoforged/neoforge/fluids/capability/wrappers/BlockWrapper.java
  src/main/java/net/neoforged/neoforge/fluids/capability/wrappers/BucketPickupHandlerWrapper.java
  src/main/java/net/neoforged/neoforge/fluids/capability/wrappers/CauldronWrapper.java
  src/main/java/net/neoforged/neoforge/fluids/capability/wrappers/FluidBlockWrapper.java
  src/main/java/net/neoforged/neoforge/fluids/capability/wrappers/FluidBucketWrapper.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/FluidUtilTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/item/CustomFluidContainerTest.java
Labels: enhancement, 1.20

#592 [1.20.4] Move Attribute to head of registration order
  src/generated/resources/reports/registry_order.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeRegistryOrderReportProvider.java
  src/main/java/net/neoforged/neoforge/registries/GameData.java
Labels: bug, 1.20
