Repository neoforged/NeoForge, pull requests merged in 2024-07, with the labels that each got.

#1134 [1.21] Rich/Component translations
  patches/net/minecraft/client/resources/language/ClientLanguage.java.patch
  patches/net/minecraft/locale/Language.java.patch
  patches/net/minecraft/network/chat/ComponentSerialization.java.patch
  patches/net/minecraft/network/chat/contents/TranslatableContents.java.patch
  src/main/java/net/neoforged/neoforge/common/util/InsertingContents.java
  src/main/java/net/neoforged/neoforge/server/LanguageHook.java
  tests/src/main/java/net/neoforged/neoforge/debug/resources/RichTranslationsTest.java
  tests/src/main/resources/assets/rich_translations_test/lang/en_us.json
Labels: enhancement, 1.21

#1203 Add an Item Ability to determine if an item can remove wolf armor (#1062)
  patches/net/minecraft/world/entity/animal/Wolf.java.patch
  src/generated/resources/data/minecraft/advancement/husbandry/remove_wolf_armor.json
  src/main/java/net/neoforged/neoforge/common/ItemAbilities.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeAdvancementProvider.java
Labels: enhancement, 1.21

#1202 Expand powdered snow advancement to check modded armor
  src/generated/resources/data/minecraft/advancement/adventure/walk_on_powder_snow_with_leather_boots.json
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/advancements/critereon/SnowBootsEntityPredicate.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeAdvancementProvider.java
Labels: enhancement, 1.21

#1187 [1.21] Fix data generator merge issue
  patches/net/minecraft/data/DataGenerator.java.patch
  src/main/java/net/neoforged/neoforge/data/event/GatherDataEvent.java
Labels: bug, enhancement, 1.21

#1215 Add poison damage type to tags containing `minecraft:magic`
  src/generated/resources/data/minecraft/tags/damage_type/always_triggers_silverfish.json
  src/generated/resources/data/minecraft/tags/damage_type/avoids_guardian_thorns.json
  src/generated/resources/data/minecraft/tags/damage_type/bypasses_armor.json
  src/generated/resources/data/minecraft/tags/damage_type/bypasses_wolf_armor.json
  src/generated/resources/data/minecraft/tags/damage_type/no_knockback.json
  src/generated/resources/data/minecraft/tags/damage_type/panic_causes.json
  src/generated/resources/data/minecraft/tags/damage_type/witch_resistant_to.json
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeDamageTypeTagsProvider.java
Labels: bug, 1.21

#1197 Replace hardcoded Blocks.FARMLAND checks with FarmBlock
  patches/net/minecraft/world/entity/animal/Rabbit.java.patch
  patches/net/minecraft/world/level/block/AttachedStemBlock.java.patch
  patches/net/minecraft/world/level/block/BushBlock.java.patch
  patches/net/minecraft/world/level/block/CropBlock.java.patch
  patches/net/minecraft/world/level/block/PitcherCropBlock.java.patch
  patches/net/minecraft/world/level/block/StemBlock.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, 1.21

#997 [1.21] Move Mod button below Realms and adjust branding text
  patches/net/minecraft/client/gui/screens/TitleScreen.java.patch
  src/main/java/net/neoforged/neoforge/internal/BrandingControl.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, 1.21

#1223 Fix Realms notification positioning
  patches/com/mojang/realmsclient/gui/screens/RealmsNotificationsScreen.java.patch
Labels: bug, 1.21

#1189 Fix `ArrowLooseEvent` not firing for bows
  patches/net/minecraft/world/item/BowItem.java.patch
Labels: bug, regression, 1.21

#1213 Reimplement hook for CustomizeGuiOverlayEvent.Chat
  patches/net/minecraft/client/gui/Gui.java.patch
Labels: bug, regression, 1.21

#1230 Update FML / ModLauncher (Updates Mixin, Improved Error Reporting, Addresses Log4j2 Warnings)
  gradle.properties
  src/main/java/net/neoforged/neoforge/internal/NeoForgeBindings.java
Labels: bug, enhancement, 1.21

#1177 Damage pipeline improvements
  patches/net/minecraft/world/entity/LivingEntity.java.patch
  patches/net/minecraft/world/entity/player/Player.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/damagesource/DamageContainer.java
  src/main/java/net/neoforged/neoforge/event/entity/living/LivingDamageEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/living/LivingEntityEventTests.java
Labels: bug, blocks stable, 1.21

#1221 Use substitution in the testframework mod metadata
  testframework/build.gradle
  testframework/src/main/resources/META-INF/neoforge.mods.toml
Labels: bug, 1.21

#1241 Avoid Optional allocation in patched-in Holder equals functions
  patches/net/minecraft/core/Holder.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IHolderExtension.java
  src/main/java/net/neoforged/neoforge/registries/DeferredHolder.java
Labels: performance, 1.21

#1049 Add BlockEntityTypeAddBlocksEvent to allow adding new valid blocks to existing BlockEntityTypes
  patches/net/minecraft/world/level/block/entity/BlockEntityType.java.patch
  src/main/java/net/neoforged/neoforge/event/BlockEntityTypeAddBlocksEvent.java
  src/main/java/net/neoforged/neoforge/mixins/BlockEntityTypeAccessor.java
  src/main/java/net/neoforged/neoforge/mixins/package-info.java
  src/main/java/net/neoforged/neoforge/registries/GameData.java
  src/main/resources/META-INF/neoforge.mods.toml
  src/main/resources/neoforge.mixins.json
  tests/src/junit/java/net/neoforged/neoforge/unittest/BlockEntityTypeValidBlocksEventTests.java
  tests/src/junit/resources/META-INF/neoforge.mods.toml
Labels: enhancement, 1.21

#1229 Add armadillo support for item ability `BRUSH_BRUSH`
  patches/net/minecraft/world/entity/animal/armadillo/Armadillo.java.patch
Labels: enhancement, 1.21

#1227 [1.21.x] Properly sync biomes modified by biome modifiers
  src/main/java/net/neoforged/neoforge/common/world/ModifiableBiomeInfo.java
  src/main/java/net/neoforged/neoforge/mixins/MappedRegistryAccessor.java
  src/main/java/net/neoforged/neoforge/server/ServerLifecycleHooks.java
  src/main/resources/neoforge.mixins.json
  tests/src/generated/resources/data/neotests_biome_modifier_sync_test/neoforge/biome_modifier/modify_taiga.json
  tests/src/main/java/net/neoforged/neoforge/debug/registry/BiomeModifierSyncTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/registry/package-info.java
Labels: bug, 1.21, data driven

#1240 [1.21] Add GatherEffectScreenTooltipsEvent
  patches/net/minecraft/client/gui/screens/inventory/EffectRenderingInventoryScreen.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/GatherEffectScreenTooltipsEvent.java
Labels: enhancement, 1.21

#1156 Split BuildCreativeModeTabContentsEvent internals to operate on two separate sets
  src/main/java/net/neoforged/neoforge/common/util/InsertableLinkedOpenCustomHashSet.java
  src/main/java/net/neoforged/neoforge/common/util/MutableHashedLinkedMap.java
  src/main/java/net/neoforged/neoforge/common/util/strategy/BasicStrategy.java
  src/main/java/net/neoforged/neoforge/common/util/strategy/IdentityStrategy.java
  src/main/java/net/neoforged/neoforge/common/util/strategy/package-info.java
  src/main/java/net/neoforged/neoforge/event/BuildCreativeModeTabContentsEvent.java
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/CreativeTabOrderTest.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/InsertableLinkedOpenCustomHashSetTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/CreativeModeTabTest.java
Labels: bug, breaking change, 1.21

#1247 [1.21] Delete IShapedRecipe
  patches/net/minecraft/recipebook/PlaceRecipe.java.patch
  patches/net/minecraft/world/item/crafting/ShapedRecipe.java.patch
  src/main/java/net/neoforged/neoforge/common/crafting/IShapedRecipe.java
Labels: cleanup, breaking change, 1.21

#1154 `SpawnPlacementRegisterEvent` -> `RegisterSpawnPlacementsEvent`
  patches/net/minecraft/world/entity/SpawnPlacements.java.patch
  src/main/java/net/neoforged/neoforge/event/entity/RegisterSpawnPlacementsEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/living/MobSpawnEvent.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/entity/SpawnPlacementTest.java
Labels: cleanup, breaking change, 1.21

#862 [1.21] Select Music Event
  patches/net/minecraft/client/sounds/MusicManager.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/SelectMusicEvent.java
Labels: enhancement, 1.21

#1150 Allow null player for UseItemOnBlockEvent
  patches/net/minecraft/world/item/ItemStack.java.patch
  src/main/java/net/neoforged/neoforge/event/entity/player/UseItemOnBlockEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/data/DataMapTests.java
Labels: enhancement, 1.21

#1210 Added Badlands and Wooded badlands to hot tag
  src/generated/resources/data/c/tags/worldgen/biome/is_hot/overworld.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBiomeTagsProvider.java
Labels: bug, 1.21

#1226 Add common Mace tag
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/item/tools/mace.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: enhancement, 1.21

#1238 Several tag fixes and additions
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/block/glass_blocks.json
  src/generated/resources/data/c/tags/item/foods.json
  src/generated/resources/data/c/tags/item/foods/berries.json
  src/generated/resources/data/c/tags/item/foods/berry.json
  src/generated/resources/data/c/tags/item/foods/bread.json
  src/generated/resources/data/c/tags/item/foods/breads.json
  src/generated/resources/data/c/tags/item/foods/candies.json
  src/generated/resources/data/c/tags/item/foods/candy.json
  src/generated/resources/data/c/tags/item/foods/cooked_fish.json
  src/generated/resources/data/c/tags/item/foods/cooked_fishes.json
  src/generated/resources/data/c/tags/item/foods/cooked_meat.json
  src/generated/resources/data/c/tags/item/foods/cookie.json
  src/generated/resources/data/c/tags/item/foods/cookies.json
  src/generated/resources/data/c/tags/item/foods/fruit.json
  src/generated/resources/data/c/tags/item/foods/fruits.json
  src/generated/resources/data/c/tags/item/foods/golden.json
  src/generated/resources/data/c/tags/item/foods/raw_fish.json
  src/generated/resources/data/c/tags/item/foods/raw_fishes.json
  src/generated/resources/data/c/tags/item/foods/raw_meat.json
  src/generated/resources/data/c/tags/item/foods/soup.json
  src/generated/resources/data/c/tags/item/foods/vegetable.json
  src/generated/resources/data/c/tags/item/glass_blocks.json
  src/generated/resources/data/c/tags/item/tools.json
  src/generated/resources/data/c/tags/item/tools/igniter.json
  src/main/java/net/neoforged/neoforge/common/TagConventionLogWarning.java
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: bug, enhancement, breaking change, 1.21

#1147 Annotation marker fixes, javadoc cleanup, and LivingChangeTargetEvent methods renamed
  patches/com/mojang/blaze3d/pipeline/RenderTarget.java.patch
  patches/net/minecraft/client/KeyMapping.java.patch
  patches/net/minecraft/client/gui/Gui.java.patch
  patches/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
  patches/net/minecraft/client/renderer/RenderType.java.patch
  patches/net/minecraft/client/renderer/entity/layers/ElytraLayer.java.patch
  patches/net/minecraft/client/renderer/texture/TextureAtlasSprite.java.patch
  patches/net/minecraft/client/resources/sounds/SoundInstance.java.patch
  patches/net/minecraft/client/server/LanServerPinger.java.patch
  patches/net/minecraft/core/Holder.java.patch
  patches/net/minecraft/data/DataProvider.java.patch
  patches/net/minecraft/locale/Language.java.patch
  patches/net/minecraft/network/chat/SignableCommand.java.patch
  patches/net/minecraft/resources/HolderSetCodec.java.patch
  patches/net/minecraft/server/MinecraftServer.java.patch
  patches/net/minecraft/server/level/Ticket.java.patch
  patches/net/minecraft/world/damagesource/DamageEffects.java.patch
  patches/net/minecraft/world/damagesource/DamageScaling.java.patch
  patches/net/minecraft/world/damagesource/DeathMessageType.java.patch
  patches/net/minecraft/world/effect/MobEffect.java.patch
  patches/net/minecraft/world/entity/Entity.java.patch
  patches/net/minecraft/world/entity/LivingEntity.java.patch
  patches/net/minecraft/world/entity/Mob.java.patch
  patches/net/minecraft/world/entity/SpawnPlacements.java.patch
  patches/net/minecraft/world/entity/ai/behavior/StartAttacking.java.patch
  patches/net/minecraft/world/entity/player/Player.java.patch
  patches/net/minecraft/world/entity/vehicle/AbstractMinecart.java.patch
  patches/net/minecraft/world/item/FishingRodItem.java.patch
  patches/net/minecraft/world/item/Item.java.patch
  patches/net/minecraft/world/item/ShieldItem.java.patch
  patches/net/minecraft/world/item/component/ItemContainerContents.java.patch
  patches/net/minecraft/world/level/ForcedChunksSavedData.java.patch
  patches/net/minecraft/world/level/biome/Biome.java.patch
  patches/net/minecraft/world/level/block/Block.java.patch
  patches/net/minecraft/world/level/block/FlowerPotBlock.java.patch
  patches/net/minecraft/world/level/block/TrapDoorBlock.java.patch
  patches/net/minecraft/world/level/block/state/BlockBehaviour.java.patch
  patches/net/minecraft/world/level/chunk/ChunkAccess.java.patch
  patches/net/minecraft/world/level/chunk/LevelChunk.java.patch
  patches/net/minecraft/world/level/levelgen/placement/EnvironmentScanPlacement.java.patch
  patches/net/minecraft/world/level/levelgen/structure/Structure.java.patch
  patches/net/minecraft/world/level/storage/loot/LootContext.java.patch
  patches/net/minecraft/world/level/storage/loot/LootPool.java.patch
  patches/net/minecraft/world/level/storage/loot/LootTable.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockStateExtension.java
  src/main/java/net/neoforged/neoforge/common/world/ModifiableStructureInfo.java
  src/main/java/net/neoforged/neoforge/event/entity/living/LivingChangeTargetEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/player/UseItemOnBlockEvent.java
  src/main/java/net/neoforged/neoforge/fluids/FluidType.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/living/LivingEntityEventTests.java
Labels: cleanup, breaking change, 1.21

#1220 Add methods to convert payloads to vanilla packets
  patches/net/minecraft/network/protocol/common/custom/CustomPacketPayload.java.patch
Labels: enhancement, 1.21, networking

#1255 Fix before/after method ordering for BuildCreativeModeTabContentsEvent
  src/main/java/net/neoforged/neoforge/event/BuildCreativeModeTabContentsEvent.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/CreativeTabOrderTest.java
Labels: bug, 1.21

#1261 Remove deprecation on `Block#BLOCK_STATE_REGISTRY`
  patches/net/minecraft/world/level/block/Block.java.patch
Labels: cleanup, 1.21

#1246 [1.21] Update documentation for the Creative Flight attribute
  src/main/java/net/neoforged/neoforge/common/BooleanAttribute.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
Labels: cleanup, 1.21

#1268 [1.21] Fix LiquidBlockRenderer checking wrong overlay texture
  patches/net/minecraft/client/renderer/block/LiquidBlockRenderer.java.patch
Labels: bug, 1.21

#991 [1.21] Add `ICustomHolderSet` support for `StreamCodec` created from `ByteBufCodecs#holderSet`
  patches/net/minecraft/network/codec/ByteBufCodecs.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/registries/NeoForgeRegistries.java
  src/main/java/net/neoforged/neoforge/registries/holdersets/AndHolderSet.java
  src/main/java/net/neoforged/neoforge/registries/holdersets/AnyHolderSet.java
  src/main/java/net/neoforged/neoforge/registries/holdersets/HolderSetType.java
  src/main/java/net/neoforged/neoforge/registries/holdersets/NotHolderSet.java
  src/main/java/net/neoforged/neoforge/registries/holdersets/OrHolderSet.java
  tests/src/main/java/net/neoforged/neoforge/debug/registries/HolderSetTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/registries/package-info.java
Labels: regression, breaking change, 1.21, networking

#1239 Update NightConfig and cleanup config code
  gradle.properties
  src/main/java/net/neoforged/neoforge/client/command/ClientConfigCommand.java
  src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java
  src/main/java/net/neoforged/neoforge/network/ConfigSync.java
  src/main/java/net/neoforged/neoforge/network/configuration/SyncConfig.java
  src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java
  src/main/java/net/neoforged/neoforge/server/command/ConfigCommand.java
Labels: cleanup, breaking change, 1.21

#689 Add error if spawn placements are missing for entities that spawn in-world
  patches/net/minecraft/world/entity/SpawnPlacements.java.patch
  src/main/java/net/neoforged/neoforge/server/ServerLifecycleHooks.java
Labels: enhancement, 1.21

#1253 Add `c:tools/melee_weapon`, `c:tools/ranged_weapon`, and `c:tools/mining_tool` tool tags
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/item/tools.json
  src/generated/resources/data/c/tags/item/tools/melee_weapon.json
  src/generated/resources/data/c/tags/item/tools/mining_tool.json
  src/generated/resources/data/c/tags/item/tools/ranged_weapon.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: enhancement, 1.21

#1256 Allow SpecialPlantable's spawnPlantAtPosition to set blocks in world
  src/main/java/net/neoforged/neoforge/common/SpecialPlantable.java
Labels: bug, breaking change, 1.21

#1270 AT pattern fields in ShapedRecipe class
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, 1.21

#1295 Make BooleanAttribute public
  src/main/java/net/neoforged/neoforge/common/BooleanAttribute.java
Labels: bug, 1.21

#1290 Fix format specifiers in chunkgen messages
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: bug, 1.21

#1296 Run CapabilityHooks::registerVanillaProviders at LOW priority
  src/main/java/net/neoforged/neoforge/capabilities/CapabilityHooks.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
Labels: bug, 1.21

#1299 Fix mod added Villager Trades failing serialization
  src/main/java/net/neoforged/neoforge/common/BasicItemListing.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/TradeTests.java
Labels: bug, 1.21

#1248 [1.21] Fix firing point for ItemStackedOnOtherEvent
  patches/net/minecraft/world/inventory/AbstractContainerMenu.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
Labels: cleanup, 1.21

#1219 Add Item Abilities for lighting and dowsing
  patches/net/minecraft/core/dispenser/DispenseItemBehavior.java.patch
  patches/net/minecraft/world/item/FireChargeItem.java.patch
  patches/net/minecraft/world/item/FlintAndSteelItem.java.patch
  patches/net/minecraft/world/item/ShovelItem.java.patch
  src/main/java/net/neoforged/neoforge/common/ItemAbilities.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
Labels: enhancement, 1.21

#1228 Add `SHEARS_TRIM` item ability & Add dispenser support for `SHEARS_HARVEST` item ability and `IShearable`
  patches/net/minecraft/core/dispenser/ShearsDispenseItemBehavior.java.patch
  patches/net/minecraft/world/item/ShearsItem.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/ItemAbilities.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
Labels: enhancement, 1.21

#1306 Add DyeColor method for getting dyed items tag
  patches/net/minecraft/world/item/DyeColor.java.patch
Labels: enhancement, 1.21

#1297 [1.21] Include component and stack data when Itemstack#save and Fluidstack#save throws from codec errors
  patches/net/minecraft/world/item/ItemStack.java.patch
  src/main/java/net/neoforged/neoforge/common/util/DataComponentUtil.java
  src/main/java/net/neoforged/neoforge/fluids/FluidStack.java
Labels: enhancement, 1.21

#1273 Make `Ingredient#getItems` and `FluidIngredient#getStacks` distinct
  patches/net/minecraft/world/item/crafting/Ingredient.java.patch
  src/main/java/net/neoforged/neoforge/fluids/FluidStackLinkedSet.java
  src/main/java/net/neoforged/neoforge/fluids/crafting/FluidIngredient.java
Labels: bug, 1.21

#1244 Add several more useful ATs to help out modders
  patches/net/minecraft/world/level/block/PoweredRailBlock.java.patch
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, 1.21

#1285 Load client and common configs earlier (now immediately after registries)
  src/main/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/main/java/net/neoforged/neoforge/data/loading/DatagenModLoader.java
  src/main/java/net/neoforged/neoforge/internal/CommonModLoader.java
  src/main/java/net/neoforged/neoforge/server/loading/ServerModLoader.java
Labels: enhancement, 1.21

#1283 Cleaned up ItemExpireEvent
  patches/net/minecraft/world/entity/item/ItemEntity.java.patch
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/entity/item/ItemExpireEvent.java
Labels: cleanup, breaking change, 1.21

#1252 New Crowdin updates
  src/main/resources/assets/neoforge/lang/da_dk.json
  src/main/resources/assets/neoforge/lang/de_de.json
  src/main/resources/assets/neoforge/lang/en_gb.json
  src/main/resources/assets/neoforge/lang/eo_uy.json
  src/main/resources/assets/neoforge/lang/es_es.json
  src/main/resources/assets/neoforge/lang/et_ee.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/hu_hu.json
  src/main/resources/assets/neoforge/lang/it_it.json
  src/main/resources/assets/neoforge/lang/ja_jp.json
  src/main/resources/assets/neoforge/lang/ko_kr.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/pt_br.json
  src/main/resources/assets/neoforge/lang/pt_pt.json
  src/main/resources/assets/neoforge/lang/ro_ro.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/sk_sk.json
  src/main/resources/assets/neoforge/lang/tr_tr.json
  src/main/resources/assets/neoforge/lang/tt_ru.json
  src/main/resources/assets/neoforge/lang/uk_ua.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_hk.json
Labels: l10n

#1311 [1.21] Move client extension registration to an event
  patches/net/minecraft/world/effect/MobEffect.java.patch
  patches/net/minecraft/world/item/Item.java.patch
  patches/net/minecraft/world/level/block/Block.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java
  src/main/java/net/neoforged/neoforge/client/extensions/common/ClientExtensionsManager.java
  src/main/java/net/neoforged/neoforge/client/extensions/common/IClientBlockExtensions.java
  src/main/java/net/neoforged/neoforge/client/extensions/common/IClientFluidTypeExtensions.java
  src/main/java/net/neoforged/neoforge/client/extensions/common/IClientItemExtensions.java
  src/main/java/net/neoforged/neoforge/client/extensions/common/IClientMobEffectExtensions.java
  src/main/java/net/neoforged/neoforge/client/extensions/common/RegisterClientExtensionsEvent.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/fluids/FluidType.java
  src/main/java/net/neoforged/neoforge/registries/GameData.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/block/CustomBreakSoundTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/client/CustomArmorModelTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/entity/player/ItemUseAnimationTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/fluid/FluidTypeTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/fluid/NewFluidTest.java
Labels: enhancement, loading, 1.21

#1332 [1.21] Fix circularity issue in RecipeBookSettings static init
  patches/net/minecraft/stats/RecipeBookSettings.java.patch
  patches/net/minecraft/world/inventory/RecipeBookType.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
Labels: bug, 1.21

#1072 Allow disabling text shadow in `EditBox`
  patches/net/minecraft/client/gui/components/EditBox.java.patch
Labels: enhancement

#1272 Add `ModifyCustomSpawnersEvent`
  patches/net/minecraft/server/level/ServerLevel.java.patch
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/level/ModifyCustomSpawnersEvent.java
Labels: enhancement, 1.21

#1199 Added configuration screen
  buildSrc/src/main/groovy/neoforge.formatting-conventions.gradle
  src/main/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java
  src/main/java/net/neoforged/neoforge/client/gui/ConfigurationScreen.java
  src/main/java/net/neoforged/neoforge/client/gui/IConfigScreenFactory.java
  src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java
  src/main/java/net/neoforged/neoforge/client/gui/widget/ModListWidget.java
  src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeConfig.java
  src/main/java/net/neoforged/neoforge/common/TranslatableEnum.java
  src/main/java/net/neoforged/neoforge/common/conditions/WithConditions.java
  src/main/java/net/neoforged/neoforge/common/crafting/CompoundIngredient.java
  src/main/java/net/neoforged/neoforge/common/crafting/IntersectionIngredient.java
  src/main/java/net/neoforged/neoforge/network/payload/AdvancedAddEntityPayload.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/DataMapEntry.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/Compostable.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/assets/neoforge/lang/en_us.json
  testframework/src/main/java/net/neoforged/testframework/condition/TestEnabledLootCondition.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/ConfigUITest.java
  tests/src/main/resources/META-INF/neoforge.mods.toml
  tests/src/main/resources/assets/configui/lang/en_us.json
Labels: enhancement, help wanted, 1.21

#1342 Fix capability nullness annotations
  patches/net/minecraft/world/entity/Entity.java.patch
  src/main/java/net/neoforged/neoforge/capabilities/BaseCapability.java
  src/main/java/net/neoforged/neoforge/capabilities/BlockCapability.java
  src/main/java/net/neoforged/neoforge/capabilities/BlockCapabilityCache.java
  src/main/java/net/neoforged/neoforge/capabilities/Capabilities.java
  src/main/java/net/neoforged/neoforge/capabilities/EntityCapability.java
  src/main/java/net/neoforged/neoforge/capabilities/IBlockCapabilityProvider.java
  src/main/java/net/neoforged/neoforge/capabilities/ICapabilityProvider.java
  src/main/java/net/neoforged/neoforge/capabilities/ItemCapability.java
  src/main/java/net/neoforged/neoforge/capabilities/RegisterCapabilitiesEvent.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/ILevelExtension.java
  testframework/src/main/java/net/neoforged/testframework/gametest/ExtendedGameTestHelper.java
Labels: 1.21

#1298 Add back int cast on entity pathfinding
  patches/net/minecraft/world/entity/ai/navigation/PathNavigation.java.patch
Labels: 1.21, vanilla bug

#1352 [1.21] Add the `applyEnchantments` hook
  patches/net/minecraft/world/inventory/EnchantmentMenu.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
Labels: enhancement, 1.21

#1359 Modify default components during data generation mod loading
  src/main/java/net/neoforged/neoforge/data/loading/DatagenModLoader.java
  src/main/java/net/neoforged/neoforge/internal/RegistrationEvents.java
Labels: enhancement, loading, 1.21

#1361 Fixes for the Config UI
  src/main/java/net/neoforged/neoforge/client/gui/ConfigurationScreen.java
  src/main/resources/assets/neoforge/lang/en_us.json
  tests/src/main/java/net/neoforged/neoforge/oldtest/ConfigUITest.java
Labels: bug, enhancement, 1.21

#1358 [1.21] Add ATs needed to support custom enchantments
  patches/net/minecraft/world/item/enchantment/EnchantmentHelper.java.patch
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, 1.21

#1356 Exclude trapped chests from chest only recipes in Neo's recipe replacements
  src/generated/resources/data/minecraft/recipe/acacia_chest_boat.json
  src/generated/resources/data/minecraft/recipe/bamboo_chest_raft.json
  src/generated/resources/data/minecraft/recipe/birch_chest_boat.json
  src/generated/resources/data/minecraft/recipe/cherry_chest_boat.json
  src/generated/resources/data/minecraft/recipe/chest_minecart.json
  src/generated/resources/data/minecraft/recipe/dark_oak_chest_boat.json
  src/generated/resources/data/minecraft/recipe/hopper.json
  src/generated/resources/data/minecraft/recipe/jungle_chest_boat.json
  src/generated/resources/data/minecraft/recipe/mangrove_chest_boat.json
  src/generated/resources/data/minecraft/recipe/oak_chest_boat.json
  src/generated/resources/data/minecraft/recipe/shulker_box.json
  src/generated/resources/data/minecraft/recipe/spruce_chest_boat.json
  src/generated/resources/data/minecraft/recipe/trapped_chest.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeRecipeProvider.java
Labels: bug, 1.21

#1353 Add missing Neo config gui translations
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: cleanup, 1.21

#1350 Fix modifier keys not correctly applying in keybind screen
  patches/net/minecraft/client/KeyboardHandler.java.patch
  patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch
  src/main/java/net/neoforged/neoforge/client/settings/KeyModifier.java
Labels: bug, 1.21

#1348 Add more melee weapons to melee tag, add `c:fertilizers` tag, and Sparse Jungle to Sparse tag
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/item/fertilizers.json
  src/generated/resources/data/c/tags/item/tools/melee_weapon.json
  src/generated/resources/data/c/tags/worldgen/biome/is_sparse_vegetation/overworld.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBiomeTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: bug, enhancement, 1.21

#1341 [1.21] Add more guards to fake players
  src/main/java/net/neoforged/neoforge/common/extensions/IPlayerExtension.java
  src/main/java/net/neoforged/neoforge/common/util/FakePlayer.java
Labels: bug, 1.21

#1310 [1.21] Reimplement custom map decoration renderers
  patches/net/minecraft/client/gui/MapRenderer.java.patch
  patches/net/minecraft/world/level/saveddata/maps/MapDecoration.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/gui/map/IMapDecorationRenderer.java
  src/main/java/net/neoforged/neoforge/client/gui/map/MapDecorationRendererManager.java
  src/main/java/net/neoforged/neoforge/client/gui/map/RegisterMapDecorationRenderersEvent.java
  src/main/resources/META-INF/accesstransformer.cfg
  tests/src/main/java/net/neoforged/neoforge/debug/client/MapDecorationRenderTests.java
Labels: enhancement, rendering, regression, 1.21

#1305 [1.21] Implement network checks for networked extensible enums
  gradle.properties
  patches/net/minecraft/stats/RecipeBookSettings.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/network/ConfigurationInitialization.java
  src/main/java/net/neoforged/neoforge/network/NetworkInitialization.java
  src/main/java/net/neoforged/neoforge/network/configuration/CheckExtensibleEnums.java
  src/main/java/net/neoforged/neoforge/network/payload/ExtensibleEnumAcknowledgePayload.java
  src/main/java/net/neoforged/neoforge/network/payload/ExtensibleEnumDataPayload.java
  src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, 1.21, networking

#1309 [1.21] Fix accessibility screen not getting shown when dismissing the loading warnings screen
  patches/net/minecraft/client/Minecraft.java.patch
  src/main/java/net/neoforged/neoforge/client/gui/LoadingErrorScreen.java
  src/main/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/main/java/net/neoforged/neoforge/data/loading/DatagenModLoader.java
  src/main/java/net/neoforged/neoforge/internal/CommonModLoader.java
  src/main/java/net/neoforged/neoforge/server/loading/ServerModLoader.java
Labels: bug, loading, 1.21

#1318 Made day time flow variable
  patches/net/minecraft/client/multiplayer/ClientLevel.java.patch
  patches/net/minecraft/server/MinecraftServer.java.patch
  patches/net/minecraft/server/level/ServerLevel.java.patch
  patches/net/minecraft/server/players/PlayerList.java.patch
  patches/net/minecraft/world/entity/player/Player.java.patch
  patches/net/minecraft/world/level/Level.java.patch
  patches/net/minecraft/world/level/storage/DerivedLevelData.java.patch
  patches/net/minecraft/world/level/storage/PrimaryLevelData.java.patch
  patches/net/minecraft/world/level/storage/ServerLevelData.java.patch
  src/main/java/net/neoforged/neoforge/network/NetworkInitialization.java
  src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java
  src/main/java/net/neoforged/neoforge/network/payload/ClientboundCustomSetTimePayload.java
  src/main/java/net/neoforged/neoforge/server/command/NeoForgeCommand.java
  src/main/java/net/neoforged/neoforge/server/command/TimeSpeedCommand.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, 1.21

#1292 [1.21] Make Boat.Type enum extensible
  patches/net/minecraft/client/model/geom/LayerDefinitions.java.patch
  patches/net/minecraft/client/model/geom/ModelLayers.java.patch
  patches/net/minecraft/client/renderer/entity/BoatRenderer.java.patch
  patches/net/minecraft/world/entity/vehicle/Boat.java.patch
  patches/net/minecraft/world/entity/vehicle/ChestBoat.java.patch
  tests/src/generated/resources/assets/neotests_custom_boat_type/lang/en_us.json
  tests/src/main/java/net/neoforged/neoforge/debug/entity/vehicle/CustomBoatTest.java
  tests/src/main/resources/META-INF/enumextensions.json
Labels: enhancement, 1.21

#1368 Check formatting local changes
  .github/workflows/check-local-changes.yml
  src/main/java/net/neoforged/neoforge/client/gui/map/package-info.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/vehicle/package-info.java
Labels: cleanup, 1.21, ci/build

#1362 Add `SlotItemHandlerImmutable` to allow `ComponentItemHandler` to work with vanilla `AbstractContainerMenu` methods
  src/main/java/net/neoforged/neoforge/items/ComponentItemHandler.java
  src/main/java/net/neoforged/neoforge/items/ItemHandlerCopySlot.java
  src/main/java/net/neoforged/neoforge/items/SlotItemHandler.java
  src/main/java/net/neoforged/neoforge/items/StackCopySlot.java
Labels: bug, enhancement, 1.21

#1370 Fix AO shadows being computed wrongly (MC-43968)
  patches/net/minecraft/client/renderer/block/ModelBlockRenderer.java.patch
Labels: bug, 1.21, vanilla bug

#1365 Add ClientInformationUpdatedEvent
  patches/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
  src/main/java/net/neoforged/neoforge/event/entity/player/ClientInformationUpdatedEvent.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/entity/player/ClientInformationUpdatedTest.java
  tests/src/main/resources/META-INF/neoforge.mods.toml
Labels: enhancement, 1.21

#1324 Moved onLivingDamagePre to be before absorption logic
  patches/net/minecraft/world/entity/LivingEntity.java.patch
  patches/net/minecraft/world/entity/player/Player.java.patch
  src/main/java/net/neoforged/neoforge/common/damagesource/DamageContainer.java
  src/main/java/net/neoforged/neoforge/event/entity/living/LivingDamageEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/living/LivingEntityEventTests.java
Labels: enhancement, breaking change, 1.21

#1382 Restore CustomizeGuiOverlayEvent.DebugText's ability to modify text
  patches/net/minecraft/client/gui/components/DebugScreenOverlay.java.patch
Labels: bug, breaking change, 1.21

#1284 Respect `needsWorldRestart` and add `needsGameRestart`
  gradle.properties
  src/main/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java
  src/main/java/net/neoforged/neoforge/client/gui/ConfigurationScreen.java
  src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/resources/assets/neoforge/lang/en_us.json
  tests/src/main/java/net/neoforged/neoforge/oldtest/ConfigUITest.java
Labels: bug, enhancement, breaking change, 1.21

#1379 Use `RegistryOps` for DataMap sync
  src/main/java/net/neoforged/neoforge/network/payload/RegistryDataMapSyncPayload.java
Labels: enhancement, 1.21, networking, data driven

#1395 Fix versions in changelog
  build.gradle
  buildSrc/src/main/groovy/neoforge.versioning.gradle
  projects/neoforge/build.gradle
Labels: bug, 1.21, ci/build

#1386 Fix section button text being looked up by config key instead of translation key
  src/main/java/net/neoforged/neoforge/client/gui/ConfigurationScreen.java
Labels: bug, 1.21
