Repository neoforged/NeoForge, pull requests merged in 2024-12, with the labels that each got.

#1735 Patch `Ingredient#isEmpty` for custom ingredients
  patches/net/minecraft/world/item/crafting/Ingredient.java.patch
Labels: bug, 1.21.4

#554 Allow running client commands from chat components
  patches/net/minecraft/client/multiplayer/ClientPacketListener.java.patch
Labels: enhancement, 1.20

#1739 Do not attempt to format mod description contents
  src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java
  tests/src/main/resources/META-INF/neoforge.mods.toml
  tests/src/main/resources/assets/neotests/lang/fr_fr.json
Labels: bug, regression, 1.21.4

#974 Implement synced registry check in holder stream codec
  patches/net/minecraft/network/codec/ByteBufCodecs.java.patch
Labels: enhancement, networking, 1.21.4

#1719 Add task to generate ats
  .github/workflows/check-local-changes.yml
  buildSrc/build.gradle
  buildSrc/src/main/java/net/neoforged/neodev/ApplyAccessTransformer.java
  buildSrc/src/main/java/net/neoforged/neodev/GenerateAccessTransformers.java
  buildSrc/src/main/java/net/neoforged/neodev/NeoDevPlugin.java
  buildSrc/src/main/java/net/neoforged/neodev/utils/SerializablePredicate.java
  buildSrc/src/main/java/net/neoforged/neodev/utils/structure/ClassInfo.java
  buildSrc/src/main/java/net/neoforged/neodev/utils/structure/ClassStructureVisitor.java
  buildSrc/src/main/java/net/neoforged/neodev/utils/structure/FieldInfo.java
  buildSrc/src/main/java/net/neoforged/neodev/utils/structure/MethodInfo.java
  projects/neoforge/build.gradle
  settings.gradle
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/META-INF/accesstransformergenerated.cfg
  src/main/resources/META-INF/neoforge.mods.toml
Labels: cleanup, ci/build, 1.21.3

#1589 Only load resources once for gametest servers
  patches/net/minecraft/server/Main.java.patch
  tests/src/generated/resources/data/neotests_reloadable_reg_data_maps/data_maps/loot_table/effect_grant.json
  tests/src/main/java/net/neoforged/neoforge/debug/data/DataMapTests.java
Labels: bug, backport, 1.21.1

#1751 Add getter for baked standalone models
  patches/net/minecraft/client/resources/model/ModelManager.java.patch
Labels: bug, 1.21.4

#1732 [1.21.4] Fix a couple model and model loader issues
  patches/net/minecraft/client/renderer/block/model/BlockModel.java.patch
  patches/net/minecraft/client/renderer/item/BlockModelWrapper.java.patch
  src/main/java/net/neoforged/neoforge/client/model/AbstractUnbakedModel.java
  src/main/java/net/neoforged/neoforge/client/model/NeoForgeModelProperties.java
  src/main/java/net/neoforged/neoforge/client/model/StandardModelParameters.java
  src/main/java/net/neoforged/neoforge/client/model/UnbakedCompositeModel.java
  src/main/java/net/neoforged/neoforge/client/model/generators/loaders/CompositeModelBuilder.java
  src/main/java/net/neoforged/neoforge/client/model/obj/ObjLoader.java
  src/main/java/net/neoforged/neoforge/client/model/obj/ObjModel.java
  src/main/java/net/neoforged/neoforge/client/model/obj/ObjTokenizer.java
Labels: bug, rendering, 1.21.4

#1748 Rename isRepairable to isCombineRepairable and make it not reliant on Repairable Data Component
  patches/net/minecraft/world/inventory/GrindstoneMenu.java.patch
  patches/net/minecraft/world/item/Item.java.patch
  patches/net/minecraft/world/item/crafting/RepairItemRecipe.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
Labels: bug, 1.21.4

#1759 fix: obj loader not rendering parts with the same name [1.21.4]
  src/main/java/net/neoforged/neoforge/client/model/obj/ObjModel.java
  tests/src/generated/resources/assets/new_model_loader_test/blockstates/obj_block_same_part_names.json
  tests/src/generated/resources/assets/new_model_loader_test/models/block/obj_block_same_part_names.json
  tests/src/main/java/net/neoforged/neoforge/oldtest/client/model/NewModelLoaderTest.java
  tests/src/main/resources/assets/new_model_loader_test/models/item/sugar_glider_same_part_names.obj
Labels: bug, 1.21.4

#1760 fix: obj loader not rendering parts with the same name [1.21.1]
  src/main/java/net/neoforged/neoforge/client/model/obj/ObjModel.java
  tests/src/generated/resources/assets/new_model_loader_test/blockstates/obj_block_same_part_names.json
  tests/src/generated/resources/assets/new_model_loader_test/models/block/obj_block_same_part_names.json
  tests/src/main/java/net/neoforged/neoforge/oldtest/client/model/NewModelLoaderTest.java
  tests/src/main/resources/assets/new_model_loader_test/models/item/sugar_glider_same_part_names.obj
Labels: bug, backport, 1.21.1

#1763 [1.21.1] Allow changing datagen indent width
  patches/net/minecraft/data/DataProvider.java.patch
Labels: enhancement, backport, 1.21.1

#1764 [1.21.1] Fix certain percentage attributes being displayed wrong
  src/main/java/net/neoforged/neoforge/common/PercentageAttribute.java
Labels: bug, backport, 1.21.1

#1757 Stop FileWatcher default instance on dedicated server exit
  patches/net/minecraft/server/dedicated/DedicatedServer.java.patch
Labels: bug, 1.21.4

#1762 Stop FileWatcher default instance on dedicated server exit
  patches/net/minecraft/server/dedicated/DedicatedServer.java.patch
Labels: bug, backport, 1.21.1

#1662 New Crowdin updates
  src/main/resources/assets/neoforge/lang/cs_cz.json
  src/main/resources/assets/neoforge/lang/da_dk.json
  src/main/resources/assets/neoforge/lang/de_de.json
  src/main/resources/assets/neoforge/lang/en_gb.json
  src/main/resources/assets/neoforge/lang/eo_uy.json
  src/main/resources/assets/neoforge/lang/es_es.json
  src/main/resources/assets/neoforge/lang/et_ee.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/hu_hu.json
  src/main/resources/assets/neoforge/lang/it_it.json
  src/main/resources/assets/neoforge/lang/ja_jp.json
  src/main/resources/assets/neoforge/lang/ko_kr.json
  src/main/resources/assets/neoforge/lang/ms_my.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/pt_br.json
  src/main/resources/assets/neoforge/lang/pt_pt.json
  src/main/resources/assets/neoforge/lang/ro_ro.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/sk_sk.json
  src/main/resources/assets/neoforge/lang/tr_tr.json
  src/main/resources/assets/neoforge/lang/tt_ru.json
  src/main/resources/assets/neoforge/lang/uk_ua.json
  src/main/resources/assets/neoforge/lang/vi_vn.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_tw.json
Labels: l10n

#1756 Add task to generate finalizeSpawn MethodRedirector coremod targets
  .github/workflows/check-local-changes.yml
  buildSrc/src/main/java/net/neoforged/neodev/GenerateFinalizeSpawnTargets.java
  buildSrc/src/main/java/net/neoforged/neodev/utils/AsmUtils.java
  buildSrc/src/main/java/net/neoforged/neodev/utils/structure/ClassStructureVisitor.java
  coremods/src/main/resources/net/neoforged/neoforge/coremods/finalize_spawn_targets.json
  projects/neoforge/build.gradle
Labels: bug, ci/build, 1.21.4

#1716 [1.21.4] Encourage more usage of IConditionBuider
  patches/net/minecraft/server/ReloadableServerResources.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/conditions/AlwaysCondition.java
  src/main/java/net/neoforged/neoforge/common/conditions/ConditionContext.java
  src/main/java/net/neoforged/neoforge/common/conditions/FeatureFlagsEnabledCondition.java
  src/main/java/net/neoforged/neoforge/common/conditions/ICondition.java
  src/main/java/net/neoforged/neoforge/common/conditions/IConditionBuilder.java
  src/main/java/net/neoforged/neoforge/common/conditions/ItemExistsCondition.java
  src/main/java/net/neoforged/neoforge/common/conditions/NeoForgeConditions.java
  src/main/java/net/neoforged/neoforge/common/conditions/NeverCondition.java
  src/main/java/net/neoforged/neoforge/common/conditions/RegisteredCondition.java
  src/main/java/net/neoforged/neoforge/common/conditions/TagEmptyCondition.java
  src/main/java/net/neoforged/neoforge/common/data/JsonCodecProvider.java
  tests/src/generated/resources/data/data_gen_test/advancement/recipes/building_blocks/conditional.json
  tests/src/generated/resources/data/data_gen_test/advancement/recipes/building_blocks/conditional2.json
  tests/src/generated/resources/data/data_gen_test/recipe/conditional.json
  tests/src/generated/resources/data/data_gen_test/recipe/conditional2.json
  tests/src/generated/resources/data/neotests_conditional_datapack_entries/damage_type/conditional_false.json
  tests/src/generated/resources/data/neotests_conditional_datapack_entries/damage_type/conditional_true.json
  tests/src/generated/resources/data/neotests_test_conditional_recipe/advancement/recipes/misc/always_disabled_recipe.json
  tests/src/generated/resources/data/neotests_test_conditional_recipe/recipe/always_disabled_recipe.json
  tests/src/main/java/net/neoforged/neoforge/debug/ConditionalRecipeTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/data/CustomFeatureFlagsTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/data/registries/DatapackEntryTests.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/DataGeneratorTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/conditions/ConditionalCodecTest.java
Labels: 1.21.4

#1767 Add nether woods to stripped tags
  src/generated/resources/data/c/tags/block/stripped_logs.json
  src/generated/resources/data/c/tags/block/stripped_woods.json
  src/generated/resources/data/c/tags/item/stripped_logs.json
  src/generated/resources/data/c/tags/item/stripped_woods.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
Labels: enhancement, 1.21.4

#1530 Switch out spotless for an alternative
  build.gradle
  buildSrc/src/main/groovy/neoforge.formatting-conventions.gradle
  coremods/build.gradle
  docs/CONTRIBUTING.md
  testframework/build.gradle
  tests/build.gradle
Labels: enhancement, ci/build

#1738 Fix chunk force ticking
  patches/net/minecraft/server/level/ChunkMap.java.patch
  patches/net/minecraft/server/level/DistanceManager.java.patch
  patches/net/minecraft/server/level/ServerChunkCache.java.patch
Labels: bug, regression, 1.21.4

#1769 Remove now-unused BakedModel return from applyTransform
  patches/net/minecraft/client/renderer/item/ItemStackRenderState.java.patch
  patches/net/minecraft/client/resources/model/DelegateBakedModel.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/extensions/IBakedModelExtension.java
Labels: enhancement, breaking change, 1.21.4

#1673 [1.21.4] Fix BlockParticleOption#pos not getting sent to the client
  patches/net/minecraft/core/particles/BlockParticleOption.java.patch
  patches/net/minecraft/world/entity/Entity.java.patch
  patches/net/minecraft/world/entity/LivingEntity.java.patch
Labels: bug, rendering, breaking change, 1.21.4

#1783 Fix NeoForge fluid ingredient types not being registered
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/fluids/crafting/FluidIngredientCodecs.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/FluidIngredientTests.java
Labels: bug, 1.21.4

#1778 [1.21.x] Move firing point of ChunkEvent$Unload to after chunk save
  patches/net/minecraft/server/level/ChunkMap.java.patch
  src/main/java/net/neoforged/neoforge/event/level/ChunkDataEvent.java
  src/main/java/net/neoforged/neoforge/event/level/ChunkEvent.java
Labels: bug, cleanup, breaking change, 1.21.4

#1782 [1.20.4] Enable Gradle module metadata
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  projects/neoforge/build.gradle
  testframework/build.gradle
  tests/build.gradle
Labels: enhancement, ci/build, 1.20.4

#1785 Add immaculate rule that forbits @NotNull in patches
  build.gradle
  patches/net/minecraft/client/resources/model/MultiPartBakedModel.java.patch
Labels: 1.21.4

#1740 [1.21.4] Fix armor property copying and tintable armor rendering
  patches/net/minecraft/client/renderer/entity/layers/EquipmentLayerRenderer.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/extensions/common/IClientItemExtensions.java
Labels: bug, rendering, 1.21.4

#1736 Fire `TagsUpdatedEvent` on the client side after joining a server
  patches/net/minecraft/client/multiplayer/ClientConfigurationPacketListenerImpl.java.patch
Labels: bug, regression, networking, 1.21.4

#1789 [1.21.4] Log warning for missing item models
  patches/net/minecraft/client/resources/model/ModelManager.java.patch
Labels: enhancement, 1.21.4

#1777 [1.21.4] Add event for registering custom special block model renderers
  patches/net/minecraft/client/renderer/special/SpecialModelRenderers.java.patch
  src/main/java/net/neoforged/neoforge/client/event/RegisterSpecialBlockModelRendererEvent.java
Labels: enhancement, rendering, 1.21.4

#1730 [1.21.4] Allow modded BE and Entity types to declare that they have NBT data only OPs can set
  patches/net/minecraft/world/entity/EntityType.java.patch
  patches/net/minecraft/world/level/block/entity/BlockEntityType.java.patch
Labels: enhancement, 1.21.4

#1731 [1.21.4] Remove custom scrollable ExperimentsScreen
  patches/net/minecraft/client/gui/screens/worldselection/ExperimentsScreen.java.patch
  src/main/java/net/neoforged/neoforge/client/gui/ScrollableExperimentsScreen.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: bug, cleanup, 1.21.4

#1598 [1.21.4] Add event fired at the start of the framegraph setup
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/FrameGraphSetupEvent.java
Labels: rendering, 1.21.4

#1677 Add registry context to `LootTableLoadEvent`
  patches/net/minecraft/server/ReloadableServerRegistries.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/LootTableLoadEvent.java
  src/main/resources/META-INF/accesstransformer.cfg
  tests/src/main/java/net/neoforged/neoforge/debug/loot/LootPoolTest.java
Labels: enhancement, data driven, 1.21.4

#1628 [1.21.4] Sync remaining `c` tags from Fabric side
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/block/storage_blocks.json
  src/generated/resources/data/c/tags/block/storage_blocks/resin.json
  src/generated/resources/data/c/tags/block/stripped_logs.json
  src/generated/resources/data/c/tags/block/stripped_woods.json
  src/generated/resources/data/c/tags/entity_type/boats.json
  src/generated/resources/data/c/tags/item/bricks.json
  src/generated/resources/data/c/tags/item/bricks/resin.json
  src/generated/resources/data/c/tags/item/clumps.json
  src/generated/resources/data/c/tags/item/clumps/resin.json
  src/generated/resources/data/c/tags/item/potions.json
  src/generated/resources/data/c/tags/item/potions/bottle.json
  src/generated/resources/data/c/tags/item/seeds.json
  src/generated/resources/data/c/tags/item/seeds/torchflower.json
  src/generated/resources/data/c/tags/item/storage_blocks.json
  src/generated/resources/data/c/tags/item/storage_blocks/resin.json
  src/generated/resources/data/c/tags/item/stripped_logs.json
  src/generated/resources/data/c/tags/item/stripped_woods.json
  src/generated/resources/data/c/tags/worldgen/biome/is_cold.json
  src/generated/resources/data/c/tags/worldgen/biome/is_dark_forest.json
  src/generated/resources/data/c/tags/worldgen/biome/is_dense_vegetation.json
  src/generated/resources/data/c/tags/worldgen/biome/is_hot.json
  src/generated/resources/data/c/tags/worldgen/biome/is_hot/overworld.json
  src/generated/resources/data/c/tags/worldgen/biome/is_rare.json
  src/generated/resources/data/c/tags/worldgen/biome/is_sparse_vegetation.json
  src/generated/resources/data/c/tags/worldgen/biome/is_spooky.json
  src/generated/resources/data/c/tags/worldgen/biome/is_temperate.json
  src/generated/resources/data/c/tags/worldgen/biome/is_temperate/end.json
  src/generated/resources/data/c/tags/worldgen/biome/is_temperate/nether.json
  src/generated/resources/data/c/tags/worldgen/biome/is_temperate/overworld.json
  src/generated/resources/data/c/tags/worldgen/biome/is_tree/deciduous.json
  src/generated/resources/data/c/tags/worldgen/biome/is_wet.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBiomeTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeEntityTypeTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: 1.21.4

#1509 New Crowdin updates
  src/main/resources/assets/neoforge/lang/cs_cz.json
  src/main/resources/assets/neoforge/lang/ms_my.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/pt_br.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/sk_sk.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_tw.json
Labels: l10n

#1791 Remove RenderSystem.activeTexture calls in ParticleEngine
  patches/net/minecraft/client/particle/ParticleEngine.java.patch
Labels: rendering, cleanup, 1.21.4

#1804 Fix index in `ItemHandlerCopySlot#setStackCopy`
  src/main/java/net/neoforged/neoforge/items/ItemHandlerCopySlot.java
Labels: bug, 1.21.4

#1802 [1.21.4] Reintroduce nested models in composite models
  src/main/java/net/neoforged/neoforge/client/model/UnbakedCompositeModel.java
  src/main/java/net/neoforged/neoforge/client/model/generators/loaders/CompositeModelBuilder.java
Labels: rendering, regression, 1.21.4

#1798 Do not fail tag datagen when removing IDs not present at runtime
  patches/net/minecraft/data/tags/TagsProvider.java.patch
  tests/src/generated/resources/data/minecraft/tags/block/test_tag.json
  tests/src/main/java/net/neoforged/neoforge/oldtest/RemoveTagDatagenTest.java
Labels: enhancement, 1.21.1

#1805 Fix index in `ItemHandlerCopySlot#setStackCopy`
  src/main/java/net/neoforged/neoforge/items/ItemHandlerCopySlot.java
  tests/src/generated/resources/data/neotests_reloadable_reg_data_maps/data_maps/loot_table/effect_grant.json
  tests/src/main/java/net/neoforged/neoforge/debug/data/DataMapTests.java
Labels: bug, 1.21.1

#1799 [1.21.4] Tear out `ExistingFileHelper`
  patches/net/minecraft/client/data/Main.java.patch
  patches/net/minecraft/data/Main.java.patch
  patches/net/minecraft/data/advancements/AdvancementProvider.java.patch
  patches/net/minecraft/data/tags/BannerPatternTagsProvider.java.patch
  patches/net/minecraft/data/tags/BiomeTagsProvider.java.patch
  patches/net/minecraft/data/tags/CatVariantTagsProvider.java.patch
  patches/net/minecraft/data/tags/DamageTypeTagsProvider.java.patch
  patches/net/minecraft/data/tags/EnchantmentTagsProvider.java.patch
  patches/net/minecraft/data/tags/EntityTypeTagsProvider.java.patch
  patches/net/minecraft/data/tags/FlatLevelGeneratorPresetTagsProvider.java.patch
  patches/net/minecraft/data/tags/FluidTagsProvider.java.patch
  patches/net/minecraft/data/tags/GameEventTagsProvider.java.patch
  patches/net/minecraft/data/tags/InstrumentTagsProvider.java.patch
  patches/net/minecraft/data/tags/IntrinsicHolderTagsProvider.java.patch
  patches/net/minecraft/data/tags/ItemTagsProvider.java.patch
  patches/net/minecraft/data/tags/PaintingVariantTagsProvider.java.patch
  patches/net/minecraft/data/tags/PoiTypeTagsProvider.java.patch
  patches/net/minecraft/data/tags/StructureTagsProvider.java.patch
  patches/net/minecraft/data/tags/TagsProvider.java.patch
  patches/net/minecraft/data/tags/WorldPresetTagsProvider.java.patch
  src/generated/resources/data/neoforge/tags/damage_type/is_poison.json
  src/main/java/net/neoforged/neoforge/common/data/AdvancementProvider.java
  src/main/java/net/neoforged/neoforge/common/data/BlockTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/ExistingFileHelper.java
  src/main/java/net/neoforged/neoforge/common/data/JsonCodecProvider.java
  src/main/java/net/neoforged/neoforge/common/data/ParticleDescriptionProvider.java
  src/main/java/net/neoforged/neoforge/common/data/SoundDefinitionsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/SpriteSourceProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeAdvancementProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBiomeTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeDamageTypeTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeEnchantmentTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeEntityTypeTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeFluidTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeSpriteSourceProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeStructureTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/VanillaSoundDefinitionsProvider.java
  src/main/java/net/neoforged/neoforge/common/extensions/IAdvancementBuilderExtension.java
  src/main/java/net/neoforged/neoforge/data/event/GatherDataEvent.java
  src/main/java/net/neoforged/neoforge/data/loading/DatagenModLoader.java
  testframework/src/main/java/net/neoforged/testframework/impl/reg/RegistrationHelperImpl.java
  tests/build.gradle
  tests/src/main/java/net/neoforged/neoforge/debug/entity/player/AdvancementTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/resources/ModDatapackTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/DataGeneratorTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/RemoveTagDatagenTest.java
Labels: cleanup, breaking change, 1.21.4
