Repository neoforged/NeoForge, pull requests merged in 2024-09, with the labels that each got.

#1110 New Crowdin updates
  src/main/resources/assets/neoforge/lang/cs_cz.json
  src/main/resources/assets/neoforge/lang/eo_uy.json
  src/main/resources/assets/neoforge/lang/es_es.json
  src/main/resources/assets/neoforge/lang/ms_my.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/pt_br.json
  src/main/resources/assets/neoforge/lang/pt_pt.json
  src/main/resources/assets/neoforge/lang/uk_ua.json
  src/main/resources/assets/neoforge/lang/vi_vn.json
  src/main/resources/assets/neoforge/lang/zh_hk.json
Labels: l10n

#1494 Add missing `minecraft:enchantable/vanishing` to `c:enchantables`
  src/generated/resources/data/c/tags/item/enchantables.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
Labels: bug, 1.21.1, awaiting community agreement

#1490 Replace json-styled translations with string-value translations
  src/main/java/net/neoforged/neoforge/client/gui/ConfigurationScreen.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: bug, 1.21.1

#1515 Bump JCC and use the custom Java version action
  .github/workflows/build-prs.yml
  .github/workflows/check-local-changes.yml
  .github/workflows/test-prs.yml
  projects/neoforge/build.gradle
Labels: cleanup, ci/build, 1.21.1

#1514 Fix null pointer when stopping chunk pregeneration
  src/main/java/net/neoforged/neoforge/server/command/GenerateCommand.java
Labels: bug, 1.21.1

#1506 Add capability support for the Crafter output
  patches/net/minecraft/world/level/block/CrafterBlock.java.patch
  src/main/java/net/neoforged/neoforge/items/VanillaInventoryCodeHooks.java
Labels: enhancement, 1.21.1

#1499 [21.1] Pass along interaction had to ItemStack.onEntitySwing
  patches/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
Labels: enhancement, 1.21.1

#1476 JSON Entity Animations
  patches/net/minecraft/client/model/HierarchicalModel.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java
  src/main/java/net/neoforged/neoforge/client/entity/animation/AnimationKeyframeTarget.java
  src/main/java/net/neoforged/neoforge/client/entity/animation/AnimationTarget.java
  src/main/java/net/neoforged/neoforge/client/entity/animation/json/AnimationHolder.java
  src/main/java/net/neoforged/neoforge/client/entity/animation/json/AnimationLoader.java
  src/main/java/net/neoforged/neoforge/client/entity/animation/json/AnimationParser.java
  src/main/java/net/neoforged/neoforge/client/entity/animation/json/AnimationTypeManager.java
  src/main/java/net/neoforged/neoforge/client/entity/animation/json/package-info.java
  src/main/java/net/neoforged/neoforge/client/entity/animation/package-info.java
  src/main/java/net/neoforged/neoforge/client/event/RegisterJsonAnimationTypesEvent.java
  src/main/java/net/neoforged/neoforge/data/loading/DatagenModLoader.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/EntityModelSerializationTest.java
Labels: enhancement, rendering, data driven, 1.21.1

#1525 Namespace the Neoforge Entity Animation JSONs with `neoforge/`
  src/main/java/net/neoforged/neoforge/client/entity/animation/json/AnimationLoader.java
Labels: bug, breaking change, 1.21.1

#1520 Add back original constructor for `TagsProvider.TagAppender`
  patches/net/minecraft/data/tags/TagsProvider.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/ITagAppenderExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/ITagBuilderExtension.java
Labels: cleanup, 1.21.1

#1528 Add `hangingSignBlock` method to `BlockStateProvider`
  src/main/java/net/neoforged/neoforge/client/model/generators/BlockStateProvider.java
  tests/src/generated/resources/assets/data_gen_test/models/block/acacia_hanging_sign.json
  tests/src/generated/resources/assets/minecraft/blockstates/acacia_hanging_sign.json
  tests/src/generated/resources/assets/minecraft/blockstates/acacia_wall_hanging_sign.json
  tests/src/main/java/net/neoforged/neoforge/oldtest/DataGeneratorTest.java
Labels: enhancement, 1.21.1

#1522 [1.21.1] Adjust `DeferredRegister$DataComponents` constructor to accept registry key
  src/main/java/net/neoforged/neoforge/registries/DeferredRegister.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/DeferredRegistryTest.java
Labels: enhancement, 1.21.1

#1465 Added `c:animal_foods` tag for all foods that can be eaten by animals
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/item/animal_foods.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: enhancement, 1.21.1

#1517 [1.21] Allow requesting entity outline processing for custom renderers outside of entity and blockentity rendering
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
Labels: enhancement, rendering, 1.21.1

#1536 Add Crying Obsidian to `c:obsidians` tag
  src/generated/resources/data/c/tags/block/obsidians.json
  src/generated/resources/data/c/tags/item/obsidians.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
Labels: bug, 1.21.1

#1544 Render hover tooltip after creative menu page size rendering
  patches/net/minecraft/client/gui/screens/inventory/CreativeModeInventoryScreen.java.patch
Labels: bug, regression, 1.21.1

#1539 [1.21.1] Fix WeightedBakedModel not calling getModelData() on the nested model
  patches/net/minecraft/client/resources/model/WeightedBakedModel.java.patch
Labels: bug, rendering, 1.21.1

#1549 Fix GrindstoneEvent.OnPlaceItem patch
  patches/net/minecraft/world/inventory/GrindstoneMenu.java.patch
Labels: bug, 1.21.1

#1447 Allow Datapack Registry to be configured by RegistryBuilder
  patches/net/minecraft/resources/RegistryDataLoader.java.patch
  src/main/java/net/neoforged/neoforge/registries/DataPackRegistryEvent.java
Labels: enhancement, data driven, 1.21.1

#1556 Add `c:obsidians/normal` and `c:obsidians/crying` subtags
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/block/obsidians.json
  src/generated/resources/data/c/tags/block/obsidians/crying.json
  src/generated/resources/data/c/tags/block/obsidians/normal.json
  src/generated/resources/data/c/tags/item/obsidians.json
  src/generated/resources/data/c/tags/item/obsidians/crying.json
  src/generated/resources/data/c/tags/item/obsidians/normal.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: enhancement, 1.21.1

#1551 [1.21] Add an Attribute formatting API for better control of attribute tooltips
  patches/net/minecraft/world/entity/ai/attributes/Attribute.java.patch
  patches/net/minecraft/world/entity/ai/attributes/Attributes.java.patch
  patches/net/minecraft/world/item/ItemStack.java.patch
  patches/net/minecraft/world/item/alchemy/PotionContents.java.patch
  src/main/java/net/neoforged/neoforge/client/event/AddAttributeTooltipsEvent.java
  src/main/java/net/neoforged/neoforge/client/event/GatherSkippedAttributeTooltipsEvent.java
  src/main/java/net/neoforged/neoforge/common/BooleanAttribute.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/PercentageAttribute.java
  src/main/java/net/neoforged/neoforge/common/extensions/IAttributeExtension.java
  src/main/java/net/neoforged/neoforge/common/util/AttributeTooltipContext.java
  src/main/java/net/neoforged/neoforge/common/util/AttributeUtil.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, 1.21.1

#1496 Allow setting if the critical hit should disable sweep attack in CriticalHitEvent, adding SweepAttackEvent
  patches/net/minecraft/world/entity/player/Player.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/event/entity/player/CriticalHitEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/player/SweepAttackEvent.java
Labels: enhancement, 1.21.1

#1541 Add a way to animate armor models in HumanoidArmorLayer
  patches/net/minecraft/client/renderer/entity/layers/HumanoidArmorLayer.java.patch
  src/main/java/net/neoforged/neoforge/client/extensions/common/IClientItemExtensions.java
Labels: enhancement, rendering, 1.21.1

#1529 Passing `RegistryAccess` to more Events!
  patches/net/minecraft/client/multiplayer/ClientPacketListener.java.patch
  patches/net/minecraft/server/MinecraftServer.java.patch
  patches/net/minecraft/world/item/alchemy/PotionBrewing.java.patch
  src/main/java/net/neoforged/neoforge/common/VillagerTradingManager.java
  src/main/java/net/neoforged/neoforge/event/brewing/RegisterBrewingRecipesEvent.java
  src/main/java/net/neoforged/neoforge/event/village/VillagerTradesEvent.java
  src/main/java/net/neoforged/neoforge/event/village/WandererTradesEvent.java
Labels: enhancement, 1.21.1

#1560 Add Pie Item Tag c:foods/pie
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/item/foods.json
  src/generated/resources/data/c/tags/item/foods/pie.json
  src/main/java/net/neoforged/neoforge/common/TagConventionLogWarning.java
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: enhancement, 1.21.1

#1545 Make Biome and Structure Modifiers not crash when attempted to be re-applied
  src/main/java/net/neoforged/neoforge/common/world/ModifiableBiomeInfo.java
  src/main/java/net/neoforged/neoforge/common/world/ModifiableStructureInfo.java
Labels: enhancement, 1.21.1
