Repository neoforged/NeoForge, pull requests merged in 2024-11, with the labels that each got.

#1651 [1.21.3] Fix `ToolMaterial` and `ArmorMaterial` causing crashes when unique tags are used
  src/main/java/net/neoforged/neoforge/registries/GameData.java
  tests/src/main/java/net/neoforged/neoforge/debug/item/ItemTests.java
Labels: bug, 1.21.3

#1657 [1.21.x] Fix Eclipse generic inference failure in testframework
  testframework/src/main/java/net/neoforged/testframework/registration/DeferredBlocks.java
Labels: bug, 1.21.3

#1656 Bump FML to v5
  gradle.properties
Labels: breaking change, dependencies, 1.21.3

#1661 Remove Unnecessary Fluid Patch Preventing Lava Movement
  patches/net/minecraft/world/entity/LivingEntity.java.patch
Labels: bug, regression, 1.21.3

#1652 [1.21.3] Show a range's default value in config file
  src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java
Labels: enhancement, 1.21.3

#1653 [1.21.1] Show a range's default value in config file
  src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java
Labels: enhancement, 1.21.1

#1671 [1.21.3] Fix composite and separate transforms models not baking generated item models correctly
  src/main/java/net/neoforged/neoforge/client/model/CompositeModel.java
  src/main/java/net/neoforged/neoforge/client/model/SeparateTransformsModel.java
Labels: bug, rendering, regression, 1.21.3

#1621 [1.21.3] Add event for registering atlases for use with Material
  patches/net/minecraft/client/resources/model/ModelManager.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/RegisterMaterialAtlasesEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/TextureAtlasTests.java
  tests/src/main/resources/assets/neotests_test_material_atlas/atlases/material_test.json
Labels: enhancement, rendering, 1.21.3

#1581 [1.21.1] Add event for registering atlases for use with Material
  patches/net/minecraft/client/resources/model/ModelManager.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/RegisterMaterialAtlasesEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/TextureAtlasTests.java
  tests/src/main/resources/assets/neotests_test_material_atlas/atlases/material_test.json
Labels: enhancement, rendering, 1.21.1

#1660 Add default BlockBehaviour.Properties overloads to DeferredRegister.Blocks
  src/main/java/net/neoforged/neoforge/registries/DeferredRegister.java
Labels: enhancement, 1.21.3

#1622 [1.21.3] Relax extensible enum coherence checks for extensible enums without custom entries
  src/main/java/net/neoforged/neoforge/network/configuration/CheckExtensibleEnums.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, networking, 1.21.3

#1559 [1.21.1] Relax extensible enum coherence checks for extensible enums without custom entries
  src/main/java/net/neoforged/neoforge/network/configuration/CheckExtensibleEnums.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, networking, 1.21.1

#1676 [1.21.3] Remove hardcoded ShieldItem check in LivingEntity
  patches/net/minecraft/world/entity/LivingEntity.java.patch
Labels: bug, 1.21.3

#1632 Only load resources once for gametest servers
  patches/net/minecraft/server/Main.java.patch
  tests/src/generated/resources/data/neotests_reloadable_reg_data_maps/data_maps/loot_table/effect_grant.json
  tests/src/main/java/net/neoforged/neoforge/debug/data/DataMapTests.java
Labels: bug, 1.21.3

#1678 [1.21.3] Remove `DeferredSpawnEggItem`
  patches/net/minecraft/client/color/item/ItemColors.java.patch
  patches/net/minecraft/world/item/SpawnEggItem.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/DeferredSpawnEggItem.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  tests/src/main/java/net/neoforged/neoforge/debug/item/ItemTests.java
Labels: enhancement, breaking change, 1.21.3

#1617 [1.21.3] Render Minecraft logo as builtin mods `logoFile`
  src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, 1.21.3

#1269 Add support for proper plural translation
  patches/net/minecraft/network/chat/contents/TranslatableContents.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java
Labels: enhancement, 1.21

#1604 [1.21.3] Fix nametag rendering and optional text filtering
  patches/net/minecraft/client/gui/Font.java.patch
  patches/net/minecraft/client/gui/font/GlyphRenderTypes.java.patch
  patches/net/minecraft/client/gui/font/glyphs/BakedGlyph.java.patch
  patches/net/minecraft/client/renderer/RenderType.java.patch
  src/main/java/net/neoforged/neoforge/client/NeoForgeRenderTypes.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/client/rendering/LinearTextTextureFilteringTest.java
Labels: rendering, 1.21.3

#1440 [1.21.3] Add remove count context to `ItemSmeltedEvent` and fix firing multiple times with shift-click
  patches/net/minecraft/world/inventory/FurnaceResultSlot.java.patch
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/entity/player/PlayerEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/crafting/CraftingEventTests.java
Labels: bug, enhancement, breaking change, 1.21.2

#1396 Added tick callback to FallingBlockEntity
  patches/net/minecraft/world/entity/item/FallingBlockEntity.java.patch
  patches/net/minecraft/world/level/block/Fallable.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IFallableExtension.java
Labels: enhancement, 1.21

#1304 [1.21.3] Add RenderPlayerEvent test and docs fixup
  src/main/java/net/neoforged/neoforge/client/event/RenderLivingEvent.java
  src/main/java/net/neoforged/neoforge/client/event/RenderPlayerEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/ClientEventTests.java
Labels: rendering, breaking change, 1.21.1

#1658 [1.21.1] Make Neoforge's Needs Netherite Tool block tag be added to vanilla's incorrect block tags
  src/generated/resources/data/minecraft/tags/block/incorrect_for_diamond_tool.json
  src/generated/resources/data/minecraft/tags/block/incorrect_for_gold_tool.json
  src/generated/resources/data/minecraft/tags/block/incorrect_for_iron_tool.json
  src/generated/resources/data/minecraft/tags/block/incorrect_for_stone_tool.json
  src/generated/resources/data/minecraft/tags/block/incorrect_for_wooden_tool.json
  src/generated/resources/data/neoforge/tags/block/needs_netherite_tool.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
Labels: enhancement, backport, 1.21.1

#1427 Simplified usage of GatherDataEvent
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/data/event/GatherDataEvent.java
Labels: enhancement, 1.21

#1538 [1.21.1] Allow mods to add custom FeatureFlags
  patches/net/minecraft/client/gui/screens/worldselection/ExperimentsScreen.java.patch
  patches/net/minecraft/world/flag/FeatureFlag.java.patch
  patches/net/minecraft/world/flag/FeatureFlagRegistry.java.patch
  patches/net/minecraft/world/flag/FeatureFlagSet.java.patch
  patches/net/minecraft/world/flag/FeatureFlags.java.patch
  src/main/java/net/neoforged/neoforge/client/gui/ScrollableExperimentsScreen.java
  src/main/java/net/neoforged/neoforge/common/util/flag/FeatureFlagLoader.java
  src/main/java/net/neoforged/neoforge/common/util/flag/package-info.java
  src/main/java/net/neoforged/neoforge/network/ConfigurationInitialization.java
  src/main/java/net/neoforged/neoforge/network/NetworkInitialization.java
  src/main/java/net/neoforged/neoforge/network/configuration/CheckFeatureFlags.java
  src/main/java/net/neoforged/neoforge/network/payload/FeatureFlagAcknowledgePayload.java
  src/main/java/net/neoforged/neoforge/network/payload/FeatureFlagDataPayload.java
  src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/assets/neoforge/lang/en_us.json
  tests/src/junit/java/net/neoforged/neoforge/unittest/CustomFeatureFlagsTest.java
  tests/src/junit/resources/META-INF/neoforge.mods.toml
  tests/src/junit/resources/feature_flags.json
  tests/src/main/java/net/neoforged/neoforge/debug/data/CustomFeatureFlagsTests.java
  tests/src/main/resources/META-INF/neoforge.mods.toml
  tests/src/main/resources/feature_flag_test_packs/flag_test_pack/pack.mcmeta
  tests/src/main/resources/feature_flag_test_packs/flag_test_pack_0/pack.mcmeta
  tests/src/main/resources/feature_flag_test_packs/flag_test_pack_1/pack.mcmeta
  tests/src/main/resources/feature_flag_test_packs/flag_test_pack_2/pack.mcmeta
  tests/src/main/resources/feature_flag_test_packs/flag_test_pack_3/pack.mcmeta
  tests/src/main/resources/feature_flag_test_packs/flag_test_pack_4/pack.mcmeta
  tests/src/main/resources/feature_flag_test_packs/flag_test_pack_5/pack.mcmeta
  tests/src/main/resources/feature_flag_test_packs/gating_test_pack/pack.mcmeta
  tests/src/main/resources/game_test_feature_flags.json
Labels: enhancement, data driven, 1.21.1

#1619 [1.21.3] Allow mods to add custom FeatureFlags
  patches/net/minecraft/client/gui/screens/worldselection/ExperimentsScreen.java.patch
  patches/net/minecraft/world/flag/FeatureFlag.java.patch
  patches/net/minecraft/world/flag/FeatureFlagRegistry.java.patch
  patches/net/minecraft/world/flag/FeatureFlagSet.java.patch
  patches/net/minecraft/world/flag/FeatureFlags.java.patch
  src/main/java/net/neoforged/neoforge/client/gui/ScrollableExperimentsScreen.java
  src/main/java/net/neoforged/neoforge/common/util/flag/FeatureFlagLoader.java
  src/main/java/net/neoforged/neoforge/common/util/flag/package-info.java
  src/main/java/net/neoforged/neoforge/network/ConfigurationInitialization.java
  src/main/java/net/neoforged/neoforge/network/NetworkInitialization.java
  src/main/java/net/neoforged/neoforge/network/configuration/CheckFeatureFlags.java
  src/main/java/net/neoforged/neoforge/network/payload/FeatureFlagAcknowledgePayload.java
  src/main/java/net/neoforged/neoforge/network/payload/FeatureFlagDataPayload.java
  src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/assets/neoforge/lang/en_us.json
  tests/src/junit/java/net/neoforged/neoforge/unittest/CustomFeatureFlagsTest.java
  tests/src/junit/resources/META-INF/neoforge.mods.toml
  tests/src/junit/resources/feature_flags.json
  tests/src/main/java/net/neoforged/neoforge/debug/data/CustomFeatureFlagsTests.java
  tests/src/main/resources/META-INF/neoforge.mods.toml
  tests/src/main/resources/feature_flag_test_packs/flag_test_pack/pack.mcmeta
  tests/src/main/resources/feature_flag_test_packs/flag_test_pack_0/pack.mcmeta
  tests/src/main/resources/feature_flag_test_packs/flag_test_pack_1/pack.mcmeta
  tests/src/main/resources/feature_flag_test_packs/flag_test_pack_2/pack.mcmeta
  tests/src/main/resources/feature_flag_test_packs/flag_test_pack_3/pack.mcmeta
  tests/src/main/resources/feature_flag_test_packs/flag_test_pack_4/pack.mcmeta
  tests/src/main/resources/feature_flag_test_packs/flag_test_pack_5/pack.mcmeta
  tests/src/main/resources/feature_flag_test_packs/gating_test_pack/pack.mcmeta
  tests/src/main/resources/game_test_feature_flags.json
Labels: enhancement, data driven, 1.21.3

#1687 [1.21.x] Allow changing datagen indent width
  patches/net/minecraft/data/DataProvider.java.patch
Labels: enhancement, 1.21.3

#1689 [1.21.x] Fix certain percentage attributes being displayed wrong
  src/main/java/net/neoforged/neoforge/common/PercentageAttribute.java
Labels: bug, 1.21.3

#1688 [1.21.1] Add default BlockBehaviour.Properties overloads to DeferredRegister.Blocks
  src/main/java/net/neoforged/neoforge/registries/DeferredRegister.java
Labels: enhancement, 1.21, backport

#1546 Truncate tags command clipboard text within 32k string limit
  src/main/java/net/neoforged/neoforge/server/command/TagsCommand.java
Labels: bug, 1.21.3

#1695 Update NeoGradle to 7.0.171
  settings.gradle
Labels: ci/build, dependencies, 1.21.3

#1654 [1.21.3] Fix unbound tags issue in registry snapshot application
  patches/net/minecraft/core/MappedRegistry.java.patch
  src/main/java/net/neoforged/neoforge/registries/GameData.java
  tests/src/main/java/net/neoforged/neoforge/debug/item/ItemTests.java
Labels: bug, 1.21.3

#1485 Use an in-tree Gradle plugin instead of an external Gradle Plugin to make version-specific changes easier
  .github/workflows/check-local-changes.yml
  build.gradle
  buildSrc/README.md
  buildSrc/build.gradle
  buildSrc/settings.gradle
  buildSrc/src/main/groovy/neoforge.formatting-conventions.gradle
  buildSrc/src/main/java/net/neoforged/neodev/ApplyAccessTransformer.java
  buildSrc/src/main/java/net/neoforged/neodev/ApplyPatches.java
  buildSrc/src/main/java/net/neoforged/neodev/CreateCleanArtifacts.java
  buildSrc/src/main/java/net/neoforged/neodev/CreateUserDevConfig.java
  buildSrc/src/main/java/net/neoforged/neodev/GenerateBinaryPatches.java
  buildSrc/src/main/java/net/neoforged/neodev/GenerateSourcePatches.java
  buildSrc/src/main/java/net/neoforged/neodev/NeoDevBasePlugin.java
  buildSrc/src/main/java/net/neoforged/neodev/NeoDevConfigurations.java
  buildSrc/src/main/java/net/neoforged/neodev/NeoDevExtension.java
  buildSrc/src/main/java/net/neoforged/neodev/NeoDevExtraPlugin.java
  buildSrc/src/main/java/net/neoforged/neodev/NeoDevPlugin.java
  buildSrc/src/main/java/net/neoforged/neodev/NeoDevTestExtension.java
  buildSrc/src/main/java/net/neoforged/neodev/RemapJar.java
  buildSrc/src/main/java/net/neoforged/neodev/Tools.java
  buildSrc/src/main/java/net/neoforged/neodev/installer/CreateArgsFile.java
  buildSrc/src/main/java/net/neoforged/neodev/installer/CreateInstallerProfile.java
  buildSrc/src/main/java/net/neoforged/neodev/installer/CreateLauncherProfile.java
  buildSrc/src/main/java/net/neoforged/neodev/installer/IdentifiedFile.java
  buildSrc/src/main/java/net/neoforged/neodev/installer/InstallerProcessor.java
  buildSrc/src/main/java/net/neoforged/neodev/installer/Library.java
  buildSrc/src/main/java/net/neoforged/neodev/installer/LibraryArtifact.java
  buildSrc/src/main/java/net/neoforged/neodev/installer/LibraryCollector.java
  buildSrc/src/main/java/net/neoforged/neodev/installer/LibraryDownload.java
  buildSrc/src/main/java/net/neoforged/neodev/utils/DependencyUtils.java
  buildSrc/src/main/java/net/neoforged/neodev/utils/FileUtils.java
  buildSrc/src/main/java/net/neoforged/neodev/utils/MavenIdentifier.java
  coremods/build.gradle
  coremods/settings.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  projects/base/build.gradle
  projects/neoforge/build.gradle
  settings.gradle
  testframework/build.gradle
  tests/build.gradle
Labels: enhancement, ci/build, 1.21.3

#1690 Add a hook for blocks to suppress a neighboring fluid overlay
  patches/net/minecraft/client/renderer/block/LiquidBlockRenderer.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockStateExtension.java
  tests/src/generated/resources/assets/neotests_test_water_glass_face_removal/blockstates/water_glass.json
  tests/src/generated/resources/assets/neotests_test_water_glass_face_removal/lang/en_us.json
  tests/src/generated/resources/assets/neotests_test_water_glass_face_removal/models/block/water_glass.json
  tests/src/main/java/net/neoforged/neoforge/debug/fluid/ClientFluidTests.java
Labels: enhancement, rendering, 1.21.3

#1572 [1.21.3] Add NF's needs_netherite_tool block tag to vanilla's incorrect_for_*_tool block tags
  src/generated/resources/data/minecraft/tags/block/incorrect_for_diamond_tool.json
  src/generated/resources/data/minecraft/tags/block/incorrect_for_gold_tool.json
  src/generated/resources/data/minecraft/tags/block/incorrect_for_iron_tool.json
  src/generated/resources/data/minecraft/tags/block/incorrect_for_stone_tool.json
  src/generated/resources/data/minecraft/tags/block/incorrect_for_wooden_tool.json
  src/generated/resources/data/neoforge/tags/block/needs_netherite_tool.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
Labels: bug, 1.21.3

#1710 [1.21.3] Fix recipe manager not using ConditionalOps
  patches/net/minecraft/world/item/crafting/RecipeManager.java.patch
  tests/src/generated/resources/data/neotests_test_conditional_recipe/advancement/recipes/misc/always_disabled_recipe.json
  tests/src/generated/resources/data/neotests_test_conditional_recipe/recipe/always_disabled_recipe.json
  tests/src/main/java/net/neoforged/neoforge/debug/ConditionalRecipeTest.java
Labels: bug, 1.21.3

#1707 Throw only when passed clientside level
  src/main/java/net/neoforged/neoforge/network/PacketDistributor.java
Labels: bug, 1.21.3

#1711 Only factor in tabs with items on Creative Menu pages
  patches/net/minecraft/client/gui/screens/inventory/CreativeModeInventoryScreen.java.patch
Labels: bug, 1.21.3

#1703 [1.21.3] Append unknown modded flags to `removed_features` level data
  patches/net/minecraft/world/level/storage/PrimaryLevelData.java.patch
Labels: 1.21.3

#1709 Add attributeAdvancedTooltipDebugInfo config option
  src/main/java/net/neoforged/neoforge/common/NeoForgeConfig.java
  src/main/java/net/neoforged/neoforge/common/extensions/IAttributeExtension.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, 1.21.3

#1712 [1.21.3] Add condition to validate feature flags enabled state
  patches/net/minecraft/server/ReloadableServerResources.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/conditions/ConditionContext.java
  src/main/java/net/neoforged/neoforge/common/conditions/FlagCondition.java
  src/main/java/net/neoforged/neoforge/common/conditions/ICondition.java
  src/main/java/net/neoforged/neoforge/common/conditions/IConditionBuilder.java
  tests/src/generated/resources/data/neotests_test_flag_condition/advancement/recipes/misc/diamonds_from_dirt.json
  tests/src/generated/resources/data/neotests_test_flag_condition/advancement/recipes/misc/dirt_from_diamonds.json
  tests/src/generated/resources/data/neotests_test_flag_condition/recipe/diamonds_from_dirt.json
  tests/src/generated/resources/data/neotests_test_flag_condition/recipe/dirt_from_diamonds.json
  tests/src/main/java/net/neoforged/neoforge/debug/data/CustomFeatureFlagsTests.java
Labels: 1.21.3

#1701 [1.21.1] Add a hook for blocks to suppress a neighboring fluid overlay
  patches/net/minecraft/client/renderer/block/LiquidBlockRenderer.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockStateExtension.java
  tests/src/generated/resources/assets/neotests_test_water_glass_face_removal/blockstates/water_glass.json
  tests/src/generated/resources/assets/neotests_test_water_glass_face_removal/lang/en_us.json
  tests/src/generated/resources/assets/neotests_test_water_glass_face_removal/models/block/water_glass.json
  tests/src/main/java/net/neoforged/neoforge/debug/fluid/ClientFluidTests.java
Labels: rendering, backport, 1.21.1

#1713 Simplify FlagCondition
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/conditions/FeatureFlagsEnabledCondition.java
  src/main/java/net/neoforged/neoforge/common/conditions/FlagCondition.java
  src/main/java/net/neoforged/neoforge/common/conditions/IConditionBuilder.java
  tests/src/generated/resources/data/neotests_test_flag_condition/advancement/recipes/misc/diamonds_from_dirt.json
  tests/src/generated/resources/data/neotests_test_flag_condition/advancement/recipes/misc/dirt_from_diamonds.json
  tests/src/generated/resources/data/neotests_test_flag_condition/recipe/diamonds_from_dirt.json
  tests/src/generated/resources/data/neotests_test_flag_condition/recipe/dirt_from_diamonds.json
  tests/src/main/java/net/neoforged/neoforge/debug/data/CustomFeatureFlagsTests.java
Labels: cleanup, 1.21.3

#1714 Backport "Only factor in tabs with items on Creative Menu pages"
  patches/net/minecraft/client/gui/screens/inventory/CreativeModeInventoryScreen.java.patch
Labels: bug, 1.21.1

#1708 Make AttributeTemplate record public
  patches/net/minecraft/world/effect/MobEffect.java.patch
  src/main/resources/META-INF/accesstransformer.cfg
Labels: bug, 1.21.3

#1650 [1.21.3] `RegisterRenderStateModifiersEvent` for appending custom data to render state objects
  patches/net/minecraft/client/renderer/MapRenderer.java.patch
  patches/net/minecraft/client/renderer/entity/EntityRenderer.java.patch
  patches/net/minecraft/client/renderer/entity/state/EntityRenderState.java.patch
  patches/net/minecraft/client/renderer/state/MapRenderState.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/extensions/IRenderStateExtension.java
  src/main/java/net/neoforged/neoforge/client/renderstate/BaseRenderState.java
  src/main/java/net/neoforged/neoforge/client/renderstate/MapDecorationRenderStateModifier.java
  src/main/java/net/neoforged/neoforge/client/renderstate/RegisterRenderStateModifiersEvent.java
  src/main/java/net/neoforged/neoforge/client/renderstate/RenderStateExtensions.java
  src/main/java/net/neoforged/neoforge/client/renderstate/package-info.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/ClientEventTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/MapDecorationRenderTests.java
Labels: enhancement, rendering, 1.21.3
