Repository neoforged/NeoForge, pull requests merged in 2024-10, with the labels that each got.

#1421 [1.21] Allow for custom components in enchantment datagen
  patches/net/minecraft/world/item/enchantment/Enchantment.java.patch
Labels: enhancement, 1.21

#1542 Add a few new `ItemModelProvider` methods!
  src/main/java/net/neoforged/neoforge/client/model/generators/ItemModelProvider.java
  tests/src/generated/resources/assets/minecraft/models/item/acacia_planks.json
  tests/src/generated/resources/assets/minecraft/models/item/sheep_spawn_egg.json
  tests/src/generated/resources/assets/minecraft/models/item/wooden_sword.json
  tests/src/main/java/net/neoforged/neoforge/oldtest/client/model/CustomItemDisplayContextTest.java
Labels: enhancement, 1.21.1

#1573 Add `c:experience` fluid tag with javadoc for standard conversion rate
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/fluid/experience.json
  src/main/java/net/neoforged/neoforge/common/TagConventionLogWarning.java
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeFluidTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: 1.21.1

#1584 Add Stripped Logs and Stripped Woods Tags
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/block/stripped_logs.json
  src/generated/resources/data/c/tags/block/stripped_woods.json
  src/generated/resources/data/c/tags/item/stripped_logs.json
  src/generated/resources/data/c/tags/item/stripped_woods.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: enhancement, 1.21.1

#1600 [1.21.2] Make block outline passes respect render types specified by the model
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
Labels: rendering, 1.21.2

#1599 [1.21.2] Replace RenderTooltipEvent.Color with RenderTooltipEvent.Texture
  patches/net/minecraft/client/gui/GuiGraphics.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/RenderTooltipEvent.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/client/CustomTooltipTest.java
  tests/src/main/resources/assets/custom_tooltip_test/textures/gui/sprites/tooltip/test_background.png
  tests/src/main/resources/assets/custom_tooltip_test/textures/gui/sprites/tooltip/test_background.png.mcmeta
  tests/src/main/resources/assets/custom_tooltip_test/textures/gui/sprites/tooltip/test_frame.png
  tests/src/main/resources/assets/custom_tooltip_test/textures/gui/sprites/tooltip/test_frame.png.mcmeta
Labels: 1.21.2

#1602 [1.21.2] Remove deprecated Item `onEntitySwing` methods
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
Labels: 1.21.2

#1614 Fix `InputEvent$Key` not being fired
  patches/net/minecraft/client/KeyboardHandler.java.patch
Labels: bug, 1.21.2

#1578 Add new MobEffect constructor that allows specifying a particle factory
  patches/net/minecraft/world/effect/MobEffect.java.patch
Labels: 1.21.1

#1615 Fix mod logos not being rendered in the mod list
  src/main/java/net/neoforged/neoforge/client/extensions/IGuiGraphicsExtension.java
Labels: bug, rendering, 1.21.3

#1620 [1.21.3] Expose RecipeManager#recipes
  patches/net/minecraft/world/item/crafting/RecipeManager.java.patch
Labels: enhancement, triage, 1.21.3

#1512 New Crowdin updates
  src/main/resources/assets/neoforge/lang/cs_cz.json
  src/main/resources/assets/neoforge/lang/da_dk.json
  src/main/resources/assets/neoforge/lang/de_de.json
  src/main/resources/assets/neoforge/lang/en_gb.json
  src/main/resources/assets/neoforge/lang/eo_uy.json
  src/main/resources/assets/neoforge/lang/es_es.json
  src/main/resources/assets/neoforge/lang/et_ee.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/hu_hu.json
  src/main/resources/assets/neoforge/lang/it_it.json
  src/main/resources/assets/neoforge/lang/ja_jp.json
  src/main/resources/assets/neoforge/lang/ko_kr.json
  src/main/resources/assets/neoforge/lang/ms_my.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/pt_br.json
  src/main/resources/assets/neoforge/lang/pt_pt.json
  src/main/resources/assets/neoforge/lang/ro_ro.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/sk_sk.json
  src/main/resources/assets/neoforge/lang/tr_tr.json
  src/main/resources/assets/neoforge/lang/tt_ru.json
  src/main/resources/assets/neoforge/lang/uk_ua.json
  src/main/resources/assets/neoforge/lang/vi_vn.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_tw.json
Labels: l10n

#1648 [1.21.3] Fix for data map serialization
  src/main/java/net/neoforged/neoforge/common/data/DataMapProvider.java
Labels: bug, data driven, 1.21.3
