Repository neoforged/NeoForge, pull requests merged in 2024-05, with the labels that each got.

#897 Fire EntityTickEvent.Post
  patches/net/minecraft/client/multiplayer/ClientLevel.java.patch
  patches/net/minecraft/server/level/ServerLevel.java.patch
  patches/net/minecraft/world/entity/Entity.java.patch
Labels: bug, 1.20.6

#892 Add an event fired when data maps are updated
  src/main/java/net/neoforged/neoforge/registries/ClientRegistryManager.java
  src/main/java/net/neoforged/neoforge/registries/DataMapLoader.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/DataMapsUpdatedEvent.java
  testframework/src/main/java/net/neoforged/testframework/impl/reg/RegistrationHelperImpl.java
  testframework/src/main/java/net/neoforged/testframework/registration/RegistrationHelper.java
  tests/src/generated/resources/data/neotests_data_map_update_event_test/data_maps/item/weight.json
  tests/src/main/java/net/neoforged/neoforge/debug/data/DataMapTests.java
Labels: enhancement, data driven, 1.20.6

#900 Rebuild indexed feature list after biome modification
  patches/net/minecraft/world/level/chunk/ChunkGenerator.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/util/Lazy.java
  src/main/java/net/neoforged/neoforge/common/util/NonNullLazy.java
  src/main/java/net/neoforged/neoforge/server/ServerLifecycleHooks.java
Labels: bug, 1.20.6

#834 Update to FML locator rewrite
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  patches/net/minecraft/client/renderer/Sheets.java.patch
  patches/net/minecraft/world/effect/MobEffect.java.patch
  patches/net/minecraft/world/item/Item.java.patch
  patches/net/minecraft/world/level/block/Block.java.patch
  settings.gradle
  src/main/java/net/neoforged/neoforge/client/gui/LoadingErrorScreen.java
  src/main/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/main/java/net/neoforged/neoforge/common/CreativeModeTabRegistry.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/event/AddReloadListenerEvent.java
  src/main/java/net/neoforged/neoforge/fluids/FluidType.java
  src/main/java/net/neoforged/neoforge/gametest/GameTestHooks.java
  src/main/java/net/neoforged/neoforge/internal/BrandingControl.java
  src/main/java/net/neoforged/neoforge/internal/versions/neoforge/NeoForgeVersion.java
  src/main/java/net/neoforged/neoforge/internal/versions/neoform/NeoFormVersion.java
  src/main/java/net/neoforged/neoforge/logging/CrashReportExtender.java
  src/main/java/net/neoforged/neoforge/resource/ResourcePackLoader.java
  src/main/java/net/neoforged/neoforge/server/command/ModListCommand.java
  src/main/java/net/neoforged/neoforge/server/loading/ServerModLoader.java
  src/main/resources/assets/neoforge/lang/en_us.json
  testframework/src/main/java/net/neoforged/testframework/impl/FrameworkCollectors.java
Labels: enhancement, breaking change, 1.20.6

#905 Remove NonNullXxx functional interfaces
  src/main/java/net/neoforged/neoforge/common/util/NonNullConsumer.java
  src/main/java/net/neoforged/neoforge/common/util/NonNullFunction.java
  src/main/java/net/neoforged/neoforge/common/util/NonNullPredicate.java
  src/main/java/net/neoforged/neoforge/common/util/NonNullSupplier.java
Labels: cleanup, 1.20.6

#909 Fix installer jsons being cached wrongly
  settings.gradle
Labels: bug, 1.20.6

#895 [1.20.6] Miscellaneous network cleanup
  patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch
  patches/net/minecraft/client/multiplayer/ClientConfigurationPacketListenerImpl.java.patch
  patches/net/minecraft/client/multiplayer/CommonListenerCookie.java.patch
  patches/net/minecraft/server/network/CommonListenerCookie.java.patch
  patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch
  patches/net/minecraft/server/network/ServerConfigurationPacketListenerImpl.java.patch
  src/main/java/net/neoforged/neoforge/network/connection/ConnectionType.java
  src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java
  src/main/java/net/neoforged/neoforge/network/registration/PayloadRegistration.java
Labels: cleanup, 1.20.6

#877 [1.20.5] Add PlayerRespawnPositionEvent
  patches/net/minecraft/server/players/PlayerList.java.patch
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/entity/player/PlayerEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/player/PlayerRespawnPositionEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/player/PlayerEventTests.java
Labels: enhancement, last call, 1.20.5

#913 Entity attachment copy fix
  src/main/java/net/neoforged/neoforge/common/extensions/IEntityExtension.java
  tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java
Labels: bug, 1.20.6

#914 Bump neoforge_snapshot_next_stable to 21.0
  gradle.properties
Labels: ci/build, 1.20.6

#910 Force ArmorMaterial registry event to fire before Items.
  src/main/java/net/neoforged/neoforge/registries/GameData.java
Labels: bug, vanilla bug, 1.20.6

#916 [20.6] Disallow fuel values of -1
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
Labels: cleanup, 1.20.6

#917 Fix incorrect parameter patch in LevelSettings
  patches/net/minecraft/world/level/LevelSettings.java.patch
Labels: bug, 1.20.6

#921 Exiting options screen now keeps game paused
  patches/net/minecraft/client/gui/screens/OptionsScreen.java.patch
Labels: bug, regression, 1.20.6

#923 Allow track command to function again for Block Entities
  patches/net/minecraft/world/level/chunk/LevelChunk.java.patch
Labels: bug, 1.20.6

#925 Disable online mode in dev
  patches/net/minecraft/server/dedicated/DedicatedServerProperties.java.patch
Labels: enhancement, 1.20.6

#924 Have TranslatableContents throw when fed improper arguments in dev
  patches/net/minecraft/network/chat/contents/TranslatableContents.java.patch
  src/main/java/net/neoforged/neoforge/forge/snapshots/ForgeSnapshotsModClient.java
  src/main/java/net/neoforged/neoforge/network/handlers/ClientPayloadHandler.java
  src/main/java/net/neoforged/neoforge/network/negotiation/NetworkComponentNegotiator.java
  src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java
  src/main/java/net/neoforged/neoforge/registries/ClientRegistryManager.java
Labels: bug, enhancement, 1.20.6

#918 [1.20.x] Use a datamap for monster room mob spawners
  patches/net/minecraft/world/level/levelgen/feature/MonsterRoomFeature.java.patch
  src/generated/resources/data/neoforge/data_maps/entity_type/monster_room_mobs.json
  src/main/java/net/neoforged/neoforge/common/DungeonHooks.java
  src/main/java/net/neoforged/neoforge/common/MonsterRoomHooks.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeDataMapsProvider.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/MonsterRoomMob.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/NeoForgeDataMaps.java
Labels: enhancement, data driven, 1.20.6

#930 Fix component issues in the error screen
  src/main/java/net/neoforged/neoforge/client/gui/LoadingErrorScreen.java
Labels: bug, 1.20.6

#929 Update FML to changes in lang loaders
  gradle.properties
  src/main/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java
  src/main/java/net/neoforged/neoforge/client/TagConventionLogWarningClient.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/TagConventionLogWarning.java
  src/main/resources/assets/neoforge/lang/en_us.json
  testframework/src/main/java/net/neoforged/testframework/impl/FrameworkCollectors.java
  tests/src/main/java/net/neoforged/neoforge/debug/fml/MultipleEntrypointsTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/fml/package-info.java
  tests/src/main/resources/META-INF/neoforge.mods.toml
Labels: enhancement, 1.20.6

#850 [20.5] Add a getAttributeModifiers method to IItemStackExtension
  patches/net/minecraft/world/item/ItemStack.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
Labels: enhancement, 1.20.5

#856 Add level and pos context to `PlayerEvent.HarvestCheck`
  patches/net/minecraft/world/entity/player/Player.java.patch
  patches/net/minecraft/world/level/block/DoorBlock.java.patch
  patches/net/minecraft/world/level/block/state/BlockBehaviour.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/entity/player/PlayerEvent.java
  src/main/java/net/neoforged/neoforge/event/level/BlockEvent.java
Labels: enhancement, 1.20.5

#938 Update to use the new FML translation hooks
  gradle.properties
  patches/net/minecraft/client/resources/language/ClientLanguage.java.patch
  patches/net/minecraft/client/resources/language/I18n.java.patch
  patches/net/minecraft/network/chat/contents/TranslatableContents.java.patch
  src/main/java/net/neoforged/neoforge/client/gui/LoadingErrorScreen.java
  src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java
  src/main/java/net/neoforged/neoforge/client/gui/ModMismatchDisconnectedScreen.java
  src/main/java/net/neoforged/neoforge/client/gui/widget/ModListWidget.java
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/I18nExtension.java
  src/main/java/net/neoforged/neoforge/common/util/MavenVersionStringHelper.java
  src/main/java/net/neoforged/neoforge/internal/BrandingControl.java
  src/main/java/net/neoforged/neoforge/internal/NeoForgeBindings.java
  src/main/java/net/neoforged/neoforge/internal/TextComponentMessageFormatHandler.java
  src/main/java/net/neoforged/neoforge/server/LanguageHook.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: bug, enhancement, 1.20.6

#904 [1.20.6] Avoid continuous rediscovery of child datapacks
  patches/net/minecraft/server/packs/repository/Pack.java.patch
  src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java
  src/main/java/net/neoforged/neoforge/common/data/ExistingFileHelper.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: bug, 1.20.6

#932 [20.6] Add tooltip helper for data component types
  src/main/java/net/neoforged/neoforge/common/extensions/IDataComponentHolderExtension.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, 1.20.6

#931 Added getBubbleColumnDirection IBlockExtension hook to reduce BubbleColumn hardcoding
  patches/net/minecraft/world/level/block/BubbleColumnBlock.java.patch
  src/main/java/net/neoforged/neoforge/common/enums/BubbleColumnDirection.java
  src/main/java/net/neoforged/neoforge/common/enums/package-info.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockStateExtension.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/BlockTests.java
Labels: enhancement, 1.20.6

#920 Allow multiple of same itemstack for BuildCreativeModeTabContentsEvent
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
Labels: bug, 1.20.6

#915 [1.20.6] Fix several NeoForge command crashes and allow chat OpenFile click action on Integrated Server
  patches/net/minecraft/network/chat/ClickEvent.java.patch
  src/main/java/net/neoforged/neoforge/client/command/ClientConfigCommand.java
  src/main/java/net/neoforged/neoforge/client/command/package-info.java
  src/main/java/net/neoforged/neoforge/server/command/ConfigCommand.java
  src/main/java/net/neoforged/neoforge/server/command/EntityCommand.java
  src/main/java/net/neoforged/neoforge/server/command/TrackCommand.java
Labels: bug, 1.20.6

#880 Fix FinalizeSpawnEvent for trial spawners
  patches/net/minecraft/world/entity/Mob.java.patch
  patches/net/minecraft/world/entity/vehicle/MinecartSpawner.java.patch
  patches/net/minecraft/world/level/BaseSpawner.java.patch
  patches/net/minecraft/world/level/block/entity/SpawnerBlockEntity.java.patch
  patches/net/minecraft/world/level/block/entity/trialspawner/TrialSpawner.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IOwnedSpawner.java
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/entity/living/FinalizeSpawnEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/living/MobSpawnEvent.java
  src/main/resources/coremods/method_redirector.js
  tests/src/main/java/net/neoforged/neoforge/oldtest/FinalizeSpawnTest.java
Labels: bug, breaking change, 1.20.5

#885 Add more accurate culling for single quad particles
  patches/net/minecraft/client/particle/Particle.java.patch
  patches/net/minecraft/client/particle/ParticleEngine.java.patch
  patches/net/minecraft/client/particle/SingleQuadParticle.java.patch
  patches/net/minecraft/client/renderer/blockentity/PistonHeadRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/StructureBlockRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/TheEndGatewayRenderer.java.patch
  patches/net/minecraft/client/renderer/culling/Frustum.java.patch
  patches/net/minecraft/world/phys/AABB.java.patch
  src/main/java/net/neoforged/neoforge/client/ParticleBoundsDebugRenderer.java
  src/main/java/net/neoforged/neoforge/client/extensions/IBlockEntityRendererExtension.java
Labels: bug, enhancement, breaking change, 1.20.5

#946 Fix dedicated server GUI never showing up
  patches/net/minecraft/server/Main.java.patch
Labels: bug, regression, 1.20.6

#945 Bump Mixin to 0.13.4 to fix local variable issues
  gradle.properties
Labels: bug

#948 Remove Unnecessary Stitcher patch
  patches/net/minecraft/client/renderer/texture/Stitcher.java.patch
Labels: cleanup, 1.20.6

#922 Fire Villager/Wandering Trader trade events on /reload
  src/main/java/net/neoforged/neoforge/common/VillagerTradingManager.java
  src/main/java/net/neoforged/neoforge/event/village/VillagerTradesEvent.java
  src/main/java/net/neoforged/neoforge/event/village/WandererTradesEvent.java
Labels: enhancement, 1.20.6

#767 Fix MC-268617 to allow valid filepaths in Minecraft
  patches/net/minecraft/FileUtil.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
Labels: bug, vanilla bug, 1.20.5

#952 Delete ItemModelShaper patch
  patches/net/minecraft/client/renderer/ItemModelShaper.java.patch
Labels: cleanup, 1.20.6

#950 [Test Framework] Add a check in `StructureTemplateBuilder#set` to prevent placing block outside template bondaries
  testframework/src/main/java/net/neoforged/testframework/gametest/StructureTemplateBuilder.java
Labels: bug, 1.20.6

#937 Address POI memory leak and Generate Command issues
  patches/net/minecraft/server/level/ChunkMap.java.patch
  patches/net/minecraft/world/level/chunk/storage/SectionStorage.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/server/command/GenerateCommand.java
  src/main/java/net/neoforged/neoforge/server/command/generation/GenerationTask.java
Labels: bug, vanilla bug, 1.20.6

#954 Make StructureTemplate's Palette caches thread safe
  patches/net/minecraft/world/level/levelgen/structure/templatesystem/StructureTemplate.java.patch
Labels: bug, vanilla bug, 1.20.6

#957 Update FML to 3.0.29
  gradle.properties
Labels: breaking change, 1.20.6

#901 [1.20.6] Add KnownPacks for mods
  patches/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.java.patch
  patches/net/minecraft/client/multiplayer/KnownPacksManager.java.patch
  patches/net/minecraft/network/protocol/configuration/ServerboundSelectKnownPacks.java.patch
  patches/net/minecraft/server/network/config/SynchronizeRegistriesTask.java.patch
  patches/net/minecraft/server/packs/repository/ServerPacksSource.java.patch
  src/main/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/main/java/net/neoforged/neoforge/event/AddPackFindersEvent.java
  src/main/java/net/neoforged/neoforge/resource/ResourcePackLoader.java
  tests/src/main/java/net/neoforged/neoforge/debug/resources/BulkKnownPackTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/world/LoginPacketSplitTest.java
Labels: enhancement, 1.20.6

#964 [no ci] Fixed Bubble Column gametest template size
  tests/src/main/java/net/neoforged/neoforge/debug/block/BlockTests.java
Labels: bug, ci/build, 1.20.6

#963 [no ci] Remove PitcherCrop patch TODO
  patches/net/minecraft/world/level/block/PitcherCropBlock.java.patch
Labels: cleanup, 1.20.6

#968 Fix ComputeCameraAngles event applying roll in global space
  patches/net/minecraft/client/renderer/GameRenderer.java.patch
Labels: bug, 1.20.6

#967 Pass growing plant blockstate into onCropsGrowPre for various vine blocks
  patches/net/minecraft/world/level/block/GrowingPlantHeadBlock.java.patch
Labels: bug, 1.20.6

#966 Patch in missing LivingJumpEvent for Slime and Camel
  patches/net/minecraft/world/entity/animal/camel/Camel.java.patch
  patches/net/minecraft/world/entity/animal/horse/AbstractHorse.java.patch
  patches/net/minecraft/world/entity/monster/Slime.java.patch
  src/main/java/net/neoforged/neoforge/event/entity/living/LivingEvent.java
Labels: bug, 1.20.6

#958 [1.20.6] Use extensible enum codec and streamcodec for rarity enum
  patches/net/minecraft/world/item/Rarity.java.patch
Labels: bug, 1.20.6

#965 Implement equals and hashCode for SizedIngredients
  src/main/java/net/neoforged/neoforge/common/crafting/SizedIngredient.java
Labels: 1.20.6

#972 New Crowdin updates
  src/main/resources/assets/neoforge/lang/da_dk.json
  src/main/resources/assets/neoforge/lang/de_de.json
  src/main/resources/assets/neoforge/lang/en_gb.json
  src/main/resources/assets/neoforge/lang/es_es.json
  src/main/resources/assets/neoforge/lang/et_ee.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/hu_hu.json
  src/main/resources/assets/neoforge/lang/it_it.json
  src/main/resources/assets/neoforge/lang/ja_jp.json
  src/main/resources/assets/neoforge/lang/ko_kr.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/ro_ro.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/sk_sk.json
  src/main/resources/assets/neoforge/lang/tr_tr.json
  src/main/resources/assets/neoforge/lang/tt_ru.json
  src/main/resources/assets/neoforge/lang/uk_ua.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_hk.json
Labels: l10n

#789 [1.20.5] Add a Fluid Ingredient system as an analogue to vanilla's Ingredient
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/fluids/FluidStack.java
  src/main/java/net/neoforged/neoforge/fluids/crafting/CompoundFluidIngredient.java
  src/main/java/net/neoforged/neoforge/fluids/crafting/DataComponentFluidIngredient.java
  src/main/java/net/neoforged/neoforge/fluids/crafting/DifferenceFluidIngredient.java
  src/main/java/net/neoforged/neoforge/fluids/crafting/EmptyFluidIngredient.java
  src/main/java/net/neoforged/neoforge/fluids/crafting/FluidIngredient.java
  src/main/java/net/neoforged/neoforge/fluids/crafting/FluidIngredientType.java
  src/main/java/net/neoforged/neoforge/fluids/crafting/IntersectionFluidIngredient.java
  src/main/java/net/neoforged/neoforge/fluids/crafting/SingleFluidIngredient.java
  src/main/java/net/neoforged/neoforge/fluids/crafting/SizedFluidIngredient.java
  src/main/java/net/neoforged/neoforge/fluids/crafting/TagFluidIngredient.java
  src/main/java/net/neoforged/neoforge/fluids/crafting/package-info.java
  src/main/java/net/neoforged/neoforge/registries/NeoForgeRegistries.java
  src/main/java/net/neoforged/neoforge/registries/NeoForgeRegistriesSetup.java
  tests/src/main/java/net/neoforged/neoforge/debug/fluid/crafting/FluidIngredientTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/fluid/crafting/package-info.java
Labels: enhancement, last call, 1.20.5

#987 [Hotfix] Temporarily disable custom EffectCure syncing
  patches/net/minecraft/world/effect/MobEffectInstance.java.patch
Labels: bug, 1.20.6

#977 Fix rendering of non-translucent particles behind translucent geometry
  patches/net/minecraft/client/particle/ParticleEngine.java.patch
  patches/net/minecraft/client/particle/ParticleRenderType.java.patch
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
Labels: bug, rendering, breaking change, vanilla bug, 1.20.6

#973 Do not override enchantments of the `stored_enchantments` component
  patches/net/minecraft/FileUtil.java.patch
  patches/net/minecraft/advancements/critereon/ItemEnchantmentsPredicate.java.patch
Labels: bug, 1.20.6

#809 [1.20.5] Record a BlockSnapshot for client break predictions and cleanup break pipeline
  patches/net/minecraft/client/multiplayer/ClientLevel.java.patch
  patches/net/minecraft/client/multiplayer/MultiPlayerGameMode.java.patch
  patches/net/minecraft/client/multiplayer/prediction/BlockStatePredictionHandler.java.patch
  patches/net/minecraft/server/level/ServerPlayerGameMode.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
  src/main/java/net/neoforged/neoforge/common/util/BlockSnapshot.java
  src/main/java/net/neoforged/neoforge/event/level/BlockEvent.java
Labels: bug, breaking change, 1.20.6

#574 Keep AbstractFurnaceBlockEntity private canBurn and burn methods static
  patches/net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity.java.patch
Labels: cleanup, 1.20.6

#1002 Fix stack count comparison in DataComponentIngredient
  src/main/java/net/neoforged/neoforge/common/crafting/DataComponentIngredient.java
Labels: bug, 1.20.6

#1007 [1.20.6] Fix event results not defaulting to default
  src/main/java/net/neoforged/neoforge/event/entity/living/MobEffectEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/living/MobSpawnEvent.java
Labels: bug, blocks stable, 1.20.6

#1000 Add a spotless check to ensure we don't accidentally perform any access widening changes in patches
  build.gradle
Labels: enhancement, 1.20.6

#573 Add a JUnit subproject
  .github/workflows/build-prs.yml
  .github/workflows/test-prs.yml
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/neoforge.formatting-conventions.gradle
  buildscript/apply-all-formatting.gradle
  buildscript/generate-package-infos.gradle
  buildscript/spotless-rules.gradle
  gradle.properties
  projects/neoforge/build.gradle
  settings.gradle
  src/main/java/net/neoforged/neoforge/junit/JUnitMain.java
  src/main/java/net/neoforged/neoforge/junit/package-info.java
  testframework/build.gradle
  testframework/src/main/java/net/neoforged/testframework/junit/EphemeralTestServerProvider.java
  testframework/src/main/java/net/neoforged/testframework/junit/package-info.java
  tests/build.gradle
  tests/src/junit/java/net/neoforged/neoforge/unittest/IngredientTests.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/MutableHashedLinkedMapTest.java
  tests/src/main/java/net/neoforged/neoforge/unittest/ModConfigSpecTest.java
  tests/src/main/java/net/neoforged/neoforge/unittest/TextTableTest.java
Labels: enhancement, 1.20.6

#1014 Foxful Branding
  .idea/icon.svg
Labels: enhancement, 1.20.6

#1023 Update NeoGradle to fix installer processor issues
  settings.gradle
Labels: bug, regression, 1.20.6

#1033 [1.20.6] Fix FP precision issues of the particle bound debug renderer close to horizontal coordinate limits
  src/main/java/net/neoforged/neoforge/client/ParticleBoundsDebugRenderer.java
Labels: bug, rendering, 1.20.6

#672 [1.20.4/5] Improved ModMismatchDisconnectedScreen and clientside handling of channel mismatches in general
  src/main/java/net/neoforged/neoforge/client/gui/ModMismatchDisconnectedScreen.java
  src/main/java/net/neoforged/neoforge/network/negotiation/NetworkComponentNegotiator.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, 1.20, last call, 1.20.6

#1010 Add SwordItem createAttributes overload that takes float damage
  patches/net/minecraft/world/item/SwordItem.java.patch
Labels: enhancement, 1.20.6

#990 [1.20.6] Add ComponentItemHandler for using IItemHandlerModifiable with Data Components
  patches/net/minecraft/world/item/component/ItemContainerContents.java.patch
  src/main/java/net/neoforged/neoforge/capabilities/CapabilityHooks.java
  src/main/java/net/neoforged/neoforge/items/ComponentItemHandler.java
  src/main/java/net/neoforged/neoforge/items/ItemHandlerHelper.java
  src/main/java/net/neoforged/neoforge/items/ItemStackHandler.java
  src/main/java/net/neoforged/neoforge/items/wrapper/CombinedInvWrapper.java
  src/main/java/net/neoforged/neoforge/items/wrapper/EmptyItemHandler.java
  src/main/java/net/neoforged/neoforge/items/wrapper/EntityEquipmentInvWrapper.java
  src/main/java/net/neoforged/neoforge/items/wrapper/ShulkerItemStackInvWrapper.java
  tests/src/main/java/net/neoforged/neoforge/debug/capabilities/ItemInventoryTests.java
Labels: enhancement, 1.20.6

#985 [1.20.6] Add ComponentEnergyStorage for using IEnergyStorage with Data Components
  src/main/java/net/neoforged/neoforge/energy/ComponentEnergyStorage.java
  src/main/java/net/neoforged/neoforge/energy/EnergyStorage.java
  src/main/java/net/neoforged/neoforge/energy/IEnergyStorage.java
  tests/src/main/java/net/neoforged/neoforge/debug/capabilities/ItemEnergyTests.java
Labels: enhancement, 1.20.6

#976 [1.20.6] Add BlockTagIngredient for when a item tag cannot be used/doesn't exist
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/crafting/BlockTagIngredient.java
  tests/src/generated/resources/data/neotests_block_tag_ingredient/advancements/recipes/misc/block_tag.json
  tests/src/generated/resources/data/neotests_block_tag_ingredient/recipes/block_tag.json
  tests/src/main/java/net/neoforged/neoforge/debug/crafting/IngredientTests.java
Labels: enhancement, 1.20.6

#1009 Expose ItemEntity#target's value in ItemEntityPickupEvent
  patches/net/minecraft/world/entity/item/ItemEntity.java.patch
Labels: enhancement, 1.20.6
