Repository neoforged/NeoForge, pull requests merged in 2024-08, with the labels that each got.

#1404 [1.21] Fix HUD elements at high Z values vanishing when many elements are registered
  patches/net/minecraft/client/gui/Gui.java.patch
  patches/net/minecraft/client/renderer/PanoramaRenderer.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/gui/GuiLayerManager.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/GuiTests.java
Labels: bug, rendering, 1.21

#1381 Deprecate ScreenEvent.BackgroundRendered
  src/main/java/net/neoforged/neoforge/client/event/ScreenEvent.java
Labels: documentation, 1.21

#1369 Remove useless patched in blockEntity checks
  patches/net/minecraft/world/level/block/state/BlockBehaviour.java.patch
  patches/net/minecraft/world/level/chunk/LevelChunk.java.patch
Labels: cleanup, 1.21

#1383 Add warning for wrong mob category in biomes
  src/main/java/net/neoforged/neoforge/server/ServerLifecycleHooks.java
Labels: enhancement, 1.21

#1372 rename slimeball tag, melee tools adjustment, and fix entries for some biome and food tags
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/item/foods/fruit.json
  src/generated/resources/data/c/tags/item/foods/golden.json
  src/generated/resources/data/c/tags/item/foods/vegetable.json
  src/generated/resources/data/c/tags/item/slime_balls.json
  src/generated/resources/data/c/tags/item/slimeballs.json
  src/generated/resources/data/c/tags/item/tools/melee_weapon.json
  src/generated/resources/data/c/tags/worldgen/biome/is_cold/overworld.json
  src/main/java/net/neoforged/neoforge/common/TagConventionLogWarning.java
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBiomeTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: enhancement, 1.21, data driven

#1417 Fill deprecated Slimeballtag with entry again
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/item/slimeballs.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: regression, 1.21

#1413 Implement hashCode() on Ingredient.ItemValue
  patches/net/minecraft/world/item/crafting/Ingredient.java.patch
Labels: bug, 1.21

#1303 [1.21] Add `HolderLookup.Provider` param to `RecipeProvider#buildRecipes`
  tests/src/main/java/net/neoforged/neoforge/debug/crafting/IngredientTests.java
Labels: enhancement, 1.21, data driven

#1276 Use the real buffer data
  src/main/java/net/neoforged/neoforge/common/util/FriendlyByteBufUtil.java
Labels: bug, 1.21, networking

#1410 Update FML to allow sorting of `IDependencyLocator`s
  gradle.properties
Labels: enhancement, 1.21

#1378 New Crowdin updates
  src/main/resources/assets/neoforge/lang/cs_cz.json
  src/main/resources/assets/neoforge/lang/da_dk.json
  src/main/resources/assets/neoforge/lang/de_de.json
  src/main/resources/assets/neoforge/lang/en_gb.json
  src/main/resources/assets/neoforge/lang/eo_uy.json
  src/main/resources/assets/neoforge/lang/es_es.json
  src/main/resources/assets/neoforge/lang/et_ee.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/hu_hu.json
  src/main/resources/assets/neoforge/lang/it_it.json
  src/main/resources/assets/neoforge/lang/ja_jp.json
  src/main/resources/assets/neoforge/lang/ko_kr.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/pt_br.json
  src/main/resources/assets/neoforge/lang/pt_pt.json
  src/main/resources/assets/neoforge/lang/ro_ro.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/sk_sk.json
  src/main/resources/assets/neoforge/lang/tr_tr.json
  src/main/resources/assets/neoforge/lang/tt_ru.json
  src/main/resources/assets/neoforge/lang/uk_ua.json
  src/main/resources/assets/neoforge/lang/vi_vn.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_hk.json
Labels: l10n

#1402 Added modifier key states to TooltipFlag and Level to TooltipContext
  patches/net/minecraft/client/gui/screens/Screen.java.patch
  patches/net/minecraft/client/gui/screens/inventory/CreativeModeInventoryScreen.java.patch
  patches/net/minecraft/client/multiplayer/SessionSearchTrees.java.patch
  patches/net/minecraft/world/item/Item.java.patch
  patches/net/minecraft/world/item/TooltipFlag.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientTooltipFlag.java
Labels: enhancement, 1.21

#1363 Add PlayerEnchantItemEvent
  patches/net/minecraft/world/inventory/EnchantmentMenu.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/event/entity/player/PlayerEnchantItemEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/enchantment/EnchantmentLevelTests.java
Labels: enhancement, 1.21

#1334 Custom attribute level curve in MobEffect, restoring `getAttributeModifierValue`
  patches/net/minecraft/world/effect/MobEffect.java.patch
Labels: enhancement, 1.21

#1424 Silence logging for deprecated slimeball tag
  src/main/java/net/neoforged/neoforge/common/TagConventionLogWarning.java
Labels: bug, 1.21

#1416 Add Maty's GameTest gist into Neo repo
  docs/CONTRIBUTING.md
  docs/NEOGAMETESTS.md
  docs/README.md
  docs/TESTFRAMEWORK.md
Labels: documentation, 1.21

#1393 Enable keyboard navigation in mod list
  src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java
  src/main/java/net/neoforged/neoforge/client/gui/widget/ModListWidget.java
Labels: bug, 1.21

#1406 Waxing & Oxidizing DataMaps
  patches/net/minecraft/data/recipes/RecipeProvider.java.patch
  patches/net/minecraft/world/item/HoneycombItem.java.patch
  patches/net/minecraft/world/level/block/WeatheringCopper.java.patch
  src/generated/resources/data/neoforge/data_maps/block/oxidizables.json
  src/generated/resources/data/neoforge/data_maps/block/waxables.json
  src/main/java/net/neoforged/neoforge/common/DataMapHooks.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeDataMapsProvider.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/NeoForgeDataMaps.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/Oxidizable.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/Waxable.java
  tests/src/generated/resources/data/neoforge/data_maps/block/oxidizables.json
  tests/src/generated/resources/data/neoforge/data_maps/block/waxables.json
  tests/src/main/java/net/neoforged/neoforge/debug/data/DataMapTests.java
Labels: enhancement, 1.21, last call, data driven

#1433 [1.21] Fix IShearable
  patches/net/minecraft/world/entity/Entity.java.patch
  patches/net/minecraft/world/entity/animal/MushroomCow.java.patch
  patches/net/minecraft/world/entity/animal/Sheep.java.patch
  patches/net/minecraft/world/entity/animal/SnowGolem.java.patch
  patches/net/minecraft/world/entity/monster/Bogged.java.patch
  patches/net/minecraft/world/item/ShearsItem.java.patch
  src/main/java/net/neoforged/neoforge/common/IShearable.java
Labels: bug, cleanup, regression, 1.21

#1279 Patch MC-274244 to allow tagged items to be picked up by Farmers
  patches/net/minecraft/world/entity/npc/Villager.java.patch
Labels: 1.21, vanilla bug

#1412 [1.21] Add IItemExtension#supportsEnchantment
  patches/net/minecraft/server/commands/EnchantCommand.java.patch
  patches/net/minecraft/world/inventory/AnvilMenu.java.patch
  patches/net/minecraft/world/item/enchantment/Enchantment.java.patch
  patches/net/minecraft/world/level/storage/loot/functions/EnchantRandomlyFunction.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
Labels: enhancement, 1.21

#1190 [1.21] Add support for the `c:register` channel registration payload
  patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch
  patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch
  src/main/java/net/neoforged/neoforge/network/filters/NetworkFilters.java
  src/main/java/net/neoforged/neoforge/network/payload/CommonRegisterPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/CommonVersionPayload.java
  src/main/java/net/neoforged/neoforge/network/registration/ChannelAttributes.java
  src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java
Labels: enhancement, 1.21, networking

#1438 Add chorus fruit to `c:foods/fruit` tag
  src/generated/resources/data/c/tags/item/foods/fruit.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
Labels: enhancement, 1.21.1

#1432 Add more crops tag (Cocoa Beans, Cactus, Melon, Pumpkin, and Sugar Cane)
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/item/crops.json
  src/generated/resources/data/c/tags/item/crops/cactus.json
  src/generated/resources/data/c/tags/item/crops/cocoa_bean.json
  src/generated/resources/data/c/tags/item/crops/melon.json
  src/generated/resources/data/c/tags/item/crops/pumpkin.json
  src/generated/resources/data/c/tags/item/crops/sugar_cane.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: enhancement, 1.21

#1431 Deprecate DummySavedData for removal and remove associated patches
  patches/net/minecraft/world/level/storage/DimensionDataStorage.java.patch
  src/main/java/net/neoforged/neoforge/common/util/DummySavedData.java
Labels: bug, 1.21

#1436 Cleanup tag translation datagen code
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/LanguageProvider.java
Labels: bug, 1.21.1

#1214 Added method to make creating faces on models less annoying
  src/main/java/net/neoforged/neoforge/client/model/generators/ModelBuilder.java
Labels: enhancement, 1.21

#1425 Add `neoforge:overlays` field for cleaner conditional overlays in some use cases
  patches/net/minecraft/server/packs/OverlayMetadataSection.java.patch
  patches/net/minecraft/server/packs/repository/Pack.java.patch
  src/main/java/net/neoforged/neoforge/common/data/GeneratingOverlayMetadataSection.java
  src/main/java/net/neoforged/neoforge/resource/ResourcePackLoader.java
  tests/src/generated/resources/pack.mcmeta
  tests/src/main/java/net/neoforged/neoforge/debug/resources/OverlayTests.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/DataGeneratorTest.java
  tests/src/main/resources/data/neoforge_overlays_test/tags/block/must_be_overlayed.json
  tests/src/main/resources/data/pack_overlays_test/tags/block/must_be_overlayed.json
  tests/src/main/resources/neoforge_overlays_test/data/neoforge_overlays_test/tags/block/must_be_overlayed.json
Labels: enhancement, 1.21

#1452 Add QuadLighter#computeLightingForQuad overload that works with vertex data array
  src/main/java/net/neoforged/neoforge/client/model/lighting/QuadLighter.java
Labels: enhancement, rendering, 1.21.1

#1458 Fixed missing Range constructor in ModConfigSpec
  src/main/java/net/neoforged/neoforge/common/ModConfigSpec.java
Labels: bug, 1.21.1

#1262 Make `GlyphProviderType` enum extensible
  patches/net/minecraft/client/gui/font/providers/GlyphProviderType.java.patch
  tests/src/main/java/net/neoforged/neoforge/debug/client/CustomGlyphProviderTypeTest.java
  tests/src/main/resources/META-INF/enumextensions.json
  tests/src/main/resources/assets/custom_glyph_provider_type_test/font/vanilla.json
Labels: enhancement, 1.21

#1414 Add IClientItemExtensions methods for per-render-layer armor coloring
  patches/net/minecraft/client/renderer/entity/layers/HumanoidArmorLayer.java.patch
  src/main/java/net/neoforged/neoforge/client/extensions/common/IClientItemExtensions.java
Labels: enhancement, rendering, 1.21

#1471 [1.21.1] Fix wrong position being passed to IBlockStateExtension#isFireSource()
  patches/net/minecraft/world/level/block/FireBlock.java.patch
Labels: bug, 1.21.1

#1428 [1.21] Allow looking up a Dimensions translated name
  patches/net/minecraft/server/commands/ForceLoadCommand.java.patch
  patches/net/minecraft/server/commands/SetSpawnCommand.java.patch
  src/generated/resources/assets/c/lang/en_us.json
  src/main/java/net/neoforged/neoforge/common/data/LanguageProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
  src/main/java/net/neoforged/neoforge/common/extensions/ILevelExtension.java
  src/main/java/net/neoforged/neoforge/server/command/DimensionsCommand.java
  src/main/java/net/neoforged/neoforge/server/command/TPSCommand.java
  src/main/java/net/neoforged/neoforge/server/command/TimeSpeedCommand.java
Labels: enhancement, 1.21

#1477 Use raw stdout stream for CrashReportExtender
  src/main/java/net/neoforged/neoforge/logging/CrashReportExtender.java
Labels: bug, 1.21.1

#1418 [1.21] Add command for listing data components on held stack
  src/main/java/net/neoforged/neoforge/server/command/DataComponentCommand.java
  src/main/java/net/neoforged/neoforge/server/command/NeoForgeCommand.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, 1.21

#1480 Deprecate `BlockItem#removeFromBlockToItemMap` for removal
  patches/net/minecraft/world/item/BlockItem.java.patch
  patches/net/minecraft/world/item/Items.java.patch
  patches/net/minecraft/world/item/StandingAndWallBlockItem.java.patch
Labels: cleanup, 1.21.1

#1489 [1.21] Fix PayloadRegistrar constructor not copying the handler thread
  src/main/java/net/neoforged/neoforge/network/registration/PayloadRegistrar.java
Labels: bug, networking, 1.21.1

#1491 Fix rare NPE in CapabilityListenerHolder
  src/main/java/net/neoforged/neoforge/capabilities/CapabilityListenerHolder.java
Labels: bug, 1.21.1

#1488 [1.21] Add NamespacedDirectoryLister
  patches/net/minecraft/resources/FileToIdConverter.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java
  src/main/java/net/neoforged/neoforge/client/event/RegisterSpriteSourceTypesEvent.java
  src/main/java/net/neoforged/neoforge/client/textures/NamespacedDirectoryLister.java
  testframework/src/main/java/net/neoforged/testframework/impl/TestFrameworkImpl.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/ClientTests.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/client/CustomSpriteSourceTest.java
  tests/src/main/resources/assets/minecraft/atlases/blocks.json
  tests/src/main/resources/assets/neotests_dir_list_absent/textures/test/dir_list_test_absent.png
  tests/src/main/resources/assets/neotests_dir_list_present/textures/test/dir_list_test_present.png
Labels: enhancement, rendering, 1.21.1

#1481 Replace CRLF line endings in mod list's details
  src/main/java/net/neoforged/neoforge/client/gui/ModListScreen.java
Labels: bug, 1.21.1

#1479 Enhance readability of mod loading crash reports
  patches/net/minecraft/CrashReportCategory.java.patch
  src/main/java/net/neoforged/neoforge/logging/CrashReportExtender.java
Labels: enhancement, 1.21.1

#1422 [1.21] Overhaul tps command to be more colorful and organized
  src/main/java/net/neoforged/neoforge/server/command/TPSCommand.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, 1.21

#1451 [1.21] Add a system to register custom ReceivingLevelScreens
  patches/net/minecraft/client/Minecraft.java.patch
  patches/net/minecraft/client/multiplayer/ClientPacketListener.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/DimensionTransitionScreenManager.java
  src/main/java/net/neoforged/neoforge/client/event/RegisterDimensionTransitionScreenEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/DimensionTransitionScreenTests.java
Labels: enhancement, rendering, 1.21.1

#1483 [1.21] Implement common networking with config tasks
  patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch
  patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch
  src/main/java/net/neoforged/neoforge/network/ConfigurationInitialization.java
  src/main/java/net/neoforged/neoforge/network/configuration/CommonRegisterTask.java
  src/main/java/net/neoforged/neoforge/network/configuration/CommonVersionTask.java
  src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java
Labels: bug, networking, 1.21.1
