Repository neoforged/NeoForge, pull requests merged in 2025-03, with the labels that each got.

#1985 Update FML to 6.0.11
  gradle.properties
Labels: 1.21.4

#1986 Update FML to 4.0.38
  gradle.properties
Labels: 1.21.1

#1681 Un-hardcode multiple `canFireProjectile` methods
  patches/net/minecraft/world/entity/monster/AbstractSkeleton.java.patch
  patches/net/minecraft/world/entity/monster/Pillager.java.patch
  patches/net/minecraft/world/entity/monster/piglin/Piglin.java.patch
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/neoforge/tags/item/piglin_usable_crossbows.json
  src/generated/resources/data/neoforge/tags/item/pillager_usable_crossbows.json
  src/generated/resources/data/neoforge/tags/item/skeleton_usable_bows.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: enhancement, 1.21.3

#1994 [1.21.4] Register Particle Types before blocks and mob effects
  src/generated/resources/reports/registry_order.json
  src/main/java/net/neoforged/neoforge/registries/GameData.java
Labels: bug, vanilla bug, 1.21.4

#1995 [1.21.4] Use Thread-Safe Collections and Maps for Key Mappings
  patches/net/minecraft/client/KeyMapping.java.patch
  src/main/java/net/neoforged/neoforge/client/settings/KeyMappingLookup.java
Labels: bug, 1.21.4

#1970 Expose target mod IDs in GatherDataEvent
  src/main/java/net/neoforged/neoforge/data/event/GatherDataEvent.java
Labels: enhancement, 1.21.1

#1990 Respect attribute debug info setting for base modifiers
  src/main/java/net/neoforged/neoforge/common/extensions/IAttributeExtension.java
Labels: bug, 1.21.4

#1624 [1.21.3] Add method to allow building custom DataGenerator.PackGenerator instances
  patches/net/minecraft/data/DataGenerator.java.patch
Labels: enhancement, 1.21.4

#2008 Update Javadoc of IClientBlockExtensions and IClientFluidTypeExtensions
  src/main/java/net/neoforged/neoforge/client/extensions/common/IClientBlockExtensions.java
  src/main/java/net/neoforged/neoforge/client/extensions/common/IClientFluidTypeExtensions.java
Labels: 1.21.4

#2007 Fix wrong BE#getModelData javadoc
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockEntityExtension.java
Labels: 1.21.4

#2013 Add a method to get the registry name of an element, that returns null from defaulted registries when not present
  patches/net/minecraft/core/DefaultedMappedRegistry.java.patch
  src/main/java/net/neoforged/neoforge/registries/IRegistryExtension.java
Labels: 1.21.4

#1975 Add fallbacks to all command translation strings
  src/main/java/net/neoforged/neoforge/server/command/CommandUtils.java
  src/main/java/net/neoforged/neoforge/server/command/ConfigCommand.java
  src/main/java/net/neoforged/neoforge/server/command/DataComponentCommand.java
  src/main/java/net/neoforged/neoforge/server/command/DimensionsCommand.java
  src/main/java/net/neoforged/neoforge/server/command/DumpCommand.java
  src/main/java/net/neoforged/neoforge/server/command/EntityCommand.java
  src/main/java/net/neoforged/neoforge/server/command/EnumArgument.java
  src/main/java/net/neoforged/neoforge/server/command/GenerateCommand.java
  src/main/java/net/neoforged/neoforge/server/command/ModListCommand.java
  src/main/java/net/neoforged/neoforge/server/command/TPSCommand.java
  src/main/java/net/neoforged/neoforge/server/command/TagsCommand.java
  src/main/java/net/neoforged/neoforge/server/command/TimeSpeedCommand.java
  src/main/java/net/neoforged/neoforge/server/command/TrackCommand.java
  src/main/java/net/neoforged/neoforge/server/command/generation/GenerationBar.java
Labels: enhancement, 1.21.4

#2009 Add support for modded tridents to trigger the thrown trident advancement
  src/generated/resources/data/minecraft/advancement/adventure/throw_trident.json
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/advancements/critereon/TridentEntityPredicate.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeAdvancementProvider.java
Labels: enhancement, 1.21.4

#1993 Add Pumpkin Block and Item Tags
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/block/pumpkins.json
  src/generated/resources/data/c/tags/block/pumpkins/carved.json
  src/generated/resources/data/c/tags/block/pumpkins/jack_o_lanterns.json
  src/generated/resources/data/c/tags/block/pumpkins/normal.json
  src/generated/resources/data/c/tags/item/pumpkins.json
  src/generated/resources/data/c/tags/item/pumpkins/carved.json
  src/generated/resources/data/c/tags/item/pumpkins/jack_o_lanterns.json
  src/generated/resources/data/c/tags/item/pumpkins/normal.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: enhancement, 1.21.4

#1999 [1.21.4] Add Post Attack Invulnerability Reduction
  patches/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/neoforged/neoforge/common/damagesource/DamageContainer.java
Labels: bug, 1.21.4

#2014 [1.21.4] Add support for double modifier keybinds
  patches/net/minecraft/client/KeyMapping.java.patch
  patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch
  src/main/java/net/neoforged/neoforge/client/settings/KeyMappingLookup.java
  src/main/java/net/neoforged/neoforge/client/settings/KeyModifier.java
Labels: bug, 1.21.4

#1967 New Crowdin updates
  src/main/resources/assets/neoforge/lang/cs_cz.json
  src/main/resources/assets/neoforge/lang/da_dk.json
  src/main/resources/assets/neoforge/lang/de_de.json
  src/main/resources/assets/neoforge/lang/en_gb.json
  src/main/resources/assets/neoforge/lang/eo_uy.json
  src/main/resources/assets/neoforge/lang/es_es.json
  src/main/resources/assets/neoforge/lang/et_ee.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/hu_hu.json
  src/main/resources/assets/neoforge/lang/it_it.json
  src/main/resources/assets/neoforge/lang/ja_jp.json
  src/main/resources/assets/neoforge/lang/ko_kr.json
  src/main/resources/assets/neoforge/lang/ms_my.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/pt_br.json
  src/main/resources/assets/neoforge/lang/pt_pt.json
  src/main/resources/assets/neoforge/lang/ro_ro.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/sk_sk.json
  src/main/resources/assets/neoforge/lang/tr_tr.json
  src/main/resources/assets/neoforge/lang/tt_ru.json
  src/main/resources/assets/neoforge/lang/uk_ua.json
  src/main/resources/assets/neoforge/lang/vi_vn.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_tw.json
Labels: l10n, 1.21.4

#1856 New Crowdin updates
  src/main/resources/assets/neoforge/lang/it_it.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/uk_ua.json
  src/main/resources/assets/neoforge/lang/zh_tw.json
Labels: l10n, 1.20.6

#2033 [1.21.4] Release all keys when key or modifier is released
  src/main/java/net/neoforged/neoforge/client/settings/KeyMappingLookup.java
Labels: bug, regression, 1.21.4

#1855 [1.21.4] Recipe priority system for solving overlaps in recipe ingredients and patterns.
  patches/net/minecraft/world/item/crafting/RecipeManager.java.patch
  patches/net/minecraft/world/item/crafting/RecipeMap.java.patch
  src/main/java/net/neoforged/neoforge/common/NeoForgeEventHandler.java
  src/main/java/net/neoforged/neoforge/common/crafting/RecipePriorityManager.java
  src/main/java/net/neoforged/neoforge/common/data/RecipePrioritiesProvider.java
  src/main/java/net/neoforged/neoforge/resource/NeoForgeReloadListeners.java
  tests/src/generated/resources/data/neotests_recipe_priorities/advancement/recipes/misc/higher_priority_test.json
  tests/src/generated/resources/data/neotests_recipe_priorities/recipe/higher_priority_test.json
  tests/src/generated/resources/data/neotests_recipe_priorities/recipe_priorities.json
  tests/src/main/java/net/neoforged/neoforge/debug/crafting/RecipePrioritiesTest.java
Labels: 1.21.4

#2024 Fix `ParametrizedGameTestSequence` swallowing exceptions
  testframework/src/main/java/net/neoforged/testframework/gametest/ParametrizedGameTestSequence.java
Labels: bug, 1.21.4

#2034 [1.21.4] Re-implement item re-equip animation hook
  patches/net/minecraft/client/renderer/ItemInHandRenderer.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
Labels: bug, rendering, regression, 1.21.4

#2040 Forbid access narrowing with patches
  build.gradle
Labels: ci/build, 1.21.5

#2050 [1.21.5] Add pipeline modifier system
  patches/com/mojang/blaze3d/opengl/GlRenderPass.java.patch
  patches/com/mojang/blaze3d/pipeline/RenderPipeline.java.patch
  patches/com/mojang/blaze3d/systems/RenderSystem.java.patch
  src/client/java/net/neoforged/neoforge/client/ClientHooks.java
  src/client/java/net/neoforged/neoforge/client/pipeline/PipelineModifier.java
  src/client/java/net/neoforged/neoforge/client/pipeline/PipelineModifierStack.java
  src/client/java/net/neoforged/neoforge/client/pipeline/PipelineModifiers.java
  src/client/java/net/neoforged/neoforge/client/pipeline/RegisterPipelineModifiersEvent.java
  src/client/java/net/neoforged/neoforge/client/pipeline/package-info.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/client/rendering/StencilEnableTest.java
Labels: enhancement, rendering

#2067 Fix damage-blocking items not working
  patches/net/minecraft/world/entity/LivingEntity.java.patch
Labels: bug, regression, 1.21.5

#2070 Backport to 1.21.1: Add system prop to runs to enable terminal colors
  projects/neoforge/build.gradle
Labels: 1.21.1

#2074 Add brown and blue eggs to `c:eggs` and added missing flowers to `c` flower tags
  src/generated/resources/data/c/tags/block/flowers.json
  src/generated/resources/data/c/tags/item/eggs.json
  src/generated/resources/data/c/tags/item/flowers.json
  src/main/java/net/neoforged/neoforge/common/TagConventionLogWarning.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBiomeTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
Labels: bug, cleanup, 1.21.5

#2076 [1.21.5] Further clean up source split
  patches/net/minecraft/client/data/Main.java.patch
  patches/net/minecraft/data/Main.java.patch
  patches/net/minecraft/server/dedicated/DedicatedServer.java.patch
  patches/net/minecraft/world/level/Level.java.patch
  patches/net/minecraft/world/level/chunk/LevelChunk.java.patch
  src/client/java/net/neoforged/neoforge/client/ClientHooks.java
  src/client/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java
  src/client/java/net/neoforged/neoforge/client/TagConventionLogWarningClient.java
  src/client/java/net/neoforged/neoforge/client/config/NeoForgeClientConfig.java
  src/client/java/net/neoforged/neoforge/client/config/package-info.java
  src/client/java/net/neoforged/neoforge/client/gui/ConfigurationScreen.java
  src/client/java/net/neoforged/neoforge/client/internal/NeoForgeClientProxy.java
  src/client/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/client/java/net/neoforged/neoforge/client/model/lighting/LightPipelineAwareModelBlockRenderer.java
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeConfig.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/TagConventionLogWarning.java
  src/main/java/net/neoforged/neoforge/common/config/NeoForgeCommonConfig.java
  src/main/java/net/neoforged/neoforge/common/config/NeoForgeServerConfig.java
  src/main/java/net/neoforged/neoforge/common/config/package-info.java
  src/main/java/net/neoforged/neoforge/common/extensions/IAttributeExtension.java
  src/main/java/net/neoforged/neoforge/data/event/GatherDataEvent.java
  src/main/java/net/neoforged/neoforge/data/loading/DatagenModLoader.java
  src/main/java/net/neoforged/neoforge/internal/NeoForgeProxy.java
  src/main/java/net/neoforged/neoforge/server/permission/PermissionAPI.java
Labels: cleanup, breaking change, 1.21.5

#2071 Bump FML to 7.0.10
  gradle.properties
Labels: enhancement, dependencies, 1.21.5

#2075 [1.21.5] Improve custom blockstate model datagen
  patches/net/minecraft/client/data/models/MultiVariant.java.patch
  src/client/java/net/neoforged/neoforge/client/model/generators/blockstate/CompositeBlockStateModelBuilder.java
  src/client/java/net/neoforged/neoforge/client/model/generators/blockstate/CustomBlockStateModelBuilder.java
Labels: enhancement, rendering, breaking change, data driven, 1.21.5

#2036 Reimplement hook for IItemExtension#getSweepHitBox
  patches/net/minecraft/world/entity/player/Player.java.patch
Labels: bug, regression, 1.21.5

#2072 No longer ship the Nashorn JS Engine for JS Coremods
  gradle.properties
  projects/neoforge/build.gradle
Labels: cleanup, 1.21.5
