Repository neoforged/NeoForge, pull requests merged in 2025-08, with the labels that each got.

#2524 [1.21.8] Add stack-aware overload of Item#canFitInsideContainerItems()
  patches/net/minecraft/world/inventory/ShulkerBoxSlot.java.patch
  patches/net/minecraft/world/item/Item.java.patch
  patches/net/minecraft/world/item/component/BundleContents.java.patch
  patches/net/minecraft/world/level/block/entity/ShulkerBoxBlockEntity.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
  src/main/java/net/neoforged/neoforge/items/ComponentItemHandler.java
Labels: enhancement, 1.21.8

#2450 New Crowdin updates
  src/main/resources/assets/neoforge/lang/cs_cz.json
  src/main/resources/assets/neoforge/lang/da_dk.json
  src/main/resources/assets/neoforge/lang/de_de.json
  src/main/resources/assets/neoforge/lang/en_gb.json
  src/main/resources/assets/neoforge/lang/eo_uy.json
  src/main/resources/assets/neoforge/lang/es_es.json
  src/main/resources/assets/neoforge/lang/et_ee.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/hu_hu.json
  src/main/resources/assets/neoforge/lang/it_it.json
  src/main/resources/assets/neoforge/lang/ja_jp.json
  src/main/resources/assets/neoforge/lang/ko_kr.json
  src/main/resources/assets/neoforge/lang/ms_my.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/pt_br.json
  src/main/resources/assets/neoforge/lang/pt_pt.json
  src/main/resources/assets/neoforge/lang/ro_ro.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/sk_sk.json
  src/main/resources/assets/neoforge/lang/tr_tr.json
  src/main/resources/assets/neoforge/lang/tt_ru.json
  src/main/resources/assets/neoforge/lang/uk_ua.json
  src/main/resources/assets/neoforge/lang/vi_vn.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_tw.json
Labels: l10n, 1.21.7

#2414 Transfer: Transactions Review
  src/main/java/net/neoforged/neoforge/transfer/ResourceHandlerDeprecationHandling.java
  src/main/java/net/neoforged/neoforge/transfer/package-info.java
  src/main/java/net/neoforged/neoforge/transfer/transaction/SnapshotJournal.java
  src/main/java/net/neoforged/neoforge/transfer/transaction/Transaction.java
  src/main/java/net/neoforged/neoforge/transfer/transaction/TransactionContext.java
  src/main/java/net/neoforged/neoforge/transfer/transaction/TransactionManager.java
  src/main/java/net/neoforged/neoforge/transfer/transaction/package-info.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/transfer/TransactionTests.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/transfer/package-info.java
Labels: 1.21.7

#2513 Add displayItems(Collection<Holder>) helper to CreativeModeTab.Builder for use with DeferredRegisters
  patches/net/minecraft/world/item/CreativeModeTab.java.patch
Labels: 1.21.8

#2580 Backport spyglass item ability
  patches/net/minecraft/client/gui/Gui.java.patch
  patches/net/minecraft/client/renderer/entity/layers/PlayerItemInHandLayer.java.patch
  patches/net/minecraft/world/entity/player/Player.java.patch
  patches/net/minecraft/world/item/SpyglassItem.java.patch
  src/main/java/net/neoforged/neoforge/client/extensions/common/IClientItemExtensions.java
  src/main/java/net/neoforged/neoforge/common/ItemAbilities.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, 1.21.1

#2593 Add tests for transfer handlers and utils
  src/main/java/net/neoforged/neoforge/transfer/ResourceHandlerUtil.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/transfer/CombinedResourceHandlerTest.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/transfer/EmptyResourceHandlerTest.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/transfer/HandlerTestUtil.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/transfer/MockResourceHandler.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/transfer/RangedResourceHandlerTest.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/transfer/ResourceHandlerUtilTest.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/transfer/TestResource.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/transfer/VoidingResourceHandlerTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/transfer/resources/TestElementResource.java
  tests/src/main/java/net/neoforged/neoforge/debug/transfer/resources/package-info.java
Labels: 1.21.7

#2459 Unload server configs after disconnecting from server
  src/client/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java
Labels: bug, 1.21.8

#2505 [1.21.1] Un-hardcode lightning rods
  patches/net/minecraft/server/level/ServerLevel.java.patch
  patches/net/minecraft/world/entity/LightningBolt.java.patch
Labels: enhancement, 1.21.1
