Repository neoforged/NeoForge, pull requests merged in 2025-05, with the labels that each got.

#2262 Backport to 1.21.1: Prevent BlockCapabilityCache keeping capability references for too long.
  src/main/java/net/neoforged/neoforge/capabilities/BlockCapabilityCache.java
Labels: 1.21.1

#2289 Add AT entries for VillagerTrades Factories
  src/main/resources/META-INF/accesstransformer.cfg
Labels: 1.21.1

#2276 Add source entity to MobEffectEvent.Applicable
  patches/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/event/entity/living/MobEffectEvent.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/PotionEventTest.java
Labels: 1.21.5

#2284 [1.21.5] Allow blocks full control over step, fall and hit sounds
  patches/net/minecraft/client/multiplayer/MultiPlayerGameMode.java.patch
  patches/net/minecraft/world/entity/Entity.java.patch
  patches/net/minecraft/world/entity/LivingEntity.java.patch
  src/client/java/net/neoforged/neoforge/client/extensions/common/IClientBlockExtensions.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockStateExtension.java
Labels: enhancement, 1.21.5

#2260 [1.21.x] Refactor the Anvil Events
  build.gradle
  patches/net/minecraft/world/inventory/AnvilMenu.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java
  src/main/java/net/neoforged/neoforge/event/AnvilUpdateEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/player/AnvilCraftEvent.java
  src/main/java/net/neoforged/neoforge/event/entity/player/AnvilRepairEvent.java
  tests/src/main/java/net/neoforged/neoforge/debug/crafting/AnvilUpdateEventTests.java
Labels: enhancement, breaking change, blocks stable, 1.21.5
