Repository neoforged/NeoForge, pull requests merged in 2025-01, with the labels that each got.

#1817 Explicitly upgrade slf4j to allow MDG usage
  gradle.properties
  projects/neoforge/build.gradle
Labels: 1.20.4

#1819 Properly resolve the parent in composite models
  src/main/java/net/neoforged/neoforge/client/model/UnbakedCompositeModel.java
Labels: regression, 1.21.4

#1787 Let vanilla try to handle Container interactions before checking for item handlers
  patches/net/minecraft/world/level/block/CrafterBlock.java.patch
  patches/net/minecraft/world/level/block/DropperBlock.java.patch
  patches/net/minecraft/world/level/block/entity/HopperBlockEntity.java.patch
  src/main/java/net/neoforged/neoforge/items/ContainerOrHandler.java
  src/main/java/net/neoforged/neoforge/items/VanillaHopperItemHandler.java
  src/main/java/net/neoforged/neoforge/items/VanillaInventoryCodeHooks.java
Labels: bug, 1.21.4

#1827 Fix custom bows being unusable by monsters extending `AbstractSkeleton`
  patches/net/minecraft/world/entity/monster/AbstractSkeleton.java.patch
Labels: regression, 1.21.4

#1779 New Crowdin updates
  src/main/resources/assets/neoforge/lang/ms_my.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/uk_ua.json
Labels: l10n, 1.21.4

#1846 Add item capability for decorated pots
  src/main/java/net/neoforged/neoforge/capabilities/CapabilityHooks.java
Labels: enhancement, 1.21.4

#1826 Add a display name extension to `KeyMapping`
  patches/net/minecraft/client/gui/screens/options/controls/KeyBindsList.java.patch
  src/main/java/net/neoforged/neoforge/client/extensions/IKeyMappingExtension.java
Labels: enhancement, 1.21.4

#1849 Add an extension to `KeyMapping` to customise the display name
  patches/net/minecraft/client/gui/screens/options/controls/KeyBindsList.java.patch
  src/main/java/net/neoforged/neoforge/client/extensions/IKeyMappingExtension.java
Labels: enhancement, backport, 1.21.1

#1825 Add `c:flowers`, `c:flowers/tall`, and `c:flowers/small` block and item tags
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/block/flowers.json
  src/generated/resources/data/c/tags/block/flowers/small.json
  src/generated/resources/data/c/tags/block/flowers/tall.json
  src/generated/resources/data/c/tags/item/flowers.json
  src/generated/resources/data/c/tags/item/flowers/small.json
  src/generated/resources/data/c/tags/item/flowers/tall.json
  src/main/java/net/neoforged/neoforge/common/TagConventionLogWarning.java
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: enhancement, 1.21.4

#1843 Patch methods in `EquipmentModelProvider` to be more mod compatible
  patches/net/minecraft/client/data/models/EquipmentAssetProvider.java.patch
Labels: bug, 1.21.4

#1851 [1.21.4] Fix `TagsCommand` tag cast error
  src/main/java/net/neoforged/neoforge/server/command/TagsCommand.java
Labels: bug, 1.21.4

#1837 [1.21.4] Fix IClientItemExtensions#renderHelmetOverlay never being called
  patches/net/minecraft/client/gui/Gui.java.patch
  src/main/java/net/neoforged/neoforge/client/extensions/common/IClientItemExtensions.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/ClientTests.java
Labels: 1.21.4

#1806 Only fire gather data events for the mods enabled
  src/main/java/net/neoforged/neoforge/data/event/GatherDataEvent.java
  src/main/java/net/neoforged/neoforge/data/loading/DatagenModLoader.java
Labels: enhancement, needs rebase, 1.21.4

#1830 Restore ability to enable stenciling
  patches/com/mojang/blaze3d/pipeline/MainTarget.java.patch
  patches/com/mojang/blaze3d/pipeline/RenderTarget.java.patch
  patches/com/mojang/blaze3d/pipeline/TextureTarget.java.patch
  patches/com/mojang/blaze3d/resource/RenderTargetDescriptor.java.patch
  patches/net/minecraft/client/Minecraft.java.patch
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/ConfigureMainRenderTargetEvent.java
  src/main/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeConfig.java
  src/main/resources/assets/neoforge/lang/en_us.json
  tests/src/main/java/net/neoforged/neoforge/oldtest/client/rendering/StencilEnableTest.java
Labels: 1.21.4

#1854 Add EntityType DeferredRegister
  src/main/java/net/neoforged/neoforge/registries/DeferredRegister.java
  testframework/src/main/java/net/neoforged/testframework/registration/DeferredEntityTypes.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/EntityDataSerializerTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/EntityTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/vehicle/CustomBoatTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/item/ItemTests.java
Labels: 1.21.4

#1793 Release bed POI if villager child spawn is blocked
  patches/net/minecraft/world/entity/ai/behavior/VillagerMakeLove.java.patch
Labels: bug, 1.21.4

#1873 Fix global block entities not being updated for empty sections
  patches/net/minecraft/client/renderer/chunk/SectionRenderDispatcher.java.patch
Labels: bug, backport, vanilla bug, 1.21.1

#1874 Bump FML
  gradle.properties
Labels: 1.21.4

#1876 Backport FML Bump with conditional mixins
  gradle.properties
Labels: 1.21.1

#1872 Use the minecraft-dependencies BOM for deps
  buildSrc/build.gradle
  coremods/build.gradle
  coremods/settings.gradle
  gradle.properties
  projects/neoforge/build.gradle
  settings.gradle
Labels: ci/build, 1.21.4

#1878 Generate ATs for villager `ItemListing`s
  projects/neoforge/build.gradle
  src/main/resources/META-INF/accesstransformergenerated.cfg
Labels: enhancement, 1.21.4

#1885 Move patched code to iface injection
  patches/net/minecraft/client/renderer/chunk/SectionRenderDispatcher.java.patch
  src/main/resources/META-INF/injected-interfaces.json
Labels: 1.21.4

#1864 Add tagkey for `c:tools/wrench`
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/item/tools.json
  src/generated/resources/data/c/tags/item/tools/wrench.json
  src/main/java/net/neoforged/neoforge/common/TagConventionLogWarning.java
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: bug, enhancement, 1.21.4

#1860 Add a seed tag for Pitcher Plants
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/item/seeds.json
  src/generated/resources/data/c/tags/item/seeds/pitcher_plant.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
Labels: enhancement, 1.21.4

#1893 Use custom composite checkout action and fix builds
  .github/workflows/build-prs.yml
  .github/workflows/check-local-changes.yml
  .github/workflows/test-prs.yml
Labels: ci/build, 1.21.4

#1894 Use custom composite checkout action and fix builds
  .github/workflows/build-prs.yml
  .github/workflows/check-local-changes.yml
  .github/workflows/test-prs.yml
Labels: ci/build, 1.21.1

#1886 Fix data map removals being required to exist
  src/main/java/net/neoforged/neoforge/registries/DataMapLoader.java
Labels: bug, data driven, 1.21.4

#1836 [1.21.1] Fix IClientItemExtensions#renderHelmetOverlay never being called
  patches/net/minecraft/client/gui/Gui.java.patch
  src/main/java/net/neoforged/neoforge/client/extensions/common/IClientItemExtensions.java
Labels: bug, 1.21.1

#1875 Patch `EmeraldsForVillagerTypeItem` to allow modders to make Custom `VillagerType`s
  patches/net/minecraft/world/entity/npc/VillagerTrades.java.patch
Labels: 1.21.4

#1882 [1.21.4] Add Datagen Helper for Creating Modded Datapack Registry Objects
  src/main/java/net/neoforged/neoforge/data/event/GatherDataEvent.java
Labels: data driven, 1.21.4

#1924 Add `genPatches` task alias to 1.21.1
  projects/neoforge/build.gradle
Labels: ci/build, 1.21.1

#1922 Fix entity movement in custom fluid types
  patches/net/minecraft/world/entity/LivingEntity.java.patch
Labels: bug, regression, 1.21.4

#1923 Cleanup cross-project dependencies
  buildSrc/src/main/java/net/neoforged/neodev/NeoDevConfigurations.java
  projects/neoforge/build.gradle
  testframework/build.gradle
  tests/build.gradle
Labels: cleanup, ci/build, 1.21.4
