Repository neoforged/NeoForge, pull requests merged in 2025-02, with the labels that each got.

#1879 Add a biome villager types data map to replace `VillagerType#BY_BIOME`
  patches/net/minecraft/world/entity/npc/VillagerType.java.patch
  src/generated/resources/data/neoforge/data_maps/worldgen/biome/villager_types.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeDataMapsProvider.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/BiomeVillagerType.java
  src/main/java/net/neoforged/neoforge/registries/datamaps/builtin/NeoForgeDataMaps.java
Labels: enhancement, data driven, 1.21.4

#1928 Fix ClientCommandSourceStack crashing or returning improper values for certain method calls
  src/main/java/net/neoforged/neoforge/client/ClientCommandSourceStack.java
Labels: bug, regression, 1.21.4

#1939 Fix note block interaction causing doubled note increase
  patches/net/minecraft/world/level/block/NoteBlock.java.patch
Labels: bug, regression, 1.21.4

#1936 [1.21.4] Reimplement `EntityRenderersEvent.CreateSkullModels`
  patches/net/minecraft/client/renderer/blockentity/SkullBlockRenderer.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/event/EntityRenderersEvent.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/block/CustomHeadTest.java
  tests/src/main/resources/assets/custom_head_test/items/blaze_head.json
Labels: bug, rendering, regression, breaking change, 1.21.4

#1937 Workaround for Eclipse not picking up cross-project compileOnly dependencies
  testframework/build.gradle
Labels: 1.21.4

#1915 [1.21.x] Topologically sort reload listeners based on dependency ordering
  patches/net/minecraft/server/ReloadableServerResources.java.patch
  patches/net/minecraft/server/packs/resources/ReloadableResourceManager.java.patch
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
  src/main/java/net/neoforged/neoforge/client/ClientNeoForgeMod.java
  src/main/java/net/neoforged/neoforge/client/event/AddClientReloadListenersEvent.java
  src/main/java/net/neoforged/neoforge/client/event/RegisterClientReloadListenersEvent.java
  src/main/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/main/java/net/neoforged/neoforge/client/model/UnbakedModelLoader.java
  src/main/java/net/neoforged/neoforge/client/resources/VanillaClientListeners.java
  src/main/java/net/neoforged/neoforge/client/resources/package-info.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeEventHandler.java
  src/main/java/net/neoforged/neoforge/common/util/VanillaClassToKey.java
  src/main/java/net/neoforged/neoforge/event/AddReloadListenerEvent.java
  src/main/java/net/neoforged/neoforge/event/AddServerReloadListenersEvent.java
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/SortedReloadListenerEvent.java
  src/main/java/net/neoforged/neoforge/resource/NeoForgeReloadListeners.java
  src/main/java/net/neoforged/neoforge/resource/ReloadListenerSort.java
  src/main/java/net/neoforged/neoforge/resource/VanillaServerListeners.java
  src/main/resources/META-INF/accesstransformer.cfg
  tests/src/main/java/net/neoforged/neoforge/debug/client/CustomGlyphProviderTypeTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/TextureAtlasTests.java
Labels: enhancement, 1.21.4

#1934 [1.21.4] Revert Registries to Frozen on Disconnect when a connection is present
  patches/net/minecraft/client/Minecraft.java.patch
  patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch
  src/main/java/net/neoforged/neoforge/server/ServerLifecycleHooks.java
Labels: bug, 1.21.4

#1909 Fix api name in comments of `BlockBehavior`
  patches/net/minecraft/world/level/block/state/BlockBehaviour.java.patch
Labels: 1.21.4

#1949 [1.21.4] Display correct relative position as used in GameTestHelper#relativePos
  patches/net/minecraft/gametest/framework/TestCommand.java.patch
Labels: vanilla bug, 1.21.4

#1796 move SavedData.save to IO worker to avoid synchronous IO on main thread
  patches/net/minecraft/server/level/ServerLevel.java.patch
  patches/net/minecraft/util/worldupdate/WorldUpgrader.java.patch
  patches/net/minecraft/world/level/saveddata/SavedData.java.patch
  src/main/java/net/neoforged/neoforge/common/IOUtilities.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/IOUtilitiesWorkerTest.java
Labels: 1.21.1

#1953 Avoid swallowing errors in case of AttachmentType Serialization failure
  src/main/java/net/neoforged/neoforge/attachment/AttachmentHolder.java
  src/main/java/net/neoforged/neoforge/attachment/AttachmentType.java
Labels: 1.21.4

#1960 Add back missing AbstractVillager.teleport method
  patches/net/minecraft/world/entity/npc/AbstractVillager.java.patch
Labels: regression, 1.21.4

#1959 Egg tag docs and recipe hookup
  src/generated/resources/data/minecraft/recipe/cake.json
  src/generated/resources/data/minecraft/recipe/pumpkin_pie.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeRecipeProvider.java
Labels: enhancement, 1.21.4

#1593 [1.21.1] Sync remaining `c` tags from Fabric side
  src/generated/resources/assets/c/lang/en_us.json
  src/generated/resources/data/c/tags/block/stripped_woods.json
  src/generated/resources/data/c/tags/item/potions.json
  src/generated/resources/data/c/tags/item/potions/bottle.json
  src/generated/resources/data/c/tags/item/seeds.json
  src/generated/resources/data/c/tags/item/seeds/torchflower.json
  src/generated/resources/data/c/tags/item/stripped_woods.json
  src/generated/resources/data/c/tags/worldgen/biome/is_cold.json
  src/generated/resources/data/c/tags/worldgen/biome/is_dense_vegetation.json
  src/generated/resources/data/c/tags/worldgen/biome/is_hot.json
  src/generated/resources/data/c/tags/worldgen/biome/is_hot/overworld.json
  src/generated/resources/data/c/tags/worldgen/biome/is_sparse_vegetation.json
  src/generated/resources/data/c/tags/worldgen/biome/is_temperate.json
  src/generated/resources/data/c/tags/worldgen/biome/is_temperate/end.json
  src/generated/resources/data/c/tags/worldgen/biome/is_temperate/nether.json
  src/generated/resources/data/c/tags/worldgen/biome/is_temperate/overworld.json
  src/generated/resources/data/c/tags/worldgen/biome/is_wet.json
  src/generated/resources/data/minecraft/recipe/cake.json
  src/generated/resources/data/minecraft/recipe/pumpkin_pie.json
  src/main/java/net/neoforged/neoforge/common/Tags.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBiomeTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLanguageProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeRecipeProvider.java
Labels: 1.21.1

#1954 Hanging Pale Moss not dropping with modded shears
  src/generated/resources/data/minecraft/loot_table/blocks/pale_hanging_moss.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeLootTableProvider.java
Labels: 1.21.4

#1952 Backported DataMapProvider#gather overload passing the registry provider
  src/main/java/net/neoforged/neoforge/common/data/DataMapProvider.java
Labels: 1.21.1

#1966 Add intrusive holder support to RegistryBuilder
  src/main/java/net/neoforged/neoforge/registries/RegistryBuilder.java
Labels: 1.21.4

#1977 Crash with a better exception when encountering an off-thread GL error
  patches/com/mojang/blaze3d/platform/Window.java.patch
Labels: 1.21.4

#1968 Prevent swim speed attribute applying to lava movement
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/extensions/ILivingEntityExtension.java
Labels: bug, 1.21.4

#1981 Patch in a Fluid#toString implementation so that FluidStack#toString is more readable
  patches/net/minecraft/world/level/material/Fluid.java.patch
Labels: 1.21.4
