Repository neoforged/NeoForge, pull requests merged in 2025-04, with the labels that each got.

#2083 Return a singleton EMPTY map from ModelData.Builder if the built map is empty (minor optimization)
  src/main/java/net/neoforged/neoforge/model/data/ModelData.java
Labels: enhancement, 1.21.5

#2094 Fix ModelData.EMPTY requiring itself to initialize
  src/main/java/net/neoforged/neoforge/model/data/ModelData.java
Labels: bug, rendering, regression, 1.21.5

#2098 [1.21.5] Fix render reload happening off-thread when toggling the light pipeline in the config file
  src/client/java/net/neoforged/neoforge/client/config/NeoForgeClientConfig.java
Labels: bug, rendering, 1.21.5

#2092 Use property assignment in buildscript
  build.gradle
Labels: cleanup, ci/build, 1.21.5

#2087 [1.21.5] Add per-BlockModelPart AO handling
  patches/net/minecraft/client/renderer/block/ModelBlockRenderer.java.patch
  src/client/java/net/neoforged/neoforge/client/config/NeoForgeClientConfig.java
  src/client/java/net/neoforged/neoforge/client/model/lighting/LightPipelineAwareModelBlockRenderer.java
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, rendering, breaking change, 1.21.5

#2099 [1.21.1] Fix render reload happening off-thread when toggling the light pipeline in the config file
  src/main/java/net/neoforged/neoforge/client/ClientHooks.java
Labels: bug, rendering, 1.21.1

#2089 [1.21.5] Fix not using "neoforge" mod ID for RecipePrioritiesProvider
  src/main/java/net/neoforged/neoforge/common/data/RecipePrioritiesProvider.java
  tests/src/generated/resources/data/neoforge/recipe_priorities.json
Labels: bug, 1.21.5

#2090 [1.21.4] Fix not using "neoforge" mod ID for RecipePrioritiesProvider
  src/main/java/net/neoforged/neoforge/common/data/RecipePrioritiesProvider.java
  tests/src/generated/resources/data/neoforge/recipe_priorities.json
Labels: bug, 1.21.4

#2101 Remove ICancellableEvent from LivingShieldBlockEvent
  src/main/java/net/neoforged/neoforge/event/entity/living/LivingShieldBlockEvent.java
Labels: bug, cleanup, 1.21.5

#2105 [1.21.5] Fix lighting of uncullable quads without AO
  patches/net/minecraft/client/renderer/block/ModelBlockRenderer.java.patch
  src/client/java/net/neoforged/neoforge/client/config/NeoForgeClientConfig.java
  src/client/java/net/neoforged/neoforge/client/model/lighting/LightPipelineAwareModelBlockRenderer.java
Labels: bug, rendering, regression, 1.21.5

#2111 [1.21.x] Fix parameter ordering issue in ItemStackedOnOtherEvent
  patches/net/minecraft/world/inventory/AbstractContainerMenu.java.patch
Labels: bug, 1.21.5

#2068 Make Loot Function without builders Constructors public
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, 1.21.5

#2112 Rewrite and split licensing info into two files
  LICENSE.txt
  README-LICENSE.md
Labels: documentation, 1.21.5

#2118 Remove legacy exc, sas, and srg files
  src/main/resources/forge.exc
  src/main/resources/forge.sas
  src/main/resources/forge.srg
Labels: cleanup, 1.21.5

#2106 Added custom splash text support
  patches/net/minecraft/client/resources/SplashManager.java.patch
  src/client/java/net/neoforged/neoforge/client/resources/NeoForgeSplashHooks.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: 1.21.5

#2078 Replace experimental light pipeline by a new enhanced AO pipeline
  patches/net/minecraft/client/multiplayer/ClientLevel.java.patch
  patches/net/minecraft/client/renderer/LightTexture.java.patch
  patches/net/minecraft/client/renderer/block/BlockRenderDispatcher.java.patch
  patches/net/minecraft/client/renderer/block/ModelBlockRenderer.java.patch
  patches/net/minecraft/client/renderer/block/model/FaceBakery.java.patch
  src/client/java/net/neoforged/neoforge/client/ClientHooks.java
  src/client/java/net/neoforged/neoforge/client/config/NeoForgeClientConfig.java
  src/client/java/net/neoforged/neoforge/client/event/AddSectionGeometryEvent.java
  src/client/java/net/neoforged/neoforge/client/model/ao/AoCalculatedFace.java
  src/client/java/net/neoforged/neoforge/client/model/ao/AoFace.java
  src/client/java/net/neoforged/neoforge/client/model/ao/EnhancedAoRenderStorage.java
  src/client/java/net/neoforged/neoforge/client/model/ao/FullFaceCalculator.java
  src/client/java/net/neoforged/neoforge/client/model/ao/package-info.java
  src/client/java/net/neoforged/neoforge/client/model/lighting/FlatQuadLighter.java
  src/client/java/net/neoforged/neoforge/client/model/lighting/LightPipelineAwareModelBlockRenderer.java
  src/client/java/net/neoforged/neoforge/client/model/lighting/QuadLighter.java
  src/client/java/net/neoforged/neoforge/client/model/lighting/SmoothQuadLighter.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, rendering, breaking change, 1.21.5

#2119 Make LootItemConditionalFunction#simpleBuilder Public
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, 1.21.5

#2137 Fix ComponentItemHandler#extractItem sometimes returning an incorrect result
  src/main/java/net/neoforged/neoforge/items/ComponentItemHandler.java
  tests/src/main/java/net/neoforged/neoforge/debug/capabilities/ItemInventoryTests.java
Labels: bug, 1.21.5

#2136 Register item handler capability for pale oak chest boats
  src/main/java/net/neoforged/neoforge/capabilities/CapabilityHooks.java
Labels: bug, 1.21.5

#2141 Remove MC-43968 fix (AO oversampling bug) for vanilla lighting
  patches/net/minecraft/client/renderer/block/ModelBlockRenderer.java.patch
Labels: bug, rendering, 1.21.5

#2130 [1.21.4] Make LootItemConditionalFunction#simpleBuilder and Loot Functions without builders Constructors public
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, backport, 1.21.4

#2143 Do not expose neoforge as a runtime transitive dependency of the test framework
  testframework/build.gradle
Labels: bug, 1.21.1

#2154 Allow mods with high OpenGL requirements to load during datagen
  src/main/java/net/neoforged/neoforge/client/loading/NoVizFallback.java
Labels: bug, 1.21.4

#2102 New Crowdin updates
  src/main/resources/assets/neoforge/lang/cs_cz.json
  src/main/resources/assets/neoforge/lang/da_dk.json
  src/main/resources/assets/neoforge/lang/de_de.json
  src/main/resources/assets/neoforge/lang/en_gb.json
  src/main/resources/assets/neoforge/lang/eo_uy.json
  src/main/resources/assets/neoforge/lang/es_es.json
  src/main/resources/assets/neoforge/lang/et_ee.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/hu_hu.json
  src/main/resources/assets/neoforge/lang/it_it.json
  src/main/resources/assets/neoforge/lang/ja_jp.json
  src/main/resources/assets/neoforge/lang/ko_kr.json
  src/main/resources/assets/neoforge/lang/ms_my.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/pt_br.json
  src/main/resources/assets/neoforge/lang/pt_pt.json
  src/main/resources/assets/neoforge/lang/ro_ro.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/sk_sk.json
  src/main/resources/assets/neoforge/lang/tr_tr.json
  src/main/resources/assets/neoforge/lang/tt_ru.json
  src/main/resources/assets/neoforge/lang/uk_ua.json
  src/main/resources/assets/neoforge/lang/vi_vn.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_tw.json
Labels: l10n, 1.21.5

#2158 Preserve datagen insertion order for GLMs
  src/main/java/net/neoforged/neoforge/common/data/GlobalLootModifierProvider.java
Labels: bug, data driven, 1.21.5

#2120 New Crowdin updates
  src/main/resources/assets/neoforge/lang/uk_ua.json
Labels: l10n, 1.20.6

#2177 Load configs earlier on the dedicated server
  patches/net/minecraft/client/server/IntegratedServer.java.patch
  patches/net/minecraft/gametest/framework/GameTestServer.java.patch
  patches/net/minecraft/server/MinecraftServer.java.patch
  patches/net/minecraft/server/TheGame.java.patch
  patches/net/minecraft/server/dedicated/DedicatedServer.java.patch
  patches/net/minecraft/server/level/ServerPlayer.java.patch
  patches/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch
  patches/net/minecraft/server/network/ServerHibernateConfigPacketListenerImpl.java.patch
  patches/net/minecraft/server/players/PlayerList.java.patch
  patches/net/minecraft/util/random/WeightedList.java.patch
  patches/net/minecraft/world/inventory/MenuType.java.patch
  patches/net/minecraft/world/item/FlintAndSteelItem.java.patch
  patches/net/minecraft/world/level/block/Block.java.patch
  patches/net/minecraft/world/level/levelgen/structure/Structure.java.patch
  src/client/java/net/neoforged/neoforge/client/ClientCommandSourceStack.java
  src/client/java/net/neoforged/neoforge/client/extensions/IDimensionSpecialEffectsExtension.java
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/common/world/ClimateSettingsBuilder.java
  src/main/java/net/neoforged/neoforge/common/world/ModifiableBiomeInfo.java
  src/main/java/net/neoforged/neoforge/event/server/ServerAboutToStartEvent.java
  src/main/java/net/neoforged/neoforge/event/server/ServerLifecycleEvent.java
  src/main/java/net/neoforged/neoforge/event/server/ServerStartingEvent.java
  src/main/java/net/neoforged/neoforge/network/IContainerFactory.java
  src/main/java/net/neoforged/neoforge/server/ServerLifecycleHooks.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/META-INF/accesstransformergenerated.cfg
  testframework/src/main/java/net/neoforged/testframework/gametest/DynamicStructureTemplates.java
  testframework/src/main/java/net/neoforged/testframework/junit/EphemeralTestServerProvider.java
  tests/src/main/java/net/neoforged/neoforge/debug/chat/CommandTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/data/DataMapTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/EntityEventTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/player/PlayerXpTests.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/world/ServerWorldCreationTest.java
  tests/src/main/resources/data/dimension_seed_test/dimension/fixed_seed_dimension.json
  tests/src/main/resources/data/dimension_seed_test/dimension/server_seed_dimension.json
  tests/src/main/resources/data/server_world_creation_test/dimension/server_world_creation_test.json
  tests/src/main/resources/data/server_world_creation_test/dimension_type/server_world_creation_test.json
  tests/src/main/resources/data/server_world_creation_test/worldgen/noise_settings/server_world_creation_test_noise.json
Labels: bug, 25w14craftmine

#2142 Fix forced chunks data serialization error
  src/main/java/net/neoforged/neoforge/common/util/NeoForgeExtraCodecs.java
  src/main/java/net/neoforged/neoforge/common/world/chunk/ForcedChunkManager.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/ExtraCodecsTests.java
Labels: bug, regression, 1.21.5

#2164 Sync datamaps of synced datapack registries to in memory connections
  src/main/java/net/neoforged/neoforge/common/NeoForgeEventHandler.java
Labels: bug, area: networking, area: data driven, 1.21.5

#1439 Sync server config changes to the connected clients
  src/main/java/net/neoforged/neoforge/common/NeoForgeEventHandler.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/network/ConfigSync.java
  src/main/java/net/neoforged/neoforge/network/NetworkInitialization.java
  src/main/java/net/neoforged/neoforge/network/configuration/SyncConfig.java
Labels: enhancement, area: networking, 1.21.1

#2135 Add support for baking multiple models in the standalone API
  patches/net/minecraft/client/resources/model/ModelManager.java.patch
  src/client/java/net/neoforged/neoforge/client/event/ModelEvent.java
  src/client/java/net/neoforged/neoforge/client/model/standalone/StandaloneModelBakerWrapper.java
  src/client/java/net/neoforged/neoforge/client/model/standalone/StandaloneModelKey.java
  src/client/java/net/neoforged/neoforge/client/model/standalone/StandaloneModelLoader.java
  src/client/java/net/neoforged/neoforge/client/model/standalone/UnbakedStandaloneModel.java
Labels: enhancement, area: rendering, 1.21.5

#2178 Use `IItemHandler#getSlotLimit` in `SlotItemHandler#getMaxStackSize`
  src/main/java/net/neoforged/neoforge/items/SlotItemHandler.java
Labels: bug, 1.21.5

#2200 Enhanced AO: Clamp vertex coordinates to [0, 1] in corner weight computation
  src/client/java/net/neoforged/neoforge/client/model/ao/AoFace.java
Labels: 1.21.5

#2190 Fix crash when defeating the ender dragon if there is no player reference
  patches/net/minecraft/world/entity/boss/enderdragon/EnderDragon.java.patch
Labels: bug, 1.21.5

#2179 Add item hand information to `LivingEntityUseItemEvent`s
  patches/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/entity/living/LivingEntityUseItemEvent.java
Labels: enhancement, 1.21.5

#2165 Make any holdersets always serialize and the not one delegate the check
  patches/net/minecraft/core/RegistrySetBuilder.java.patch
  src/main/java/net/neoforged/neoforge/registries/holdersets/AnyHolderSet.java
  src/main/java/net/neoforged/neoforge/registries/holdersets/NotHolderSet.java
  src/main/resources/META-INF/injected-interfaces.json
Labels: bug, 1.21.5, area: datagen

#2212 Make any holdersets always serialize and the not one delegate the check
  patches/net/minecraft/core/RegistrySetBuilder.java.patch
  src/main/java/net/neoforged/neoforge/registries/holdersets/AnyHolderSet.java
  src/main/java/net/neoforged/neoforge/registries/holdersets/NotHolderSet.java
Labels: bug, 1.21.3, area: datagen

#2224 Fix Vanilla clients crashing the server due to updated server config sync
  src/client/java/net/neoforged/neoforge/client/network/handlers/ClientPayloadHandler.java
  src/main/java/net/neoforged/neoforge/network/ConfigSync.java
Labels: bug, 1.21.5

#2235 Fix IShearable preventing other mods from capturing drops
  src/main/java/net/neoforged/neoforge/common/IShearable.java
Labels: 1.21.5, backport to 1.21.1

#2230 Fix a bug where cancelling AnvilUpdateEvent didn't make output empty
  patches/net/minecraft/world/inventory/AnvilMenu.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/event/AnvilUpdateEvent.java
  testframework/src/main/java/net/neoforged/testframework/gametest/ExtendedGameTestHelper.java
  tests/src/main/java/net/neoforged/neoforge/debug/capabilities/VanillaHandlersTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/crafting/AnvilUpdateEventTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/crafting/CraftingEventTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/loot/LootPoolTest.java
Labels: 1.21.5

#2231 add ability to get attachment data without an optional or creation
  patches/net/minecraft/world/level/chunk/ChunkAccess.java.patch
  src/main/java/net/neoforged/neoforge/attachment/AttachmentHolder.java
  src/main/java/net/neoforged/neoforge/attachment/IAttachmentHolder.java
Labels: 1.21.5

#1847 Respect WorldlyContainer nullability contracts in SidedInvWrapper
  src/main/java/net/neoforged/neoforge/capabilities/CapabilityHooks.java
  src/main/java/net/neoforged/neoforge/items/wrapper/SidedInvWrapper.java
Labels: bug, 1.21.4

#1446 Introduce proxyable and non-proxyable block capabilities
  src/main/java/net/neoforged/neoforge/capabilities/BlockCapability.java
  src/main/java/net/neoforged/neoforge/capabilities/CapabilityHooks.java
  src/main/java/net/neoforged/neoforge/capabilities/RegisterCapabilitiesEvent.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
Labels: enhancement, request for comments, 1.21.5
