Repository neoforged/NeoForge, pull requests merged in 2025-07, with the labels that each got.

#2401 Make sure that list in `GatherComponents` is mutable
  src/client/java/net/neoforged/neoforge/client/event/RenderTooltipEvent.java
Labels: bug, area: rendering

#2417 Fix effects and boss overlay being visible when they should be hidden
  patches/net/minecraft/client/gui/Gui.java.patch
Labels: bug, area: rendering, regression, 1.21.7

#2347 Test & errors UX improvements
  .github/workflows/build-prs.yml
  .github/workflows/check-local-changes.yml
  .github/workflows/test-prs.yml
  patches/net/minecraft/client/renderer/block/LiquidBlockRenderer.java.patch
  patches/net/minecraft/data/tags/EnchantmentTagsProvider.java.patch
  patches/net/minecraft/data/tags/TagsProvider.java.patch
  patches/net/minecraft/gametest/framework/GameTestServer.java.patch
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeAdvancementProvider.java
  testframework/src/main/java/net/neoforged/testframework/Test.java
  testframework/src/main/java/net/neoforged/testframework/client/AbstractTestScreen.java
  testframework/src/main/java/net/neoforged/testframework/impl/GameTestRegistration.java
  testframework/src/main/java/net/neoforged/testframework/impl/TestFrameworkImpl.java
  testframework/src/main/java/net/neoforged/testframework/impl/test/AbstractTest.java
  testframework/src/main/java/net/neoforged/testframework/impl/test/MethodBasedEventTest.java
  testframework/src/main/java/net/neoforged/testframework/impl/test/MethodBasedGameTestTest.java
  testframework/src/main/java/net/neoforged/testframework/impl/test/MethodBasedTest.java
  testframework/src/main/java/net/neoforged/testframework/summary/FileSummaryDumper.java
  testframework/src/main/java/net/neoforged/testframework/summary/GitHubActionsStepSummaryDumper.java
  testframework/src/main/java/net/neoforged/testframework/summary/JUnitSummaryDumper.java
  testframework/src/main/java/net/neoforged/testframework/summary/TestSummary.java
  tests/build.gradle
  tests/src/main/java/net/neoforged/neoforge/debug/client/DimensionTransitionScreenTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/MapDecorationRenderTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/TextureAtlasTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/data/CustomFeatureFlagsTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/data/registries/DatapackEntryTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/EntityTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/entity/player/AdvancementTests.java
  tests/src/main/java/net/neoforged/neoforge/debug/fml/MultipleEntrypointsTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/resources/ModDatapackTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/resources/RichTranslationsTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/DataGeneratorTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/DeferredHolderTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/DuplicateOptionalTagTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/PermissionTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/misc/RegistryCodecTest.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/world/LoginPacketSplitTest.java
  tests/src/main/resources/META-INF/neoforge.mods.toml
Labels: ci/build, 1.21.6, area: tests

#2341 New Crowdin updates
  src/main/resources/assets/neoforge/lang/cs_cz.json
  src/main/resources/assets/neoforge/lang/da_dk.json
  src/main/resources/assets/neoforge/lang/de_de.json
  src/main/resources/assets/neoforge/lang/en_gb.json
  src/main/resources/assets/neoforge/lang/eo_uy.json
  src/main/resources/assets/neoforge/lang/es_es.json
  src/main/resources/assets/neoforge/lang/et_ee.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/hu_hu.json
  src/main/resources/assets/neoforge/lang/it_it.json
  src/main/resources/assets/neoforge/lang/ja_jp.json
  src/main/resources/assets/neoforge/lang/ko_kr.json
  src/main/resources/assets/neoforge/lang/ms_my.json
  src/main/resources/assets/neoforge/lang/nl_nl.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/pt_br.json
  src/main/resources/assets/neoforge/lang/pt_pt.json
  src/main/resources/assets/neoforge/lang/ro_ro.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/sk_sk.json
  src/main/resources/assets/neoforge/lang/tr_tr.json
  src/main/resources/assets/neoforge/lang/tt_ru.json
  src/main/resources/assets/neoforge/lang/uk_ua.json
  src/main/resources/assets/neoforge/lang/vi_vn.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_tw.json
Labels: l10n, 1.21.6

#2422 Add `CompoundTag`/`ListTag` constructors with initial size
  patches/net/minecraft/nbt/CompoundTag.java.patch
  patches/net/minecraft/nbt/ListTag.java.patch
Labels: enhancement, backport to 1.21.1, backport to 1.21.3, backport to 1.20.6, backport to 1.21.4, backport to 1.21.5, 1.21.7

#2421 Add method to wrap gui layers
  src/client/java/net/neoforged/neoforge/client/event/RegisterGuiLayersEvent.java
  testframework/src/main/java/net/neoforged/testframework/impl/test/AbstractTest.java
  tests/src/main/java/net/neoforged/neoforge/debug/client/GuiTests.java
Labels: enhancement, area: rendering, 1.21.7

#2447 Fix issues with binding function keys on Mac systems
  patches/net/minecraft/client/gui/screens/options/controls/KeyBindsScreen.java.patch
Labels: bug, 1.21.7

#2458 Fix a decompiler issue that leads to infinite loops when dismounting a horse under certain conditions
  gradle.properties
Labels: 1.21.7

#2463 [1.21.1] Use real time based delta ticks in panorama renderer
  patches/net/minecraft/client/renderer/PanoramaRenderer.java.patch
Labels: bug, area: rendering, regression, 1.21.1

#2416 Update to FML 9.0.14
  gradle.properties
  projects/neoforge/build.gradle
Labels: blocks stable, 1.21.7

#2399 [1.21.7][B3D][Breaking] Add GpuDevice configuration, validation, and property reporting
  patches/com/mojang/blaze3d/buffers/GpuBuffer.java.patch
  patches/com/mojang/blaze3d/opengl/GlDevice.java.patch
  patches/com/mojang/blaze3d/platform/DepthTestFunction.java.patch
  patches/com/mojang/blaze3d/platform/DestFactor.java.patch
  patches/com/mojang/blaze3d/platform/SourceFactor.java.patch
  patches/com/mojang/blaze3d/shaders/ShaderType.java.patch
  patches/com/mojang/blaze3d/shaders/UniformType.java.patch
  patches/com/mojang/blaze3d/systems/RenderSystem.java.patch
  patches/com/mojang/blaze3d/textures/AddressMode.java.patch
  patches/com/mojang/blaze3d/textures/GpuTexture.java.patch
  patches/com/mojang/blaze3d/textures/TextureFormat.java.patch
  src/client/java/net/neoforged/neoforge/client/ClientHooks.java
  src/client/java/net/neoforged/neoforge/client/blaze3d/GpuDeviceFeatures.java
  src/client/java/net/neoforged/neoforge/client/blaze3d/GpuDeviceProperties.java
  src/client/java/net/neoforged/neoforge/client/blaze3d/opengl/DefaultGlDeviceFeatures.java
  src/client/java/net/neoforged/neoforge/client/blaze3d/opengl/DefaultGlDeviceProperties.java
  src/client/java/net/neoforged/neoforge/client/blaze3d/opengl/ImmutableGlDeviceFeatures.java
  src/client/java/net/neoforged/neoforge/client/blaze3d/opengl/ImmutableGlDeviceProperties.java
  src/client/java/net/neoforged/neoforge/client/blaze3d/opengl/package-info.java
  src/client/java/net/neoforged/neoforge/client/blaze3d/package-info.java
  src/client/java/net/neoforged/neoforge/client/blaze3d/validation/GpuDeviceUsageValidator.java
  src/client/java/net/neoforged/neoforge/client/blaze3d/validation/ValidationCommandEncoder.java
  src/client/java/net/neoforged/neoforge/client/blaze3d/validation/ValidationGpuDevice.java
  src/client/java/net/neoforged/neoforge/client/blaze3d/validation/ValidationGpuTexture.java
  src/client/java/net/neoforged/neoforge/client/blaze3d/validation/ValidationRenderPass.java
  src/client/java/net/neoforged/neoforge/client/blaze3d/validation/package-info.java
  src/client/java/net/neoforged/neoforge/client/config/NeoForgeClientConfig.java
  src/client/java/net/neoforged/neoforge/client/event/ConfigureGpuDeviceEvent.java
  src/client/java/net/neoforged/neoforge/client/extensions/blaze3d/GpuDeviceExtension.java
  src/client/java/net/neoforged/neoforge/client/extensions/blaze3d/package-info.java
  src/client/java/net/neoforged/neoforge/client/loading/NeoForgeLoadingOverlay.java
  src/main/java/net/neoforged/neoforge/internal/NonExhaustiveEnum.java
  src/main/resources/META-INF/injected-interfaces.json
  src/main/resources/assets/neoforge/lang/en_us.json
Labels: enhancement, area: rendering, breaking change, blocks stable, 1.21.7

#2474 Fix failing attachmentSyncTest game test
  tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentSyncTests.java
Labels: 1.21.7

#2473 Ignore unknown empty registries synced from the server
  src/client/java/net/neoforged/neoforge/client/network/ClientPayloadHandler.java
  src/main/java/net/neoforged/neoforge/registries/RegistryManager.java
Labels: backport to 1.21.1, 1.21.7

#2480 [1.20.4] Bump some dependencies
  gradle.properties
Labels: 1.20.4

#2471 [1.21.7][B3D] Add viewport to RenderPass
  patches/com/mojang/blaze3d/opengl/GlRenderPass.java.patch
  patches/com/mojang/blaze3d/systems/RenderPass.java.patch
  src/client/java/net/neoforged/neoforge/client/blaze3d/validation/ValidationRenderPass.java
Labels: enhancement, area: rendering, breaking change, 1.21.7

#2497 Account for integrated servers in `NeoForgeClientProxy#resolveLookup`
  src/client/java/net/neoforged/neoforge/client/internal/NeoForgeClientProxy.java
Labels: bug, regression, 1.21.8

#2484 [1.21.8] Allow adding additional states to foreign PoiTypes
  patches/net/minecraft/world/entity/ai/village/poi/PoiType.java.patch
  src/main/java/net/neoforged/neoforge/common/world/poi/ExtendPoiTypesEvent.java
  src/main/java/net/neoforged/neoforge/common/world/poi/PoiStateSet.java
  src/main/java/net/neoforged/neoforge/common/world/poi/PoiTypeExtender.java
  src/main/java/net/neoforged/neoforge/common/world/poi/package-info.java
  src/main/java/net/neoforged/neoforge/internal/RegistrationEvents.java
  tests/src/main/java/net/neoforged/neoforge/debug/block/BlockTests.java
Labels: enhancement, 1.21.8

#2499 [1.21.8] Only call IBlockEntityExtension#onLoad() on BEs that were properly added to the level
  patches/net/minecraft/world/level/Level.java.patch
Labels: bug, 1.21.8

#2512 [1.21.x] Fix ECJ issue with inner public class
  tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentSyncTests.java
Labels: 1.21.8

#2509 Fix the icon embedded in the installer profile by using an actual PNG
  buildSrc/src/main/java/net/neoforged/neodev/NeoDevPlugin.java
  docs/assets/installer_profile_icon.png
  docs/assets/neoforged_logo.png
Labels: 1.21.8

#2501 [1.21.8] Fix InventoryScreen.renderEntityInInventory() reusing entity render state for multiple entities of the same type
  patches/net/minecraft/client/gui/screens/inventory/InventoryScreen.java.patch
  tests/src/main/java/net/neoforged/neoforge/debug/client/GuiTests.java
Labels: bug, area: rendering, 1.21.8

#2525 Build: Bump MixinExtras to 0.5.0
  gradle.properties
Labels: 1.21.8

#2530 Fix #2510: Synced data attachments on players aren't re-sent when they change dimension
  patches/net/minecraft/server/level/ServerPlayer.java.patch
Labels: 1.21.8

#2522 Allow command suggestions/autocomplete to search all modded paths at once without namespace provided
  patches/net/minecraft/commands/SharedSuggestionProvider.java.patch
  tests/src/junit/java/net/neoforged/neoforge/unittest/CommandSuggestionTests.java
Labels: enhancement, 1.21.8

#2527 [1.21.8] Fix vehicle health not rendering in creative mode
  patches/net/minecraft/client/gui/Gui.java.patch
Labels: bug, area: rendering, regression, 1.21.8
