Repository neoforged/NeoForge, pull requests merged in 2025-09, with the labels that each got.

#2576 Expand the context of GrindstoneEvent.OnTakeItem
  patches/net/minecraft/world/inventory/GrindstoneMenu.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/event/GrindstoneEvent.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/misc/GrindstoneEventTest.java
Labels: 1.21.8

#2609 [1.21.8] Make Equipment Layer Types Extensible
  patches/net/minecraft/client/resources/model/EquipmentClientInfo.java.patch
  src/main/resources/META-INF/injected-interfaces.json
  tests/src/main/java/net/neoforged/neoforge/debug/client/ClientTests.java
  tests/src/main/resources/META-INF/enumextensions.json
  tests/src/main/resources/assets/neotests_custom_equipment_layer_type/textures/entity/equipment/neotests/layer_type/equipment_texture_present.png
Labels: enhancement, area: rendering, area: extensible enums, 1.21.8

#2607 Include remove entries when copying block tags
  src/main/java/net/neoforged/neoforge/common/data/BlockTagCopyingItemTagProvider.java
  tests/src/generated/resources/data/minecraft/tags/item/test_tag.json
  tests/src/main/java/net/neoforged/neoforge/oldtest/RemoveTagDatagenTest.java
Labels: bug, area: datagen, 1.21.8

#2610 Re-add reading of additional level save data
  patches/net/minecraft/client/gui/screens/worldselection/WorldOpenFlows.java.patch
  patches/net/minecraft/world/level/storage/LevelStorageSource.java.patch
Labels: bug, regression, 1.21.8

#2619 [1.21.5] Include remove entries when copying block tags
  patches/net/minecraft/data/tags/ItemTagsProvider.java.patch
  tests/src/generated/resources/data/minecraft/tags/item/test_tag.json
  tests/src/main/java/net/neoforged/neoforge/oldtest/RemoveTagDatagenTest.java
Labels: bug, 1.21.5, backport to 1.21.1, backport to 1.21.3, backport to 1.21.4, area: datagen

#2627 [1.21.x] Fix the bug that some blocks do not catch fire from lava when they should
  patches/net/minecraft/world/level/block/state/BlockBehaviour.java.patch
  patches/net/minecraft/world/level/material/LavaFluid.java.patch
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/IBlockStateExtension.java
Labels: 1.21.8

#2614 Transfer: Item Access
  src/main/java/net/neoforged/neoforge/transfer/access/HandlerItemAccess.java
  src/main/java/net/neoforged/neoforge/transfer/access/InfiniteMaterialsItemAccess.java
  src/main/java/net/neoforged/neoforge/transfer/access/ItemAccess.java
  src/main/java/net/neoforged/neoforge/transfer/access/OneByOneItemAccess.java
  src/main/java/net/neoforged/neoforge/transfer/access/PlayerItemAccess.java
  src/main/java/net/neoforged/neoforge/transfer/access/StackItemAccess.java
  src/main/java/net/neoforged/neoforge/transfer/access/package-info.java
  src/main/java/net/neoforged/neoforge/transfer/handlers/templates/fluids/ItemAccessFluidHandler.java
  src/main/java/net/neoforged/neoforge/transfer/handlers/templates/items/ItemAccessItemHandler.java
  src/main/java/net/neoforged/neoforge/transfer/handlers/templates/resources/ItemAccessResourceHandler.java
  src/main/java/net/neoforged/neoforge/transfer/handlers/wrappers/fluids/BucketResourceHandler.java
  src/main/java/net/neoforged/neoforge/transfer/handlers/wrappers/items/CarriedSlotWrapper.java
  tests/src/junit/java/net/neoforged/neoforge/unittest/transfer/ItemAccessHandlerTest.java
Labels: 1.21.7

#2660 Copper chest and tools into tags
  src/generated/resources/data/c/tags/block/chests.json
  src/generated/resources/data/c/tags/item/chests.json
  src/generated/resources/data/c/tags/item/tools/melee_weapon.json
  src/generated/resources/data/c/tags/item/tools/mining_tool.json
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeBlockTagsProvider.java
  src/main/java/net/neoforged/neoforge/common/data/internal/NeoForgeItemTagsProvider.java
Labels: enhancement, area: tags, 1.21.9
