Repository neoforged/NeoForge, pull requests merged in 2025-10, with the labels that each got.

#2466 Remove `WorldWorkerManager`
  src/main/java/net/neoforged/neoforge/common/NeoForgeEventHandler.java
  src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java
  src/main/java/net/neoforged/neoforge/common/WorldWorkerManager.java
Labels: breaking change, 1.22

#2678 [1.21.9] Fix and expand context of RenderNameTagEvent
  patches/net/minecraft/client/renderer/entity/EntityRenderer.java.patch
  patches/net/minecraft/client/renderer/entity/player/AvatarRenderer.java.patch
  src/client/java/net/neoforged/neoforge/client/event/RenderNameTagEvent.java
Labels: bug, enhancement, area: rendering, regression, 1.21.9

#2683 ResourceHandlerSlot: Fix mayPickup for empty resources
  src/main/java/net/neoforged/neoforge/transfer/item/ResourceHandlerSlot.java
Labels: 1.21.9

#2681 [1.21.9] Fix being unable to cancel world creation and editing
  patches/net/minecraft/client/gui/screens/worldselection/WorldSelectionList.java.patch
Labels: bug, regression, 1.21.9

#2645 [1.21.9] Give custom sprite sources access to set of additional metadata sections
  patches/net/minecraft/client/renderer/texture/SpriteLoader.java.patch
  patches/net/minecraft/client/renderer/texture/atlas/SpriteSourceList.java.patch
  src/client/java/net/neoforged/neoforge/client/extensions/SpriteSourceExtension.java
  src/main/resources/META-INF/injected-interfaces.json
Labels: enhancement, area: rendering, 1.21.9

#2661 [1.21.9] Handle custom chest textures in extract phase
  patches/net/minecraft/client/renderer/blockentity/ChestRenderer.java.patch
  patches/net/minecraft/client/renderer/blockentity/state/ChestRenderState.java.patch
Labels: enhancement, area: rendering, 1.21.9

#2648 [1.21.9] Rework level render hooks to match vanilla two-stage architecture
  patches/net/minecraft/client/renderer/GameRenderer.java.patch
  patches/net/minecraft/client/renderer/LevelRenderer.java.patch
  patches/net/minecraft/client/renderer/WeatherEffectRenderer.java.patch
  patches/net/minecraft/client/renderer/state/LevelRenderState.java.patch
  rejects_1_21_9-pre1/net/minecraft/client/renderer/WeatherEffectRenderer.java.patch.rej
  src/client/java/net/neoforged/neoforge/client/BlockEntityRenderBoundsDebugRenderer.java
  src/client/java/net/neoforged/neoforge/client/DimensionSpecialEffectsManager.java
  src/client/java/net/neoforged/neoforge/client/event/ExtractLevelRenderStateEvent.java
  src/client/java/net/neoforged/neoforge/client/event/RenderLevelStageEvent.java
  src/client/java/net/neoforged/neoforge/client/extensions/IDimensionSpecialEffectsExtension.java
  src/main/resources/META-INF/accesstransformer.cfg
  tests/src/main/java/net/neoforged/neoforge/debug/client/ClientEventTests.java
Labels: enhancement, area: rendering, 1.21.9

#2694 Add an `isEmpty` check in the hopper hook before extracting
  src/main/java/net/neoforged/neoforge/transfer/item/VanillaInventoryCodeHooks.java
Labels: 1.21.9

#2705 Collect sortable mod list into a mutable collection
  src/client/java/net/neoforged/neoforge/client/gui/ModListScreen.java
Labels: bug, 1.21.10
