Repository neoforged/NeoForge, pull requests merged in 2025-06, with the labels that each got.

#2303 [1.21.1] Fix root transforms with arbitrary rotations creating mangled quads
  patches/net/minecraft/client/renderer/block/model/FaceBakery.java.patch
  src/main/java/net/neoforged/neoforge/client/extensions/ModelStateExtension.java
  src/main/java/net/neoforged/neoforge/client/model/geometry/UnbakedGeometryHelper.java
  src/main/resources/META-INF/injected-interfaces.json
Labels: bug, area: rendering, regression, 1.21.1

#2322 Make all removal entries optional at runtime
  patches/net/minecraft/tags/TagEntry.java.patch
  patches/net/minecraft/tags/TagLoader.java.patch
Labels: bug, area: data driven, area: tags

#2308 [1.21.6] Avoid patching LanServerPinger into the dedicated server, using a neo-supplied implementation instead
  patches/net/minecraft/client/server/LanServerPinger.java.patch
  patches/net/minecraft/server/dedicated/DedicatedServer.java.patch
  src/main/java/net/neoforged/neoforge/common/config/NeoForgeServerConfig.java
  src/main/java/net/neoforged/neoforge/server/dedicated/DedicatedLanServerPinger.java
  src/main/java/net/neoforged/neoforge/server/dedicated/package-info.java
Labels: enhancement, 1.21.6

#2323 Allow client-side commands to run chat components
  patches/net/minecraft/client/multiplayer/ClientPacketListener.java.patch
Labels: enhancement, 1.21.1

#2316 Move attachment serialisers from raw NBT to ValueI/O
  patches/net/minecraft/world/entity/Entity.java.patch
  patches/net/minecraft/world/level/block/entity/BlockEntity.java.patch
  patches/net/minecraft/world/level/chunk/ChunkAccess.java.patch
  patches/net/minecraft/world/level/storage/TagValueInput.java.patch
  patches/net/minecraft/world/level/storage/TagValueOutput.java.patch
  src/main/java/net/neoforged/neoforge/attachment/AttachmentHolder.java
  src/main/java/net/neoforged/neoforge/attachment/AttachmentType.java
  src/main/java/net/neoforged/neoforge/attachment/IAttachmentSerializer.java
  src/main/java/net/neoforged/neoforge/attachment/LevelAttachmentsSavedData.java
  src/main/java/net/neoforged/neoforge/common/extensions/ValueInputExtension.java
  src/main/java/net/neoforged/neoforge/common/extensions/ValueOutputExtension.java
  src/main/resources/META-INF/injected-interfaces.json
  tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java
Labels: enhancement, breaking change, 1.21.6

#2168 New Crowdin updates
  src/main/resources/assets/neoforge/lang/cs_cz.json
  src/main/resources/assets/neoforge/lang/fr_fr.json
  src/main/resources/assets/neoforge/lang/pl_pl.json
  src/main/resources/assets/neoforge/lang/ro_ro.json
  src/main/resources/assets/neoforge/lang/ru_ru.json
  src/main/resources/assets/neoforge/lang/uk_ua.json
  src/main/resources/assets/neoforge/lang/zh_cn.json
  src/main/resources/assets/neoforge/lang/zh_tw.json
Labels: l10n, 1.21.6

#1866 Fix redstone neighbor update order differing from vanilla
  patches/net/minecraft/world/level/Level.java.patch
Labels: bug, divergence from vanilla, 1.21.6

#2340 Remove INBTSerializable in favor of ValueIOSerializable
  patches/net/minecraft/world/entity/Entity.java.patch
  patches/net/minecraft/world/level/block/entity/BlockEntity.java.patch
  patches/net/minecraft/world/level/chunk/ChunkAccess.java.patch
  patches/net/minecraft/world/level/chunk/storage/SerializableChunkData.java.patch
  src/main/java/net/neoforged/neoforge/attachment/AttachmentHolder.java
  src/main/java/net/neoforged/neoforge/attachment/AttachmentType.java
  src/main/java/net/neoforged/neoforge/attachment/IAttachmentSerializer.java
  src/main/java/net/neoforged/neoforge/attachment/LevelAttachmentsSavedData.java
  src/main/java/net/neoforged/neoforge/common/util/INBTSerializable.java
  src/main/java/net/neoforged/neoforge/common/world/LevelChunkAuxiliaryLightManager.java
  src/main/java/net/neoforged/neoforge/energy/EnergyStorage.java
  src/main/java/net/neoforged/neoforge/items/ItemStackHandler.java
  tests/src/main/java/net/neoforged/neoforge/debug/attachment/AttachmentTests.java
Labels: breaking change, 1.21.6

#2348 [1.21.6] Fix render fog event not being posted
  src/client/java/net/neoforged/neoforge/client/ClientHooks.java
  src/client/java/net/neoforged/neoforge/client/event/ViewportEvent.java
Labels: 1.21.6

#2306 [1.21.6] [Breaking] Avoid bundling binpatches for client classes for the server
  buildSrc/src/main/java/net/neoforged/neodev/NeoDevPlugin.java
Labels: bug, enhancement, breaking change, 1.21.6

#2343 Re-align FluidStack with ItemStack
  src/main/java/net/neoforged/neoforge/common/MutableDataComponentHolder.java
  src/main/java/net/neoforged/neoforge/common/util/DataComponentUtil.java
  src/main/java/net/neoforged/neoforge/fluids/FluidStack.java
  src/main/java/net/neoforged/neoforge/fluids/capability/templates/FluidTank.java
Labels: 1.21.6

#2381 [1.21.6] Fix air meter rendering below vehicle health
  patches/net/minecraft/client/gui/Gui.java.patch
Labels: 1.21.6

#2379 [1.21.6] Fix links in mod list crashing when accessed from the main menu
  src/client/java/net/neoforged/neoforge/client/gui/ModListScreen.java
Labels: bug, regression, 1.21.6

#2334 [1.21.1] Add registry context to `LootTableLoadEvent`
  patches/net/minecraft/world/level/storage/loot/LootDataType.java.patch
  src/main/java/net/neoforged/neoforge/common/CommonHooks.java
  src/main/java/net/neoforged/neoforge/event/EventHooks.java
  src/main/java/net/neoforged/neoforge/event/LootTableLoadEvent.java
  src/main/resources/META-INF/accesstransformer.cfg
  tests/src/main/java/net/neoforged/neoforge/debug/loot/LootPoolTest.java
Labels: 1.21.1

#2370 Update to FML 9.0.2
  gradle.properties
  projects/neoforge/build.gradle
Labels: 1.21.6

#2272 [1.21.6] Add separate client-side payload handler registration
  patches/net/minecraft/client/multiplayer/ClientCommonPacketListenerImpl.java.patch
  patches/net/minecraft/client/multiplayer/ClientConfigurationPacketListenerImpl.java.patch
  src/client/java/net/neoforged/neoforge/client/internal/NeoForgeClientProxy.java
  src/client/java/net/neoforged/neoforge/client/loading/ClientModLoader.java
  src/client/java/net/neoforged/neoforge/client/network/ClientPacketDistributor.java
  src/client/java/net/neoforged/neoforge/client/network/ClientPayloadHandler.java
  src/client/java/net/neoforged/neoforge/client/network/event/RegisterClientPayloadHandlersEvent.java
  src/client/java/net/neoforged/neoforge/client/network/event/package-info.java
  src/client/java/net/neoforged/neoforge/client/network/package-info.java
  src/client/java/net/neoforged/neoforge/client/network/registration/ClientNetworkRegistry.java
  src/client/java/net/neoforged/neoforge/client/network/registration/package-info.java
  src/main/java/net/neoforged/neoforge/internal/NeoForgeProxy.java
  src/main/java/net/neoforged/neoforge/network/NetworkInitialization.java
  src/main/java/net/neoforged/neoforge/network/PacketDistributor.java
  src/main/java/net/neoforged/neoforge/network/filters/GenericPacketSplitter.java
  src/main/java/net/neoforged/neoforge/network/handling/DirectionalPayloadHandler.java
  src/main/java/net/neoforged/neoforge/network/payload/AdvancedAddEntityPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/AdvancedContainerSetDataPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/AdvancedOpenScreenPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/AuxiliaryLightDataPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/ClientDispatchPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/ClientboundCustomSetTimePayload.java
  src/main/java/net/neoforged/neoforge/network/payload/ConfigFilePayload.java
  src/main/java/net/neoforged/neoforge/network/payload/FrozenRegistryPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/FrozenRegistrySyncCompletedPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/FrozenRegistrySyncStartPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/KnownRegistryDataMapsPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/RecipeContentPayload.java
  src/main/java/net/neoforged/neoforge/network/payload/RegistryDataMapSyncPayload.java
  src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java
  src/main/java/net/neoforged/neoforge/network/registration/PayloadRegistrar.java
  src/main/java/net/neoforged/neoforge/network/registration/PayloadRegistration.java
  testframework/src/main/java/net/neoforged/testframework/impl/TestFrameworkImpl.java
  testframework/src/main/java/net/neoforged/testframework/impl/packet/TestFrameworkPayloadInitialization.java
  tests/src/main/java/net/neoforged/neoforge/oldtest/misc/ModMismatchTest.java
Labels: enhancement, area: networking, 1.21.6
